### ISSUE TITLE
check_disk_smb uses -w and -c can't be set to be equal [sf#3316383]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1005]
Submitted by mfrostp83 on 2011-06-14 20:50:00

The check_disk_smb plugin seems to behave differently from other plugins in that it will not allow you to set them to be equal.

Commonly, we only want a critical alert and not a warning so we set them to be equal for a plugin (i.e. "-w 90% -c 90%").  When you do this with check_disk_smb, you get

    Percentage: warning (90%) should be less than critical (90%) 

Other plugins allow them to be set equal.  When they are equal, they seem to just ignore the warning threshold.

**Comment by riskersen** [comment]
So either remove default values which could break working setups or allow equal values and return with crit

**Comment by riskersen** [comment]
Should be okay with current release:

```
./check_disk -w 18% -c 18% -p /
DISK CRITICAL - free space: / 13187 MB (18% inode=89%);| /=56904MB;60035;60035;0;73214
```

Could be closed

**Comment by waja** [comment]
same here:

$ /usr/lib/nagios/plugins/check_disk -w 18% -c 18% -p /
DISK OK - free space: / 4620 MB (48% inode=91%);| /=4947MB;8264;8264;0;10079
$ /usr/lib/nagios/plugins/check_disk -V
check_disk v2.1.1 (monitoring-plugins 2.1.1)
