### ISSUE TITLE
check_ircd does not work with IPv6 [sf#3405551]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1019]
Submitted by cyco_dd on 2011-09-07 14:31:04

The following Bugreport we got against our debian package:

The check_ircd script uses low-level socket library calls and as such
cannot check IPv6 IRC servers.

It would probably make sense to rewrite this to use an IRC library.

Net::IRC is deprecated these daays (#608583) and claims that
Bot::BasicBot or POE::Component::IRC is the best way forward, but both
of those may be a little heavyweight, I suspect.
#822 may contain a working patch to add IPv6 support to the existing code,

although needing to pass the -6 flag isn't ideal.

Cheers,
Dominic.

You can track the bugreport via http://bugs.debian.org/638310

Many thanks, Jan.

**Comment by RincewindsHat** [comment]
Closed by #1995
