### ISSUE TITLE
check_http: add CONNECT method [sf#3414894]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1021]
Submitted by duncan_ferguson on 2011-09-28 10:21:35

Add 'CONNECT' method to chek+http

Patch taken from http://nagios.frank4dd.com/howto/monitor-ssl-websites-through-proxy.htm and reworked slightly for nagios-plugins-1.4.15

The arguments will be

check_http_new  -I <proxy> -p <proxy-port> -u <check-url> -S(sl) -j CONNECT -H <webserver>

A suggested test would be

check_http_new -I <proxyname> -p <proxyport> -u https://www.verisign.com/ -S -j CONNECT -H www.verisign.com

This has been tested by one of our Opsview customers and works as expected

  Duncs

**Comment by lazyfrosch** [comment]
@waja Should be obsolete since 2.2

**Comment by waja** [comment]
This should be done with 342dd1b97fd3423cb6368fedbb6c729f3c3b6243
