### ISSUE TITLE
check_disk_smb - Samba shares upper 2 To [sf#3312534]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1022]
Submitted by olikamm on 2011-06-06 17:14:26

Plugin Version (-V output): nagios-plugins 1.4.15
 Plugin Name: check_disk_smb
 Plugin Commandline showing issues: none
 Operating System: CentOS release 5.6 (Final)

The plugin cannot detect space on Samba shares over 2To. It still works, but if I have a 8To share with 2To used, the plugin will write 2047.93G (100%) free.

I guess this is a limitation on a int32 variable.

**Comment by RincewindsHat** [comment]
Looks like this was an `smbclient` problem
