### ISSUE TITLE
check_fping: added quick host-alive mode [sf#3458175]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1027]
Submitted by shrank on 2011-12-12 12:05:27

Hi there

I'm using check_fping to test around 1000 WAN Routers around the globe. Due to high delay and a normal packet loss I'm forced to use high timeouts and more Pings per test to prevent flapping. 

To reduce the check-duration, i added a host-alive flag which stops testing after the first successful reply.

Kind regards,

Michael

**Comment by RincewindsHat** [comment]
Might be worth implementing

**Comment by waja** [comment]
https://www.monitoring-plugins.org/attachments/430613-check_fping.c_patch

**Comment by waja** [comment]
closed by #1740 1740
