### ISSUE TITLE
check_http: print subject name in certificate check [sf#3462469]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1028]
Submitted by osk on 2011-12-19 18:01:48

This patch prints the subject name in certificate checks.
It also changes the date format to the more common YYYY-MM-DD HH:MM (unless AMERICAN_DATE_FORMAT is defined).

**Comment by waja** [comment]
fixed by e1ed1d805eafaef113e7a676f57cf9f5d0016099
