### ISSUE TITLE
Wrong Performance Data from check_disk [sf#3468344]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1031]
Submitted by jorg1985 on 2012-01-02 10:05:15

Hi,

There are wrong values in the performance data output of the check_disk plugin.
please check the following example:

definition:
label'=value[UOM];[warn];[crit];[min];[max]

if i take the diff of the value and the max value i cant reach the explored freespace value.
8068 - 1922 != 5736

This also affects the thresholds (w and c)

check_disk v1.4.15 (nagios-plugins 1.4.15)
 ./check_disk -w 10% -c 5% -p /
 DISK OK - free space: / 5736 MB (74% inode=96%);| /=1922MB;7261;7664;0;8068  

Best regards and a happy new year,
Jorg

**Comment by RincewindsHat** [comment]
This is most likely fixed by now
