### ISSUE TITLE
HTTP Check fails [sf#3515233]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1041]
Submitted by None on 2012-04-05 17:46:02

check_http plugin version 1.4.15 fails at times while a search and string match case as below: intrestingly, it fails only at times and works most of the time. could not identify what environment make it break. the earlier version tested (1.4.12 and 1.4.13) works fine when 1.4.15 fails. see the examples below:
```
# ../../libexec/check_http --version

check_http v1.4.15 (nagios-plugins 1.4.15)
```
example:
```
# ../../libexec/check_http -H servername  -u "/search-results?searchText=obama&search-header-search-submit=" -s "Displaying results" -t 60

HTTP CRITICAL: HTTP/1.1 200 OK - string 'Displaying results' not found on 'http://web6.aetv.com:80/search-results?searchText=obama&search-header-search-submit=' - 89652 bytes in 1.117 second response time |time=1.116784s;;;0.000000 size=89652B;;;0
```
This works fine with older version. see below:
```
# ../../libexec/check_http_v13 --version

check_http v2053 (nagios-plugins 1.4.13)
# ../../libexec/check_http_v13 -H server -u "/search-results?searchText=obama&search-header-search-submit=" -s "Displaying results" -t 60

HTTP OK HTTP/1.1 200 OK - 0.387 second response time |time=0.386511s;;;0.000000 size=89531B;;;0
```
Tested on : Redhat / Centos version 5.x
Tested Architecture: x86_64

Thanks

**Comment by RincewindsHat** [comment]
No idea what this was about, but this issue is dead.
