### ISSUE TITLE
please include check_yum  [sf#3539323]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1064]
Submitted by calestyo on 2012-07-01 21:10:55

(Roughly) From: http://tracker.nagios.org/view.php?id=306

Hi.

It's good that check_apt is already shipped as part of the nagios-plugins.

YUM is the current higher level package manager for all RedHat based distros, i.e. the majors RHEL (and its clones, like CentOS and Scientific Linux) and Fedora.

Therefore (because of its importance and wide spread), may I propose to include check_yum, too.

The official site for check_yum is:
https://code.google.com/p/check-yum/

The Nagios Exchange site is:
http://exchange.nagios.org/directory/Plugins/Operating-Systems/Linux/Check_Yum/details

Cheers.
Chris.

**Comment by RincewindsHat** [comment]
I don't think, this is gonna happen any time soon, since we are swamped with all the other stuff and that should be fixed first.
