### ISSUE TITLE
check_apt: document default OPTs for --update [sf#3539330]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1065]
Submitted by calestyo on 2012-07-01 21:43:19

(Roughly) From: http://tracker.nagios.org/view.php?id=303

Hi.

check_apt uses the following default options on update:
-q

Unlike the default options for --upgrade these are however undocumented in --help, which I suggest to add.

Cheers,
Chris

btw: I'd write patches.

**Comment by RincewindsHat** [comment]
that patch would have been nice.
