### ISSUE TITLE
configure hangs in environment without 127.0.0.1  [sf#3552819]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1071]
Submitted by calestyo on 2012-08-01 00:45:46

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## kensington:

In an environment without 127.0.0.1 (such as vserver), configure hangs on "checking for ICMP ping syntax...". 

Attached is a patch from bugs.gentoo.org/{44382,338247}.

**Comment by riskersen** [comment]
Duplicate with #756 thus closed
