### ISSUE TITLE
NRDP returns the string "Array ()" when you send it invalid  [sf#3552824]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1072]
Submitted by calestyo on 2012-08-01 00:48:09

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## Shawn Sterling:

When I send NRDP bad XML I get the following string returned:
Array
(
)
<?xml version="1.0" encoding="utf-8"?>
<result>
  <status>-1</status>
  <message>BAD XML</message>
</result>

Expected results:
<?xml version="1.0" encoding="utf-8"?>
<result>
  <status>-1</status>
  <message>BAD XML</message>
</result>

It would be best if I didn't send NRDP bad XML in the first place, but that's beside the point. :)

PS: NRDP is awesome thanks for making it.

**Comment by RincewindsHat** [comment]
NRDP is not part of this project afaik.
