### ISSUE TITLE
check_http false alarms  [sf#3552832]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1073]
Submitted by calestyo on 2012-08-01 00:55:19

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## nbardier:

check_http reports socket timeouts ("socket timeout after 30 seconds") against some hosts.
Although the problem only happens with those hosts, inmediatly after i get an alarm, i check the URL myself, and it's working.
I also tried raising from 10 to 30 seconds the command timeout, with no luck 

check_http v1.4.15 (nagios-plugins 1.4.15)

**Comment by RincewindsHat** [comment]
I don't think this can be reproduced and with amount of information it seems rather futile. Close the issue?

**Comment by RincewindsHat** [comment]
Please reopen if still occuring
