### ISSUE TITLE
TLS support lost installing on >= Debian Squeeze distro [sf#3552835]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1076]
Submitted by calestyo on 2012-08-01 01:01:58

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## VGavara:

TLS support is always off installing Nagios Plugins 1.4.15 on Debian Squeeze and more recent releases. Configuration process outputs:

...
checking for libgnutls-config... no
...
--with-gnutls: no 

The reason is that Nagios Plugins installation script needs libgnutls-config binary that has been deprecated since Debian Squeeze release, ie, is not being included in the libgnutls-dev package anymore.

**Comment by RincewindsHat** [comment]
Long dead
