### ISSUE TITLE
check_procs option -a fails on long command lines due to COL [sf#3552838]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1078]
Submitted by calestyo on 2012-08-01 01:09:31

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## Christoph Probst :

To receive a list of processes the check_procs plug-in uses

  /bin/ps axwo 'stat uid pid ppid vsz rss pcpu etime comm args'

ps limits its output in regard to the current value of the environment variable COLUMNS. If COLUMNS is set to a small value and the command line arguments of the process is very long (e.g. >1000 characters for a java command with many properties), a required command line argument (-a option) might not be found. 

Debugging becomes tricky as the value of COLUMNS depends on the current environment, when NRPE/check_procs is started. If the NRPE Daemon is started by init, the COLUMNS value might be a lot smaller (96 in my case) than if NRPE Daemon is restarted manually using /etc/init.d/nrpe restart. Actually it depends on the current xterm/putty windows size if the check turns green after a manuall restart or not.

**Comment by RincewindsHat** [comment]
I really hope this problem is long dead. This really is an unnecessary one.
