### ISSUE TITLE
check_disk -u bytes incorrect performance data  [sf#3552840]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1079]
Submitted by calestyo on 2012-08-01 01:12:58

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## aayala:

Hello

I use CentOS release 5.6 (Final) 64 bits, with:
check_disk v1.4.15 (nagios-plugins 1.4.15)

When i use:

check_disk -u bytes -w 20% -c 10%

Please NOTE -u bytes

return invalid performance data (negative values):

DISK OK - free space: / 45387558912 B (96% inode=99%); /boot 221027328 B (91% inode=99%); /dev/shm 525316096 B (100% inode=99%);| /=1714491392B;-2147483648;-2147483648;0;49665605632 /boot=20682752B;229381632;203639915;0;254868480 /dev/shm=0B;472784486;419727560;0;525316096

verbose output:

[root@ ~]# /usr/lib64/nagios/plugins/check_disk -u bytes -c 20.1% -w 10% -vvvv
Thresholds(pct) for / warn: 10.000000 crit 20.100000
calling stat on /
For /, total=12125392, available=11080947, available_to_root=11706815, used=418577, fsp.fsu_files=12517376, fsp.fsu_ffree=12473854
For /, used_pct=4 free_pct=96 used_units=1.71449e+09 free_units=4.53876e+10 total_units=4.96656e+10 used_inodes_pct=1 free_inodes_pct=99 fsp.fsu_blocksize=4096 mult=1
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /proc warn: 10.000000 crit 20.100000
calling stat on /proc
Thresholds(pct) for /sys warn: 10.000000 crit 20.100000
calling stat on /sys
Thresholds(pct) for /dev/pts warn: 10.000000 crit 20.100000
calling stat on /dev/pts
Thresholds(pct) for /boot warn: 10.000000 crit 20.100000
calling stat on /boot
For /boot, total=248895, available=215847, available_to_root=228697, used=20198, fsp.fsu_files=64256, fsp.fsu_ffree=64215
For /boot, used_pct=9 free_pct=91 used_units=2.06828e+07 free_units=2.21027e+08 total_units=2.54868e+08 used_inodes_pct=1 free_inodes_pct=99 fsp.fsu_blocksize=1024 mult=1
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /dev/shm warn: 10.000000 crit 20.100000
calling stat on /dev/shm
For /dev/shm, total=128251, available=128251, available_to_root=128251, used=0, fsp.fsu_files=128251, fsp.fsu_ffree=128250
For /dev/shm, used_pct=0 free_pct=100 used_units=0 free_units=5.25316e+08 total_units=5.25316e+08 used_inodes_pct=1 free_inodes_pct=99 fsp.fsu_blocksize=4096 mult=1
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /proc/sys/fs/binfmt_misc warn: 10.000000 crit 20.100000
calling stat on /proc/sys/fs/binfmt_misc
Thresholds(pct) for /var/lib/nfs/rpc_pipefs warn: 10.000000 crit 20.100000
calling stat on /var/lib/nfs/rpc_pipefs
DISK OK - free space: / 45387558912 B (96% inode=99%); /boot 221027328 B (91% inode=99%); /dev/shm 525316096 B (100% inode=99%);| /=1714491392B;-2147483648;-2147483648;0;49665605632 /boot=20682752B;229381632;203639915;0;254868480 /dev/shm=0B;472784486;419727560;0;525316096

and with only one partition:
[root@ ~]# /usr/lib64/nagios/plugins/check_disk -u bytes -c 20.1% -w 10% -vvvv -p /
calling stat on /
Thresholds(pct) for / warn: 10.000000 crit 20.100000
calling stat on /
For /, total=12125392, available=11080947, available_to_root=11706815, used=418577, fsp.fsu_files=12517376, fsp.fsu_ffree=12473854
For /, used_pct=4 free_pct=96 used_units=1.71449e+09 free_units=4.53876e+10 total_units=4.96656e+10 used_inodes_pct=1 free_inodes_pct=99 fsp.fsu_blocksize=4096 mult=1
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK OK - free space: / 45387558912 B (96% inode=99%);| /=1714491392B;-2147483648;-2147483648;0;49665605632

**Comment by RincewindsHat** [comment]
should be closed with #1714
