### ISSUE TITLE
autodiscovery fping issue  [sf#3552847]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1080]
Submitted by calestyo on 2012-08-01 01:19:07

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## michaelo:

Log extract
OUTPUT: /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/4mout7.xml
WATCH: /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/4mout7.watch
FPING CMD: /usr/sbin/fping -a -r 1 -g 10.72.14.128/25 2> /dev/null
ALIVE:
Array
(
    [0] => 10.72.14.128 [<- 10.72.8.196]
    [1] => 10.72.14.129
    [2] => 10.72.14.130
    [3] => 10.72.14.131
    [4] => 10.72.14.140
    [5] => 10.72.14.141
    [6] => 10.72.14.142
    [7] => 10.72.14.143
    [8] => 10.72.14.255 [<- 10.72.8.196]
)

the parse fails because of the [<- 10.72.8.196] returned by fping

the net result is the autodiscovery does not work.

**Comment by qiqiaobin** [comment]
I also want to konw the reason.

**Comment by RincewindsHat** [comment]
this seems to be a problem with nagios?
