### ISSUE TITLE
Warn when check_command argument is passed but the definitio [sf#3552853]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1082]
Submitted by calestyo on 2012-08-01 01:25:09

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## candlerb:

I propose that a warning is issued when parsing the config, if a check_command is invoked with arguments, but the command definition does not make use of those arguments.

Example: (This issue came up when using Ubuntu/Debian package of nagios 3.2.0)

The nagios documentation shows that if you want to monitor a different URI path, you use something like this:

```
 check_command check_http!-u /myapp/
```

However, the Debianized configs define check_http in /etc/nagios-plugins/config/http.cfg as:
# 'check_http' command definition
```
define command{
        command_name check_http
        command_line /usr/lib/nagios/plugins/check_http -H '$HOSTADDRESS$' -I '$HOSTADDRESS$'
        }
```
Note that there is no $ARG1$.

This means that if you provide arguments to check_http!.... they are accepted but silently ignored.

As a result, you may think you are monitoring a different uri path / port etc, but actually you are monitoring the server root. You may not discover this until the app dies and Nagios doesn't alert :-(

Furthermore: View Config > Services shows the arguments, leading to a further false sense of security.

<sarcasm>
"Debian Always Knows Best"
</sarcasm>

But this is a circumstance in which a warning is arguably useful in general. Suggested wording:

Warning: Extra arguments passed to service check command 'check_http' specified in service 'NAGIOS' will be ignored

(or maybe it should be an Error?)

As a bonus, it would be useful to report the file where the command was defined. This is because the fragmented Debian config doesn't include the 'define command' sections under /etc/nagios3/conf.d where you'd expect them, so you have to go hunting. Again, you can hardly blame nagios for this.

**Comment by RincewindsHat** [comment]
This look a)outdated and b)to be a problem for nagios and/or debian
