### ISSUE TITLE
check_dns plugin doesn't output correct the results  [sf#3552860]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1086]
Submitted by calestyo on 2012-08-01 01:31:35

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## Constantin007:

I guess there are 2 issues:
1. The resolved IP addresses are not returned when the plugin is run with -s option on some DNS servers:
# ./check_dns -H www.google.com -s 192.228.79.201 (<-rood DNS Server)

DNS OK: 0.201 seconds response time. www.google.com returns |time=0.200703s;;;0.000000

When using other local DNS:
# ./check_dns -H www.google.com -s 192.168.115.5
# DNS OK: 0.065 seconds response time. www.google.com returns 74.125.87.103,74.125.87.104,74.125.87.105,74.125.87.106,74.125.87.147,74.125.87.99|time=0.064952s;;;0.000000
1. The warning & critical thresholds are not reflected in the output performance:
# ./check_dns -H www.google.com -s 192.228.79.201 -w 10 -c 20

DNS OK: 0.213 seconds response time. www.google.com returns |time=0.212656s;;;0.000000
# ./check_dns -H www.google.com -s 192.168.115.5 -w 10 -c 20

DNS OK: 0.020 seconds response time. www.google.com returns 74.125.87.103,74.125.87.104,74.125.87.105,74.125.87.106,74.125.87.147,74.125.87.99|time=0.019878s;;;0.000000

Could you please investigate this? 

./check_dns -h
check_dns v1.4.14 (nagios-plugins 1.4.14)
Copyright (c) 1999 Ethan Galstad nagios@nagios.org
Copyright (c) 2000-2008 Nagios Plugin Development Team
        nagiosplug-devel@lists.sourceforge.net

./nagios --help

Nagios Core 3.2.0
Copyright (c) 2009 Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 08-12-2009
License: GPL

**Comment by ekohl** [comment]
This may be because check_dns uses nslookup which is [flawed and shouldn't be used](https://jdebp.eu/FGA/nslookup-flaws.html).

**Comment by sni** [comment]
I double checked those issues and i could not reproduce them. I assume they have been fixed meanwhile.
