### ISSUE TITLE
memory plugin doesn't account for cached memory  [sf#3552846]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1091]
Submitted by calestyo on 2012-08-01 01:17:50

Hi.

This is from the old / soon to be disabled again Nagios Plugins bug tracker that used to be at Nagios itself.
I've just copied this bug over. I'm not the original reporter and have no idea about the thoughts about this bug.
## vdanen:

keep getting warnings about memory usage on one system (it has 8GB RAM):

WARNING - 397 / 7987 MB (4%) Free Memory, Used: 7590 MB, Shared: 0 MB, Buffers: 813 MB, Cached: 5750 MB

This looks scary, but on a Linux box this is ok. Cached memory is actually a good thing, so while it is technically accurate, it should account for cached memory.

Instead of "Free Memory" it should probably report "Available Memory" in which case it wouldn't be 397MB available but 397MB (free) + 5.7GB (cached) which leaves me with just over 6GB available/usable memory.

**Comment by RincewindsHat** [comment]
There is (sadly) no plugin to check for memory usage (anymore?).
