### ISSUE TITLE
check_disk: -M meanting swapped? and -M documentation [sf#3560843]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1094]
Submitted by calestyo on 2012-08-23 03:02:43

Hi.

With check_disk v1.4.15 (nagios-plugins 1.4.15):
```
# /usr/lib/nagios/plugins/check_disk -l -u bytes -x /dev -x /lib/init/rw -x /dev/shm

DISK OK - free space: / 5560602624 B (61% inode=81%);| /=3483860992B;;;0;9528483840
# /usr/lib/nagios/plugins/check_disk -l -u bytes -x /dev -x /lib/init/rw -x /dev/shm -M

DISK OK - free space: /dev/mapper/vg_system-root 5560578048 B (61% inode=81%);| /dev/mapper/vg_system-root=3483885568B;;;0;9528483840
```
When I add -M the device and not the mountpoint is given; so the behaviour seems to be just swapped as documented.

Also, the documentation speaks about mountpoints vs. partitions.
Please use "devices" instead of partitions, as the devices need not to be partitions.

Cheers,
Chris.

**Comment by RincewindsHat** [comment]
#1746
