### ISSUE TITLE
document the base of binary units and support/use SI bases [sf#3560978]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1095]
Submitted by calestyo on 2012-08-23 13:50:16

Hi.

Currently the base of binary units in most (all?) plugins, e.g. check_disk which use them seems to be 1024.

This is though usually not documented, which makes the whole thing ambigous.

Please support SI units and use the correct units:

First that means that things like kB, MB or --megabytes of e.g. check_disk should no longer use the incorrect basis 1024.
k is always 1000, etc. pp.

The IEC standardised the use of e.g. KiB, MiB, GiB, TiB as units with the basis 1024.

Cheers,
Chris.

**Comment by RincewindsHat** [comment]
Fixed with #1714
