### ISSUE TITLE
check_ping add source interface [sf#3575281]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1101]
Submitted by europhil on 2012-10-07 16:25:07

sometimes it is useful to specify a source interface in a ping check e.g. to test routing.

I found an old solution here: http://osdir.com/ml/network.nagios.plugins.devel/2004-09/msg00010.html

I modified the latest check_ping.c according to this file (thanks to its author Oliver) - It works perfectly on Debian Squeeze with Icinga (latest stable releases downloaded on 2012-10-01) without any modifications to the Debian or Icinga System

**Comment by riskersen** [comment]
The attached patch is only manipulating ping call inside check_ping.c 

We should implement that based on source address with #1136 

Closed
