### ISSUE TITLE
check_ide_smart: Invalid argument [sf#3343431]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1104]
Submitted by domibarton on 2011-06-29 10:03:17

The check_ide_smart plugin fails on some disks w/ the following output:

```
# ./check_ide_smart -n -d /dev/sda

CRITICAL - SMART_ENABLE: Invalid argument
CRITICAL - SMART_CMD_ENABLE
```

But the disk is SMART capable:

```
# smartctl -i /dev/sda

smartctl version 5.33 [i686-redhat-linux-gnu] Copyright (C) 2002-4 Bruce Allen
Home page is http://smartmontools.sourceforge.net/

Device: MAXTOR   ATLAS10K4_36SCA  Version: DFV0
Serial number: B2SM1QGM
Device type: disk
Transport protocol: Parallel SCSI (SPI-4)
Local Time is: Wed Jun 29 10:02:31 2011 CEST
Device supports SMART and is Enabled
Temperature Warning Enabled
```

**Comment by spjmurray** [comment]
If it helps I've got a newer better version that will work on devices on SAS buses (and behind SAS expanders).  It doesn't use the archaic IDE ioctls, instead fires ATA commands embedded in SCSI at the storage device, relying on the SAT layer to decapsulate either in libata, the HBA or the SXP.  Feel free to have a play with https://github.com/spjmurray/check_scsi_smart and once all the bugs are ironed out and things are at a state I'll submit it for inclusion in monitoring-plugins

**Comment by glensc** [comment]
btw, does this plugin work?
https://github.com/glensc/nagios-plugin-check_raid

**Comment by spjmurray** [comment]
I'll have to check after xmas, but if it just checks the state of RAID arrays probably not.  This is more to do predictive failure analysis using the ATA SMART command set.  However I'm interested in that check, we've got a few old HP blades kicking about that would benefit :)

**Comment by waja** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690760#37 states it has been fixed
