### ISSUE TITLE
Nagios check_snmp not displaying enumeration values [sf#3586201]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1106]
Submitted by tomwong321456 on 2012-11-11 13:27:08

Hi, when I create a service to check_snmp values, if the snmp agent returns a enumeration value with the following declaration
```
rttState OBJECT-TYPE
SYNTAX INTEGER {
unknown(0),
running(1),
stopped(2)
}
MAX-ACCESS read-only
STATUS current
DESCRIPTION
"The currently configured status of an instance."
::= { rttEntry 3 }
```
if the command doesn't include a warning or critical threshold,
```
./check_snmp -p 161 -H 10.36.0.50 -o enterprises.40312.1.1.1.3.1 -C public -P 2c -l "rttState-Instance1" -m /usr/share/snmp/mibs/RTT-MIB.txt
```
the check_snmp command returns
`rttState-Instance1 OK - running(1) |`

However, if the warning or critical threshold is declared, such as
```
./check_snmp -p 161 -H 10.36.0.50 -o enterprises.40312.1.1.1.3.1 -C public -P 2c -l "rttState-Instance1" -m /usr/share/snmp/mibs/RTT-MIB.txt -w 1:2
```
it would return
```
rttState-Instance1 OK - 1 | RTT-MIB::rttState.1=1
```
It doesn't display the enumerated value.

**Comment by RincewindsHat** [comment]
I think this is an example of wrong usage.
