### ISSUE TITLE
Buffer overrun with -u option by check_snmp. [sf#3588761]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1115]
Submitted by one6f on 2012-11-20 16:58:45

Plugin Version (-V output): rested with check_snmp v1.4.16 (nagios-plugins 1.4.16) and v1.4.15

Plugin Name: check_snmp

Plugin Commandline showing issues:
```
./check_snmp -H 10.31.17.180 -C public -o "ifOperStatus.1,ifOperStatus.17,ifOperStatus.18,ifOperStatus.21,ifOperStatus.29" -u "port_1","port_17","port_18","port_21","port_29"
ï¿½ï¿½ OK - up(1) port_1 up(1) port_17 up(1) port_18 up(1) port_21 up(1) port_29 |
```
If I leave out the last unit, "port_29", it shows SNMP OK 

Operating System:Ubuntu 10.04 LTS
Architecture: 64bit
Compiler: tested with apt-get install or self compiled with gcc

**Comment by RincewindsHat** [comment]
Should be fixed.
