### ISSUE TITLE
check_by_ssh exit status when reaching timeout [sf#2859548]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1123]
Submitted by guillomovitch on 2009-09-15 22:30:06

check_by_ssh currently exist with CRITICAL status when reaching timeout. When used just as a transport mechanism for invoking a remote plugin, it should rather exit with UNKNOWN status in this case.

The patch is trivial, I'd be happy to contribute it if this is agreed.

**Comment by barry-luijten** [comment]
> There is an easy workaround: you can achieve the same effect by adding the -oConnectTimeout=XX flag where XX is slightly less than the timeout set with the -t flag.

The workaround results in an exit code of 255, which is still translated into Critical by Nagios and mod_gearman. The result message however starts with "UNKNOWN", so this is a cosmetic workaround imho.
I would really appreciate it if the -u switch will be implemented for check_by_ssh...

**Comment by archiecobbs** [comment]
> The workaround results in an exit code of 255, which is still translated into Critical by Nagios and mod_gearman. The result message however starts with "UNKNOWN", so this is a cosmetic workaround imho.
I would really appreciate it if the -u switch will be implemented for check_by_ssh...

Done - see my PR #1774.

**Comment by RincewindsHat** [comment]
Resolved by #1123

**Comment by RincewindsHat** [comment]
#1774  ok, yes :-)
