### ISSUE TITLE
check_nt "Network is unreachable" handling [sf#3601012]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1125]
Submitted by rfults on 2013-01-15 20:28:25

It would be nice to have the option to either ignore "network is unreachable" errors or control the status they return.  I am running my checks over very low bandwidth satellite links and have frequent disconnects, when this error is returned it can generate thousands of emails which has made the notification system useless for me.  I only send critical, warning, and recovery emails for my services and hosts as it is, but this feature would help to reduce false positives in these situations where we have bad connections.

**Comment by RincewindsHat** [comment]
I think this should be handled by service dependencies on the side of the monitoring system.
