### ISSUE TITLE
check_snmp can't do IPv6 [sf#3602488]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1128]
Submitted by seegras on 2013-01-29 10:32:43

root@monitor1:/usr/src/nagiosplug/plugins# ./check_snmp --version 
check_snmp v1.4.16.72.gf4bbd (nagios-plugins 1.4.16)
root@monitor1:/usr/src/nagiosplug/plugins# ./check_snmp  -H 'ipv6.hostname.example' -C 'public' -o  '.1.3.6.1.2.1.25.1.1.0'
External command error: getaddrinfo: ipv6.hostname.example Name or service not known

Neither can 1.4.14.

**Comment by waja** [comment]
n-p has an issue about that to: https://github.com/nagios-plugins/nagios-plugins/issues/84

Patch maybe available at: https://github.com/nagios-plugins/nagios-plugins/commit/bf9aa4d647281425ba77b287ecf48501aeac9e7d#diff-a3c534e51df69a1d0c6a1b18fed94550

**Comment by RincewindsHat** [comment]
seems like this was implemented. Closing this issue therefore

**Comment by waja** [comment]
this was implemented by 7276ce77c7f1dc682b6ac0b58d78445c6bb814bf
