### ISSUE TITLE
check_smtp -D (1.4.16) doesn't QUIT [sf#3608135]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1130]
Submitted by j-bern on 2013-03-15 10:24:28

Plugin Version (-V output): 1.4.16
Plugin Name: check_smtp
Plugin Commandline showing issues: check_smtp -H [postfix-MTA-IP] -F nagios.[domain] -S -D 5,2 -v
Operating System: CentOS
Architecture: x86_64
Compiler: (from repos)

check_smtp -D executes the "if ( check_cert )" branch, which calls my_close(), which closes the connection. No SMTP QUIT command is being sent, which makes the (postfix) MTA log "lost connection after EHLO" warning messages. Please include an smtp_quit() somewhere along this code path.

(I'm not submitting a patch myself because I don't know offhand whether the smtp_quit() should go into the "if ( check_cert )" branch alone, or become part of my_close(), which also handles two EHLO error cases.)

**Comment by siccegge** [comment]
FWIW my_close seems to be an utility function that is not only used for check_smtp but for any (tcp?) connection by any plugin.

However the question remains whether it should quit just yet at that point. The way to code currently works it will skip most of the tests if -D is used .. including all the Command and Auth stuff

**Comment by RincewindsHat** [comment]
This was fixed with b317aaf32a8a054f0274aef9137353bffef7a80c.
But yes, many of the network plugins exit early if they check for the certificate. This is unfortunate (and should probably be changed).
