### ISSUE TITLE
check_udp plugin can't check port state [sf#3612567]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1138]
Submitted by dkorzhevin on 2013-05-03 15:08:59

Hi,

I use icinga 1.8.4 with nagios-plugins 1.4.16 on Debian 6.0.7 x86_64. I try to use check_udp plugin to check remote server udp port 53 (DNS) state:

./check_udp -H 192.81.219.105 -p 53 -s "" -e "" -t 15

A always receive error: "CRITICAL - Socket timeout after 15 seconds"

But, port is open, and i know that. Even netcat show this (i use openbsd-netcat 1.105):

nc -vzu 192.81.219.105 53
Connection to 192.81.219.105 53 port [udp/domain] succeeded!

Seems, this is problem of check_udp plugin?

I will provide any info to investigate this issue

**Comment by RincewindsHat** [comment]
So, this is late a lot, but maybe someone is listening. Is this issue still there? Can it be reproduced?

Otherwise: Can this issue be closed?

**Comment by RincewindsHat** [comment]
Closing this. Checking for DNS servers should be done with `check_dns` or `check_dig` and sending nothing to a UDP Port probably results in not much anyway. There is no connection to monitor
