### ISSUE TITLE
check_disk show 0% used on some part on AIX [sf#3613736]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1157]
Submitted by cameleon078 on 2013-05-22 18:20:25

I have an issue on check_disk on some part on AIX system.

-bash-3.00# /var/opt/nagios/plugins/check_disk -w 5% -p /dev/tsm02fORA0lv -vvvv
calling stat on /dev/tsm02fORA0lv
For /ptsm02/server/filesORA0, used_pct=100 free_pct=0 used_units=1831 free_units=0 total_units=1.1991e+07 used_inodes_pct=1 free_inodes_pct=99 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=0
Freespace% result=1
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK WARNING - free space: /ptsm02/server/filesORA0 0 MB (0% inode=99%);| /ptsm02/server/filesORA0=1831MB;11391488;;0;11991040

-bash-3.00# df -k /dev/tsm02fORA0lv                                             Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/tsm02fORA0lv 12278824960 12276949612    1%        5     1% /ptsm02/server/filesORA0

-bash-3.00# df -i /dev/tsm02fORA0lv
Filesystem    512-blocks      Free %Used    Iused %Iused Mounted on
/dev/tsm02fORA0lv 24557649920 24553899224    1%        5     1% /ptsm02/server/filesORA0

**Comment by RincewindsHat** [comment]
Closed until this can be replicated in 2021+
