### ISSUE TITLE
check_http add warning and critical pattern search

### ISSUE THREAD

**Issue by davmik** [monitoring-plugins/monitoring-plugins#1213]
There are only two parameter available (-r|-R) for pattern search which return by default ok if matched and critical if not (as long as there is no --invert-regex param given). Some new parameters like -wr and -wR would be nice to do the same like -r or -R but will return warning instead of critical.
As soon as both parameters would be given --invert-regex would be set by default and if both regex for warning and critical would match, critical would be returned.

**Comment by RincewindsHat** [comment]
Sorry for not answering.
Sounds like a nice idea, but I think it would be wasted time to include that in `check_http`, maybe @andreasbaumann would be interested to implement something like that in `check_curl`.

**Comment by RincewindsHat** [comment]
Personaly I would just skip the short options, they are convenient vor CLI commands, but these programs are executed by other programs most of the time. Long options only is IMHO OK.

I personally dislike positional arguments, at least with Icinga2 I don't have a guarante for a fixed order and in general they add additional unneeded complexity. At least that's my opinion

**Comment by waja** [comment]
> I personally dislike positional arguments

Second that.

**Comment by C0rn3j** [comment]
This should already be fixed by #2006

**Comment by RincewindsHat** [comment]
Indeed, thanks for doing the bookkeeping
