### ISSUE TITLE
check_pgsql is too restrictive with database names

### ISSUE THREAD

**Issue by dlangille** [monitoring-plugins/monitoring-plugins#1214]
Hi,

check_pgsql restricts database names to [^_a-zA-Z0-9-]

However, that's not valid for quoted identifiers, such as "freshports.org"

Any character, except null, is valid.

ref: http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

"Quoted identifiers can contain any character, except the character with code zero."

Blog post: http://dan.langille.org/2013/11/14/nagios-plugin-check_pgsql-cant-handle-all-valid-database-names/

HTH

**Comment by RincewindsHat** [comment]
According to [https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS](the postgres docu) this would be korrekt, but it seems like this is not the current practise.

**Comment by RincewindsHat** [comment]
Fixed by 2d9c6276d0a380f831bf94734359f071d0c7e958

**Comment by dlangille** [comment]
I remember this now that I read it again. :) Thank you.

**Comment by RincewindsHat** [comment]
No problem :-)
