### ISSUE TITLE
check_dig is case sensitive

### ISSUE THREAD

**Issue by stirnim** [monitoring-plugins/monitoring-plugins#1233]
check_dig is case sensitive about the query answer which leads to a warning: Server not found in ANSWER SECTION.

See verbose output:
/usr/lib/nagios/plugins/check_dig -H dns-cache2.switch.ch -vvvv -l 6to4-relay.switch.ch
/usr/bin/dig @dns-cache2.switch.ch -p 53 6to4-relay.switch.ch -t A 
Looking for: '6to4-relay.switch.ch'
;; ANSWER SECTION:
6TO4-RELAY.switch.ch.	81981	IN	A	130.59.31.253

;; AUTHORITY SECTION:
switch.ch.		2221	IN	NS	ns2.switch.ch.
switch.ch.		2221	IN	NS	scsnms.switch.ch.

;; ADDITIONAL SECTION:
ns2.switch.ch.		160647	IN	A	130.59.138.49
ns2.switch.ch.		160647	IN	AAAA	2001:620:0:1b:5054:ff:fe74:8780
scsnms.switch.ch.	160647	IN	A	130.59.1.30
scsnms.switch.ch.	160647	IN	A	130.59.10.30
scsnms.switch.ch.	160647	IN	AAAA	2001:620::1

;; Query time: 12 msec
;; SERVER: 2001:620:0:ff::3#53(2001:620:0:ff::3)
;; WHEN: Fri Feb  7 12:42:51 2014
;; MSG SIZE  rcvd: 208

DNS WARNING - 0.033 seconds response time (Server not found in ANSWER SECTION)|time=0.033127s;;;0.000000

**Comment by ch82** [comment]
check_dig uppercase problems #114 really duplicates this, but more then year passed and I see no fix.

**Comment by waja** [comment]
@ch82 you are more then welcome to provide a fix. For example via a Pull Request.

**Comment by riskersen** [comment]
@stirmin i would like to add your patch as PR but i need your mail address to commit for you

**Comment by stirnim** [comment]
I've not created a pull request. Can't you just create one yourself? It's
one line that changed.

**Comment by riskersen** [comment]
Yeah i've prepared a PR for your fix, but it wanted to set you as author for kudos =)

**Comment by stirnim** [comment]
nice ;)
daniel.stirnimann @ gmail . com
