### ISSUE TITLE
Update check_icmp to use op5 version

### ISSUE THREAD

**Issue by awiddersheim** [monitoring-plugins/monitoring-plugins#1238]
Looks like check_icmp has been enhanced by the op5 team but those enhancements haven't made it back into the plugins project.

http://git.op5.org/git/?p=nagios/op5plugins/check_icmp.git;a=blob;f=check_icmp.c;h=f559ea29c1991050519ab7093c3a7e1fe6606508;hb=HEAD

Just briefly looking at the op5 version it has much better help output and when trying it the intervals work as one would expect.

Perhaps it might be a good idea to pull in their version.

**Comment by RincewindsHat** [comment]
It seems like this topic is quite dead. Well, op5 is also dead and the link is unreachable. If nobody here saved the the other version (and I have trouble finding it on first try) I would suggest to close the issue.

**Comment by jacobbaungard** [comment]
We (OP5) are still around. However it's our plan to start using the upstream monitoring-plugins version shortly. Perhaps there are still some things in our downstream version that could be useful, but it's probably not straight forward to upstream those changes, as per the previous discussions.

Anyway, I think it's fine we close this, I might have a look at some point later, and create PRs if I find anything useful in our downstream version. If anyone else want to have a go at it, let me know and I can provide the source.

**Comment by RincewindsHat** [comment]
Oh, I am sorry. It seems like I got the wrong impression from the first few links I found. Thanks for the feedback.
