### ISSUE TITLE
Make it possible for check_tcp to inhibit "TCP " in output

### ISSUE THREAD

**Issue by Seegras** [monitoring-plugins/monitoring-plugins#1240]
We've got the issue of having to check something from a remote server; which can easily be done like this in /etc/snmp/snmpd.conf

extend connection /usr/lib/nagios/plugins/check_tcp -H <remote> -p 8080
And checking for 
check_snmp_extend!connection 
in icinga/nagios. 

Which would work but for 
TCP OK - 0.002 second response time on port 8080|time=0.002008s;;;0.000000;10.000000
That "TCP " in front of the OK. 

I loathe to make my own package; so I'd appreciate it if you just could add a flag to it to inhibit this. I can make a patch if you want one, but it's fairly trivial.

**Comment by RincewindsHat** [comment]
Closing this to clean up a little bit. Reworking the output is still on my list though
