### ISSUE TITLE
~/.my.cnf may not be loaded properly in check_mysql.c under some conditions

### ISSUE THREAD

**Issue by skottler** [monitoring-plugins/monitoring-plugins#1250]
In #1199, there's some strace output that shows `/root/..cnf`. This appears to be a bug that manifests itself when there's not a `.my.cnf` in the user's homedir, but I'll look into it more.

**Comment by RincewindsHat** [comment]
Is this still a thing?

**Comment by waja** [comment]
I think we should close the bug. If someone disagree, we might reopen the bug.
