### ISSUE TITLE
check_oracle command line arguments not quoted

### ISSUE THREAD

**Issue by horihel** [monitoring-plugins/monitoring-plugins#1258]
check_oracle uses "naked" arguments ($1 $2) which causes special characters to be interpreted by the shell.
Especially this causes check_oracle to fail if you use a full TNS description as a SID because it contains parentheses. Putting Quotes around those parameters fixes the problem.

**Comment by RincewindsHat** [comment]
Probably already fixed 8294af907bd8482a86df749f562b7ec09e3faeed or something similar.
Please reopen if still valid
