### ISSUE TITLE
monitoring-plugins.spec.in: Needs some love

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1273]
After renaming into monitoring-plugin the spec file is not in a good shape.

I guess the following should be reviewed:

https://github.com/monitoring-plugins/monitoring-plugins/commit/63734f52ab1b4b2c17545b26fc41016d6bbd80bd#commitcomment-6980575

Anyways ... I don't know rpm very well anymore, but I guess there are other places which can be improved.

**Comment by waja** [comment]
OP5 has also a spec file available for their build: http://git.op5.org/gitweb?p=system-addons/plugins/nagiosplug.git;a=blob_plain;f=op5build/nplug.spec;hb=HEAD

**Comment by wols** [comment]
I was looking for a current EPEL/monitoring-plugins.rpm today :-1:
Any old stuff like...
- [Version 2.1 Released](https://www.monitoring-plugins.org/news/release-2-1.html) with a link to https://github.com/monitoring-plugins/monitoring-plugins/pull/1283
- [monitoring-plugins as rpm?](https://monitoring-portal.org/woltlab/index.php?thread/34746-monitoring-plugins-as-rpm/)
- [Red Hat Bugzilla – Bug 1054340](https://bugzilla.redhat.com/show_bug.cgi?id=1054340)
- [RPM resource monitoring-plugins](http://rpmfind.net/linux/rpm2html/search.php?query=monitoring-plugins&submit=Search+...&system=&arch=x86_64)

Is not the time yet ripe?

**Comment by waja** [comment]
Looks like we can drop that for #1894?

**Comment by RincewindsHat** [comment]
I think so too.
