### ISSUE TITLE
check_disk usage tecnically incorrect, -w and -c not always mandatory

### ISSUE THREAD

**Issue by mfalkvidd** [monitoring-plugins/monitoring-plugins#1293]
The usage for check_disk:
 check_disk -w limit -c limit [-W limit] [-K limit] {-p path | -x device}
says that the -w and -c limits are mandatory. However, they are no longer mandatory (and should probably not be) if -W and -K are provided. Example:
$ sudo /opt/plugins/check_disk -W 0 -K 0 -p /scratch
DISK OK - free space: /scratch 0 MB (0% inode=99%);| /scratch=989MB;;;0;1007

This was identified by one of our customers. They are happy with the way the plugin works now[1], but they are worried that this "undocumented feature" might not work in the future.

I'm not sure if there is a way to correctly express this possibility in the help text. A solution could be something like this:
 check_disk {-w limit -c limit | -W limit -K limit}  {-p path | -x device}
but that would discourage the use of both disk usage and inode usage at the same time, which is allowed:
$ sudo /opt/plugins/check_disk -w 70 -c 70 -W 90 -K 90 /
DISK OK - free space: / 4996 MB (25% inode=92%);| /=14683MB;20659;20659;0;20729

[1] This customer wants to graph disk usage over time, but they don't want warnings even if the file system is full. Since they don't expect their file system to run out of inodes, the current solution suits them perfectly.

**Comment by RincewindsHat** [comment]
Put this into an PR #1745
