### ISSUE TITLE
check_snmp: default timeout incorrect in --help output

### ISSUE THREAD

**Issue by jyoung15** [monitoring-plugins/monitoring-plugins#1318]
running check_snmp -h shows the following

    -t, --timeout=INTEGER
        Seconds before connection times out (default: 10)

In check_snmp.c, this comes from DEFAULT_SOCKET_TIMEOUT:

    printf (UT_CONN_TIMEOUT, DEFAULT_SOCKET_TIMEOUT);

However the actual timeout is defined in DEFAULT_TIMEOUT (which is 1 second, not 10)

    timeout_interval = DEFAULT_TIMEOUT;

**Comment by riskersen** [comment]
Is there any reason to not use DEFAULT_SOCKET_TIMEOUT from utils.h?

I'm creating a pull request for this inconsistency

**Comment by waja** [comment]
Fixed by #1325 in maint branch
