### ISSUE TITLE
check_disk: missing -lrt on Solaris

### ISSUE THREAD

**Issue by nameless-user** [monitoring-plugins/monitoring-plugins#1329]
The following is being reported against monitoring-plugins-v2.1.1-39-g8095.

In the link of `check_disk.o` on Solaris 8, I get:

    Undefined                       first referenced
    symbol                             in file
    nanosleep                           check_disk.o
    ld: fatal: Symbol referencing errors. No output written to check_disk
    *** Error code 1
    make: Fatal error: Command failed for target `check_disk'

A look at the man page for nanosleep(3RT) on this platform shows that
it requires the `-lrt` library to be linked in, to access this function.

**Comment by waja** [comment]
@druchoo complaint at https://github.com/monitoring-plugins/monitoring-plugins/commit/6986aa1d0a352d8d02eed4896034631fffd25a27#commitcomment-9428666 about nanosleep anyways

**Comment by waja** [comment]
@sthen opened https://github.com/monitoring-plugins/monitoring-plugins/issues/1377 too
