### ISSUE TITLE
check_disk: format warning

### ISSUE THREAD

**Issue by hydrapolic** [monitoring-plugins/monitoring-plugins#1331]
After compiling monitoring-plugins-2.1.1 with gcc 4.8 / 4.9, there is a warning:

check_disk.c:1005:18: warning: format '%llu' expects a matching 'long long unsigned int' argument [-Wformat=]

**Comment by awiddersheim** [comment]
I think #1326 addresses this issue.

**Comment by waja** [comment]
this code was introduced with 77f2c84d2f599d86a60586494169dcab17853e3a

**Comment by RincewindsHat** [comment]
should be fixed with #1695
