### ISSUE TITLE
monitoring-plugins-2.1.1 check_tcp -D didn't work as expected

### ISSUE THREAD

**Issue by nuts424** [monitoring-plugins/monitoring-plugins#1333]
Hi,

i'll check the validation of certificates e.g. with check_tcp -D but it doesn't return the expected value.

The following command [1] leads to [2]

[1] /usr/lib/nagios/plugins/check_tcp -H heise.de -p 443 -S -D 1000,2000
[2] TCP OK - 0.032 second response time on heise.de port 443|time=0.032378s;;;0.000000;10.000000

Expected (nagios-plugins-1.4.15): 
/usr/lib/nagios/plugins/check_tcp -H heise.de -p 443 -S -D 1000
WARNING - Certificate expires in 186 day(s) (10/15/2015 23:59).

**Comment by waja** [comment]
Everything looks fine here.

# /usr/lib/nagios/plugins/check_tcp -V
check_tcp v2.1.1 (monitoring-plugins 2.1.1)
# /usr/lib/nagios/plugins/check_tcp -H heise.de -p 443 -S -D 1000,2000
CRITICAL - Certificate 'heise.de' expires in 185 day(s) (Fr 16 Okt 2015 00:59:00 CEST).

Are you using a distribution package? If so, which one?

**Comment by nuts424** [comment]
server # /usr/lib/nagios/plugins/check_tcp -V
check_tcp v2.1.1 (monitoring-plugins 2.1.1)

crazy...
It is a gentoo.
My profile is default/linux/amd64/13.0

**Comment by waja** [comment]
And you did install it via emerge?

**Comment by nuts424** [comment]
Ah, there is the failure.
my useflags were: 

net-analyzer/monitoring-plugins sudo snmp gnutls

with gnutls check_tcp -D doesn't work. Thanks! A "its working for me" is in some cases a good constructive answer.
