### ISSUE TITLE
check_http - support TLS v1.2

### ISSUE THREAD

**Issue by druchoo** [monitoring-plugins/monitoring-plugins#1338]
Please add TLS v1.2 to check_http. Currently only v1 is supported?

```
 -S, --ssl=VERSION
    Connect via SSL. Port defaults to 443. VERSION is optional, and prevents
    auto-negotiation (1 = TLSv1, 2 = SSLv2, 3 = SSLv3).
```

**Comment by jasonwilk** [comment]
Some QSAs are starting to vail PCI scans when TLSv1 is enabled. They've already disallowed SSLv2 and SSLv3. That means that there are no checks that would be available via SSL with this command unless it's extended to support TLSv1.1 and TLSv1.2. This needs to be updated for this plugin to be useful in any environment that has PCI implications.

**Comment by seccentral** [comment]
Yes this is still a problem. and now most https checks are useless. 
When can we expect an update ?

**Comment by waja** [comment]
Just to complete this thread, there is a reply on our development mailing list (https://www.monitoring-plugins.org/archive/devel/2015-August/010055.html):

"It should still connect when you use auto-negotiation."

**Comment by seccentral** [comment]
Don't know about their/his/her setup but i've tried and by default it's auto (right ? manual sais so anyway) 
" -S, --ssl=VERSION
    Connect via SSL. Port defaults to 443. VERSION is optional, and prevents
    auto-negotiation (1 = TLSv1, 2 = SSLv2, 3 = SSLv3)."
so even if i use -S --ssl=1 it still fails. albeit with a different error: (with --ssl=1)
CRITICAL - Cannot make SSL connection.
140318164997776:error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error:s3_pkt.c:1294:SSL alert number 80

**Comment by seccentral** [comment]
Big update on this and solution *nohack* 
So how do you check a host with SNI ? like this :
openssl s_client -connect www.example.com:443 -servername www.example.com 
works perfectly. And this made me think.

now back to the icinga1/2/nagios/etc check_http execution.
this is the correct way to use the command to check a webhost with sni 
check_http -H www.example.com -S --sni 
HTTP OK: HTTP/1.1 200 OK - 13667 bytes in 1.031 second response time |time=1.031097s;;;0.000000 size=13667B;;;0
Now, -H stands for vhost but i guess in the context of sni it's somewhat the same thing tho the documentation should be updated.

Here is a host object definition for such a check 
sequence from hosts.conf 
====
[...]
object Host www.example.com { 
 address www.example.com 
 vars.http_vhost = "www.example.com"
 vars.http_sni = "true"
 vars.server_type = "Web Servers" 
 vars[...] # any other required on-setup vars 
}
[...]

and the check is simple . 
sequence from a customservicechecks.conf *justanexamplename*
====
[...]
apply Service "https" {
        import "generic-service"
        check_command = "http"
        vars.http_ssl = "true"
       assign where host.vars.server_type == "Web Servers" 
}
[...]

Now i don't know about nagios 1/2/3/4, this is icinga2 syntax but this should be adaptable to nagios configs. 

Yay and big thanks to Mr. Rob Stradling at openssl who (although unrelated to nagios/icinga) gave me a very important hint. 
Rock on \m/

**Comment by gsemia** [comment]
PCI demanded from my company to disable internal TLSv1 Access to our Servers immediately. Only Public TLSv1 Access is still allowed until 2015-06-31. This means Monitoring is also affected and needs to have TLSv1 disabled. Having check_http not support TLSv1.2 breaks our Nagios monitoring.

**Comment by waja** [comment]
@gsemia did try to just use "-S" without specifying the the version and using auto-negotiation as suggested by Stuart at https://www.monitoring-plugins.org/archive/devel/2015-August/010055.html?

**Comment by waja** [comment]
Stuart Henderson wrote at https://www.monitoring-plugins.org/archive/devel/2015-September/010076.html:

You could do something like this which changes the default check to
TLSv1.0+ (I think at this point in the game it's reasonable to consider
a service which doesn't TLS at all as down/broken ;-) and adds a new
option to enforce TLSv1.2+ (allowing it to autodetect and connect to
future protocol versions).

[check_http_support_TLS_v1.2.patch.txt](https://github.com/monitoring-plugins/monitoring-plugins/files/2220/check_http_support_TLS_v1.2.patch.txt)

**Comment by keith4** [comment]
This is much more thorough than my patch. I wish I had found this first ;-)

**Comment by waja** [comment]
@sthen I created #1359 with your proposed changes, feel free to adjust if needed.
