### ISSUE TITLE
 check_http: Fix for checking http on different virtual port

### ISSUE THREAD

**Issue by odenbach** [monitoring-plugins/monitoring-plugins#1348]
Hi,

a few days ago I added a comment to issue #1026 which was marked as closed but is not. Please have a look. If you want me to recreate the patch I will give it a try.

Thanks,

Christopher

**Comment by waja** [comment]
I reopened both issues, so closing this one

**Comment by waja** [comment]
Anyways ... recreating/rebasing would help for the sprint (https://www.monitoring-plugins.org/news/bug-squashing-fall-2015.html), as we maybe can integrate it with less work.

**Comment by odenbach** [comment]
closing, as issue #1352 contains the patch against master.
