### ISSUE TITLE
check_http: Odd bug with SSL check.

### ISSUE THREAD

**Issue by benpro** [monitoring-plugins/monitoring-plugins#1358]
```
$ /usr/lib/nagios/plugins/check_http -V      
check_http v2.1.1 (monitoring-plugins 2.1.1) 
```

If we check an Apache 2.2 server under Debian Wheezy, all is OK.

```
$ /usr/lib/nagios/plugins/check_http -S -H $MYDOMAIN
HTTP OK: HTTP/1.1 200 OK - 2481 bytes in 0.582 second response time |time=0.582011s;;;0.000000 size=2481B;;;0
```

If we check an Apache 2.4 server under Debian Jessie, there is an odd bug.

```
$ /usr/lib/nagios/plugins/check_http -S -H $MYDOMAIN                                      
HTTP OK: HTTP/1.1 200 OK - 2392 bytes in 7.530 second response time |time=7.529691s;;;0.000000 size=2392B;;;0 
$ /usr/bin/time curl https://$MYDOMAIN -k -o /dev/null -s       
0.00user 0.00system 0:00.28elapsed 2%CPU (0avgtext+0avgdata 8828maxresident)k
```

Why it took 7+s where curl took 0.28s?

The fact is check_http doesn't seems to speak the same HTTPS as curl. I traced Apache to see more informations.

```
14:57:42 accept4(6, {sa_family=AF_INET6, sin6_port=htons(53216), inet_pton(AF_INET6, "::ffff:88.179.18.233", &sin6_addr), sin6_flowinfo
=0, sin6_scope_id=0}, [28], SOCK_CLOEXEC) = 29
14:57:42 read(29, 0x7f7ddd36b048, 8000) = -1 EAGAIN (Resource temporarily unavailable)
14:57:42 poll([{fd=29, events=POLLIN}], 1, 7000) = 0 (Timeout)
14:57:49 close(29)                      = 0
```

It took 7+s, because my Apache server has a Timeout of 7s. Apache seems to wait something from check_http, before timeout occurs. (You can set Apache timeout to 30s, check_http will take 30+s).

And here comes the really odd part.

```
$ /usr/lib/nagios/plugins/check_http -S -H $MYDOMAIN -N                                 
HTTP OK: HTTP/1.1 200 OK - 256 bytes in 0.555 second response time |time=0.554783s;;;0.000000 size=256B;;;0 
```

With -N, all is OK.

Any ideas? I opened the issue here because I have only this odd bug with check_http, not with curl, wget, browsers…
It may be related to Apache, but that's quite odd.

**Comment by waja** [comment]
$ cat /etc/debian_version
8.2
$ /usr/lib/nagios/plugins/check_http -V
check_http v2.1.1 (monitoring-plugins 2.1.1)
$ /usr/lib/nagios/plugins/check_http -S -H www.monitoring-plugins.org
HTTP OK: HTTP/1.1 200 OK - 5528 bytes in 0.125 second response time |time=0.125402s;;;0.000000 size=5528B;;;0
$ /usr/bin/time curl https://www.monitoring-plugins.org -k -o /dev/null -s
0.01user 0.00system 0:00.14elapsed 16%CPU (0avgtext+0avgdata 4140maxresident)k
0inputs+0outputs (0major+1174minor)pagefaults 0swaps

I cant see any problem here. I tested check_http against several apache (2.2,2.4) and nginx on wheezy and jessie. It looks like it's related to you apache2 installation/configuration.

With my Debian monitoring-plugins maintainer hat on, Jan.

**Comment by tinuzz** [comment]
I came here, researching a similar or the same problem. All HTTPS checks on a specific server (Apache 2.4, Debian 8.2) get a timeout with check_http. As benpro notes, with '-N', it works fine. HTTP checks work fine too.

Somehow, neither end closes the connection after the request. Check_http just keeps trying to read from the socket and Apache doesn't send anything anymore. Disabling keepalive did not make a difference. If I force-close the connection by stopping Apache, the check result is HTTP OK: HTTP/1.1 200 OK.

**Comment by tinuzz** [comment]
I have traced the problem back to the use of mpm_itk. If I disable the mpm_itk module, the HTTPS check works as expected.

**Comment by tinuzz** [comment]
The bug is in mpm-itk. It is reported here:
http://lists.err.no/pipermail/mpm-itk/2015-September/000914.html
and a fix is available later in that thread.

**Comment by sni** [comment]
Closing this issue since there is a fix for apache available.
