### ISSUE TITLE
lint .py and .pl scripts

### ISSUE THREAD

**Issue by glensc** [monitoring-plugins/monitoring-plugins#1365]
to avoid [such](https://github.com/nagios-plugins/nagios-plugins/pull/110) [mistakes](https://github.com/monitoring-plugins/monitoring-plugins/pull/1361) like distributing scripts with syntax error, imho would be good if travis syntax lints the scripts. `perl -c script.pl`, `python -m py_compile script.py`

**Comment by sni** [comment]
We do this since yesterday already :-)
https://github.com/monitoring-plugins/monitoring-plugins/commit/c0b4f418993ee2ad9fc96acafdddd98ac1bc5074
At least for perl scripts. I am not aware of any python scripts.

**Comment by glensc** [comment]
it can be done for python as well.

**Comment by glensc** [comment]
oh. no `.py` indeed. where did i see `.py` then? :)

**Comment by waja** [comment]
The idea behind of implementing it soon was, if we delay it, it will never happen. :-)

**Comment by glensc** [comment]
otoh, if all plugins are tested for functionality, the syntax check is not needed ;)

**Comment by waja** [comment]
this syntax check is good for having an indicator for people creating RPs, for exampel
