### ISSUE TITLE
check_dig: expected address is not an exact match

### ISSUE THREAD

**Issue by riskersen** [monitoring-plugins/monitoring-plugins#1385]
Expected address is not fully matched for example

Assume i have a host which has the IP 173.194.116.215 and i want to check against it:
`´./check_dig -H dns1 -vvvv -l www.google.de -a 173.194.116.215``

As expected check_dig returns OK, but if its checked for .21:
`´./check_dig -H dns1 -vvvv -l www.google.de -a 173.194.116.21``

It returns also OK, because strstr/strcasestr just locate substrings but it might return a WARNING/CRITICAL because it matches not 100%

To not break working setups we could add a new option -e --exact-match which toggles strict checking and then returns WARN/CRIT if the result and the expected result do not match 100%

**Comment by sni** [comment]
I'd say this is a bug and there is no need for an extra option. The only valid use case would be subnet
matching, ex.: to check if a given name returns an ip from a given subnet and then substring matching
would be wrong either.

**Comment by weiss** [comment]
> I'd say this is a bug and there is no need for an extra option.

+1

**Comment by ekohl** [comment]
Given the PR was merged, shouldn't this be closed?

**Comment by RincewindsHat** [comment]
It should I guess
