### ISSUE TITLE
check_http not following redirects containing angle brackets

### ISSUE THREAD

**Issue by 2bjc466** [monitoring-plugins/monitoring-plugins#1389]
Hello,

I am having trouble getting check_http to follow redirects that contain angle brackets. A web site is issuing a 302 and a URL containing 'proxycustom=<HOME/>' and check_http is attempting to use 'proxycustom=' to follow the redirect. Here's partial verbose output from the command I am using:

./check_http --critical=20 --hostname=google-search-appliance --port=80 --string='<title>Search Home</title>' --url=/ --warning=10 --onredirect=follow -v
GET / HTTP/1.1
User-Agent: check_http/v2.1.2 (monitoring-plugins 2.1.2)
Connection: close
Host: google-search-appliance

http://google-search-appliance:80/ is 293 characters
STATUS: HTTP/1.1 302 Found
***\* HEADER ****
Date: Wed, 28 Oct 2015 18:23:07 GMT
Server: Google Search Appliance
Location: /search?site=default_collection&client=default_frontend&output=xml_no_dtd&proxystylesheet=default_frontend&proxycustom=<HOME/>
Content-Type: text/html
Content-Length: 0
Connection: close
***\* CONTENT ****

Redirection to http://google-search-appliance:80/search?site=default_collection&client=default_frontend&output=xml_no_dtd&proxystylesheet=default_frontend&proxycustom=
GET /search?site=default_collection&client=default_frontend&output=xml_no_dtd&proxystylesheet=default_frontend&proxycustom= HTTP/1.1
User-Agent: check_http/v2.1.2 (monitoring-plugins 2.1.2)
Connection: close
Host: google-search-appliance

http://google-search-appliance:80/search?site=default_collection&client=default_frontend&output=xml_no_dtd&proxystylesheet=default_frontend&proxycustom= is 19793 characters
STATUS: HTTP/1.1 200 OK
***\* HEADER ****

Let me know if I can provide any additional information. Thanks!

**Comment by 2bjc466** [comment]
I think the original post ate the angle brackets. Unmangled plugin output can be found here:

http://quotes.colorado.edu/~jesse/check_http.txt

**Comment by RincewindsHat** [comment]
I am sorry for this being really late. Also I am sorry, be cause the link is down and I am going to close this until the problem resurfaces.
