### ISSUE TITLE
check_rpc: Not working on Debian Wheezy

### ISSUE THREAD

**Issue by RSpiertz** [monitoring-plugins/monitoring-plugins#1393]
The check_rpc plugin is no longer working on Debian Wheezy, the package version is 2.1.1-1~bpo70+1. It assumes rpcinfo is in /usr/sbin while it is in /usr/bin, thus it throws the error 'Can't fork for rpcinfo: No such file or directory'.

**Comment by RincewindsHat** [comment]
This would be a problem of the distribution. Also (sadly) nothing happened here for the last six years, so I am closing this.
