### ISSUE TITLE
check_ping and IPv4 / IPv6 address selection 

### ISSUE THREAD

**Issue by jenslink** [monitoring-plugins/monitoring-plugins#1397]
When  using check_ping to check a dual-stacked website (e.g. www.heise.de) from a host that has IPv6 enabled but no global IPv6 address check_ping will fail (Network unreachable).

Please consider implementing RFC 6724 (Default Address Selection for Internet Protocol Version 6 (IPv6)) for check_ping.

**Comment by weiss** [comment]
Does `ping www.heise.de` from the same host work?  Does `check_ping -4 -H www.heise.de -w '200,20%' -c '500,50%'` solve the problem?

Either way, you might want to use `check_icmp` (which currently doesn't support ICMPv6) to work around the issue (and because it's preferable for v4 checks anyway).

**Comment by jenslink** [comment]
Holger Weiß <notifications@github.com> writes:

> Does ping www.heise.de from the same host work? Does check_ping -4 -H
> www.heise.de -w '200,20%' -c '500,50%' solve the problem?

Sure ping works.  One has to use ping6 on Linux to ping via ICMPv6. And
check_ping -4 also works as expected.

> Either way, you might want to use check_icmp (which currently doesn't
> support ICMPv6) to work around the issue (and because it's preferable
> for v4 checks anyway).

I know. I also reported that problem. ;-) 

Jens
-- 
----------------------------------------------------------------------------
| Foelderichstr. 40   | 13595 Berlin, Germany           | +49-151-18721264 |
| http://blog.quux.de | jabber: jenslink@quux.de        | ---------------  | 
----------------------------------------------------------------------------

**Comment by weiss** [comment]
> One has to use ping6 on Linux to ping via ICMPv6.

Only if you're using a _very_ (i.e., more than a [few weeks][1]) old iputils version!

I just need some sleep, sorry :-)

[1]: https://github.com/iputils/iputils/commit/25aaaf4c58b485a5d9ec758a1f170cc5ec4073c4

**Comment by RincewindsHat** [comment]
Can not reproduce anymore, I guess this is fixed.
