### ISSUE TITLE
check_imap doesn't support STARTTLS

### ISSUE THREAD

**Issue by peikk0** [monitoring-plugins/monitoring-plugins#1400]
IMAPS is deprecated nowadays, STARTTLS is widely used instead, and check_imap doesn't support it.

**Comment by peikk0** [comment]
Same goes with check_pop and check_jabber, as they are all symlinked to check_tcp.

**Comment by RincewindsHat** [comment]
Kind of a duplicate of #1282 . Closing this to reduce the clutter
