### ISSUE TITLE
check_mailq.pl has a typo

### ISSUE THREAD

**Issue by elpito** [monitoring-plugins/monitoring-plugins#1403]
Line 37 has a missing ';'.

The patch which fixes this:
```
--- plugins-scripts/check_mailq.pl.orig	2016-02-15 07:23:29.024865990 +0100
+++ plugins-scripts/check_mailq.pl	2016-02-15 07:23:40.310866192 +0100
@@ -35,7 +35,7 @@
 use lib "$FindBin::Bin";
 use utils qw(%ERRORS &print_revision &support &usage );

-my ($sudo)
+my ($sudo);

 sub print_help ();
 sub print_usage ();
```

**Comment by glensc** [comment]
you lack version information!
and as  this particular bug never existed in monitoring-plugins
so likely you also confused the repository, monitoring-plugins has this bug.

**Comment by glensc** [comment]
https://github.com/nagios-plugins/nagios-plugins/pull/110
https://github.com/nagios-plugins/nagios-plugins/commit/842384a9097f30265637040d7f719f619a310118

**Comment by waja** [comment]
As pointed out by @glensc, monitoring-plugins is not affected by this. We introduced a not affected version of this by https://github.com/monitoring-plugins/monitoring-plugins/commit/8235fd0aef2945e0d638fba3493134588d085d5a
