### ISSUE TITLE
add centreon.

### ISSUE THREAD

**Issue by crazy-canux** [monitoring-plugins/monitoring-plugins#1429]
maintain a bundle of more than fifty standard plugins for Icinga, Naemon, Nagios, Shinken, Sensu, Centreon, Opsview.

https://www.centreon.com

https://www.opsview.com/

**Comment by waja** [comment]
what are you trying to tell us?

**Comment by crazy-canux** [comment]
extend the doc, let more user know what this plugin can be used.

Centreon and Opsview can use this plugin.
