### ISSUE TITLE
check_disk --all appears to be broken

### ISSUE THREAD

**Issue by BackSeat** [monitoring-plugins/monitoring-plugins#1432]
`check_disk 2.1.2`

Running check_disk without `--all` reports three issues on this sever (I've stripped out performance data):

```
$ plugins/check_disk -e -l  -w 20% -c 10% 
DISK WARNING - free space: /export/scratch 73715 MB (19% inode=99%); /scratch/local 73715 MB (19% inode=99%); /local 73715 MB (19% inode=99%);
```

Adding `--all` to the above REMOVES `/export/scratch` from the list:

```
$ plugins/check_disk -e -l  -w 20% -c 10% --all
DISK WARNING - free space: /local 73715 MB (19% inode=99%); /scratch/local 73715 MB (19% inode=99%);
```

This is counter-intuitive. Have I misunderstood what `--all` does?

Thanks,
Keith

**Comment by sni** [comment]
Thats kinda strange, --all does exactly like the help page says and is equivalent to -R '.*'. Can you try -R '.*'.
Is there anything special about /export/scratch?
