### ISSUE TITLE
check_disk fails as non-root since debian security update

### ISSUE THREAD

**Issue by grindhold** [monitoring-plugins/monitoring-plugins#1434]
When i am trying to execute check_disk (version 2.1.2) in debian stretch, it will always end critical with
```
DISK CRITICAL - /sys/kernel/debug/tracing is not accessible: Permission denied
```
This is due to the fact that the folder permissions of ```/sys/kernel/debug``` have been changed from ```0644``` to ```0600``` recently.

Since the distributors restrict it like that, i assume it's counterproductive to circumvent the issue by setting the permissions back.
I'd prefer to run my checks as non-root.

**Comment by waja** [comment]
With my Debian maintainers hat on, I would recommend to try to use of ```-x, --exclude_device=PATH <STRING>```.
