### ISSUE TITLE
check_mysql performance label length exceeds 19 characters

### ISSUE THREAD

**Issue by infotek** [monitoring-plugins/monitoring-plugins#1439]
check_mysql performance label 'Qcache_queries_in_cache' and 'Qcache_lowmem_prunes' have lengths that exceed the 19 characters

> label length is arbitrary, but ideally the first 19 characters are unique (due to a limitation in RRD). Be aware of a limitation in the amount of data that NRPE returns to Nagios

https://nagios-plugins.org/doc/guidelines.html

**Comment by infotek** [comment]
This could be solved by using CamelCase to forgo the underscores. With the addition of abbreviating "in" to "N"... 19 characters met!  Are there any issues that this would cause?

**Comment by riskersen** [comment]
Could it break existing performance values?
From my perspective, we might add the fix perf label, but also keep the old
one to maintain backwards compatibility.

Am 16.11.2016 6:08 PM schrieb "Jason Ellison" <notifications@github.com>:

**Comment by infotek** [comment]
That is completely dependent on how your software handles the perf data... what software are you using that deals with the perf data output from check_* plugins?

**Comment by RincewindsHat** [comment]
`label length is arbitrary`. I don't see any special reason the limit the length in general.
Closing this, for the purpose of tidying up a little bit. Please reopen, if I misunderstood the problem

**Comment by infotek** [comment]
the issue is one with rrdtool seen here:
https://github.com/oetiker/rrdtool-1.x/issues/713

it was patched here: 
https://github.com/librenms/librenms/issues/4729

**Comment by RincewindsHat** [comment]
To get this right: Does rrdtool reject values wie a label longer thant 19 characters?

**Comment by RincewindsHat** [comment]
Ah, I misunderstood that. I would propose an output option to restrict label length. But I am not sure, if and when I find the time to actually do something about it.

**Comment by infotek** [comment]
i believe i fixed it here:
https://github.com/librenms/librenms/issues/4729

**Comment by RincewindsHat** [comment]
I saw that link, but seems to be a fix for LibreNMS in regard to this, not for the Plugins. As a workaround your monitoring system might be able to cut the labels short on itself.
But that would be a question for Icinga, LibreNMS, Zabbix or whatever you are using.

**Comment by infotek** [comment]
I'm sorry, had a busy day. You are correct. It could be solved at the check_mysql plugin level, but all "stake holders" would probably need to be consulted (Nagios, Icinga, LibreNMS, Zabbix, etc...).

**Comment by RincewindsHat** [comment]
ok, this has been some time and I reread this story again.
I don't have time to implement stuff like that and, to be honest, no motivation. setting an length limit to labels could probably implemented with limited effort via #1979 if it ever gets merged and will be used.
Apart from that, I do consider this a problem of RRD or the monitoring systems, not ours.
