### ISSUE TITLE
check_cluster - How To?

### ISSUE THREAD

**Issue by gvenka008c** [monitoring-plugins/monitoring-plugins#1453]
I configured the check_cluster to monitor the host states as show below. When I bring down one of the node, it is still showing OK status. Please suggest.

commands.conf

```
object CheckCommand "check_cluster" {
  import "plugin-check-command"

  command = [ "/usr/lib64/nagios/plugins/check_cluster" ]

  arguments = {
    "-l" = "$check_cluster_label$"
    "-w" = "$check_cluster_warning$"
    "-c" = "$check_cluster_critical$"
    "-d" = "$check_cluster_data$"
  }
}
```

services.conf

```
object Service "my-cluster-check" {
  host_name = NodeName
  check_command = "check_cluster"
  vars.check_cluster_label = "PING"
  vars.check_cluster_warning = 1
  vars.check_cluster_critical = 2
  vars.check_cluster_data = {{ get_service("host1.net", "PING").state_id + ", " + get_service("host2.net", "PING").state_id }}
}
```

**Comment by waja** [comment]
Are you sure you are using monitoring plugins? Your path seems to indicate it isn't.

What is the plugin output when you call it on the command line and what is the return code? Please tell us also the plugin version!

**Comment by gvenka008c** [comment]
@waja Here is the info

```
[root@6a7a7ffeeb31 /]# /usr/lib64/nagios/plugins/check_cluster --help
check_cluster v2.0.3 (nagios-plugins 2.0.3)
Copyright (c) 2000-2004 Ethan Galstad (nagios@nagios.org)
Copyright (c) 2000-2014 Nagios Plugin Development Team
	<devel@nagios-plugins.org>

Host/Service Cluster Plugin for Nagios 2

Usage:
 check_cluster (-s | -h) -d val1[,val2,...,valn] [-l label]
[-w threshold] [-c threshold] [-v] [--help]

```

**Comment by waja** [comment]
@gvenka008c This is the plugin from nagios-plugins (https://github.com/nagios-plugins/nagios-plugins/issues/202). Anyway ... please try to check your stuff on command line. It look like you have a problem in Icinga and NOT with the plugins.

**Comment by gvenka008c** [comment]
@waja Do you have any example for checking host status from command line using check_cluster?

**Comment by tobiasvdk** [comment]
Examples:

```
$ /usr/lib/nagios/plugins/check_cluster -w 1 -c 2 -d 0,0,0
CLUSTER OK: Service cluster: 3 ok, 0 warning, 0 unknown, 0 critical
```

```
$ /usr/lib/nagios/plugins/check_cluster -w 1 -c 2 -d 1,0,0
CLUSTER OK: Service cluster: 2 ok, 1 warning, 0 unknown, 0 critical
```

```
$ /usr/lib/nagios/plugins/check_cluster -w 1 -c 2 -d 1,1,0
CLUSTER WARNING: Service cluster: 1 ok, 2 warning, 0 unknown, 0 critical
```

```
$ /usr/lib/nagios/plugins/check_cluster -w 1 -c 2 -d 1,1,1
CLUSTER CRITICAL: Service cluster: 0 ok, 3 warning, 0 unknown, 0 critical
```

**Comment by gvenka008c** [comment]
@tobiasvdk How do we get the -d dynamically? I tried the below code in services.conf but not getting the desired result.

```
object Service "my-cluster-check" {
  host_name = NodeName
  check_command = "check_cluster"
  vars.check_cluster_label = "PING"
  vars.check_cluster_warning = 1
  vars.check_cluster_critical = 2
  vars.check_cluster_data = {{ get_service("host1.net", "PING").state_id + ", " + get_service("host2.net", "PING").state_id }}
}
```

 -d, --data=LIST
    The status codes of the hosts or services in the cluster, separated by
    commas

**Comment by waja** [comment]
Dear @gvenka008c,

while I understand your problem, this is not a support forum (of icinga or any other software), this is an ISSUE tracker of monitoring-plugins.

There are so many tools depending on our plugins, we can't know all of them.

Did you discover, that every plugin has a help output?

**Comment by gvenka008c** [comment]
@waja Yes, agreed. Unfortunately the plugin --help doesn't have much examples. This is the only one available.

```
Examples:
 check_cluster -s -d 2,0,2,0 -c @3:
    Will alert critical if there are 3 or more service data points in a non-OK
    state.
```

**Comment by gvenka008c** [comment]
@tobiasvdk @waja 

I was trying to get the state of the host as shown below

```
 vars.check_cluster_data = get_host("host1").state + ", " + get_host("host2").state

```

Both are returning value as 1

```
Check Cluster Data	1, 1

```

Any thoughts? Both the nodes are up and running. Is that the right way of getting the host state? Please suggest.

**Comment by dnsmichi** [comment]
Putting it here as well. I don't have an idea if such a thing should be included inside the Icinga 2 documentation, especially for naming conventions "cluster" won't fix (already reserved object name).

Defining `check_cluster_data` is the simple approach. If you prefer to just pass an array of object names, some more Icinga 2 DSL coding must be involved. 

Btw - check_cluster requires you to set `--host` and `--service` as well. So you'll need that inside your CheckCommand definition and then your Host or Service object.

Could look like this basically:

````
object CheckCommand "check_cluster" {
        import "plugin-check-command"

        command = [ PluginDir + "/check_cluster" ]

        arguments = {
                "--host" = {
                        set_if = "$check_cluster_host$"
                        description = "Check host cluster status"
                }
                "--service" = {
                        set_if = "$check_cluster_service$"
                        description = "Check service cluster status"
                }
                "--label" = {
                        value = "$check_cluster_label$"
                        description = "Optional prepended text output (i.e. \"Host cluster\")"
                }
                "--warning" = {
                        value = "$check_cluster_warning$"
                        description = "Specifies the range of hosts or services in cluster that must be in a non-OK state in order to return a WARNING status level"
                }
                "--critical" = {
                        value = "$check_cluster_critical$"
                        description = "Specifies the range of hosts or services in cluster that must be in a non-OK state in order to return a CRITICAL status level"
                }
                "--data" = {
                        value = "$check_cluster_data$"
                        description = "The status codes of the hosts or services in the cluster, separated by commas"
                }
        }
}
````

If you want to go deeper, enhance the CheckCommand e.g. by this logic at the end:

````
        //this hides the logic from the caller
        //define an array of full host/service object names in vars.check_cluster_objects
        //and set vars.check_cluster_service or vars.check_cluster_host accordingly
        vars.check_cluster_data = {{
                var cluster_objects = macro("$check_cluster_objects$")

                //type safety
                if (typeof(cluster_objects) != String && typeof(cluster_objects) != Array) {
                        return ""
                }

                var states = []

                for (obj in cluster_objects) {
                        if (macro("$check_cluster_service$")) {
                                states.add(get_object(Service, obj).state)
                        } else if (macro("$check_cluster_host$")) {
                                states.add(get_object(Host, obj).state)
                        } else {
                                return ""
                        }
                }

                return states.join(",")
        }}
````

Using a simple configuration for testing then defining two hosts and a ping4 service apply rule with some defined dummy states.

````
object Host "cluster-01" {
        check_command = "dummy"
        vars.dummy_state = 2
}

object Host "cluster-02" {
        check_command = "dummy"
        vars.dummy_state = 1
}

apply Service "ping4" {
        check_command = "dummy"

        if (match("*01", host.name)) {
                vars.dummy_state = 2
        } else {
                vars.dummy_state = 1//modify me
        }

        assign where match("cluster*", host.name)
}
````

In addition to that a cluster host and service which actually passes the cluster data to check_cluster then.

````
object Host "cluster-host" {
        check_command = "check_cluster"

        vars.check_cluster_host = true
        vars.check_cluster_label = "HOST"
        vars.check_cluster_warning = 1
        vars.check_cluster_critical = 2

        vars.check_cluster_objects = [ "cluster-01", "cluster-02" ]
}

apply Service "cluster-ping" {
        check_command = "check_cluster"

        vars.check_cluster_service = true
        vars.check_cluster_label = "PING"
        vars.check_cluster_warning = 1
        vars.check_cluster_critical = 2

        //the logic is hidden inside the CheckCommand in vars.check_cluster_data
        //vars.check_cluster_objects = [ "cluster-01!ping4", "cluster-02!ping4" ]

        //or the simple approach with manually setting vars.check_cluster_data
        vars.check_cluster_data = {{
                get_object(Service, "cluster-01!ping4").state + "," + get_object(Service, "cluster-02!ping4").state
        }}

        assign where host.name == "cluster-host"
}
````

Looks like this in Icinga Web 2 then:

Host check combining check_cluster:

<img width="692" alt="icingaweb2_check_cluster_host_check" src="https://cloud.githubusercontent.com/assets/382049/20939068/b04dc4e2-bbed-11e6-8ecd-fd921c9da0fe.png">


2 Services

<img width="268" alt="icingaweb2_check_cluster_service_check_cluster01" src="https://cloud.githubusercontent.com/assets/382049/20939061/a8b2ed16-bbed-11e6-95bb-cf3e3b8610f9.png">
<img width="274" alt="icingaweb2_check_cluster_service_check_cluster02" src="https://cloud.githubusercontent.com/assets/382049/20939062/a8b33000-bbed-11e6-9168-8d0f89c947d5.png">


check_cluster Service

<img width="589" alt="icingaweb2_check_cluster_service_check_overall" src="https://cloud.githubusercontent.com/assets/382049/20939049/9e4aafb2-bbed-11e6-971a-ca6ff98edf0c.png">


Although check_cluster might be reasonable to call, I'd just go for [writing functions](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/advanced-topics#access-object-attributes-at-runtime) and evaluating the state over there. We'll probably find a way to prevent the call to check_dummy at some point, for now it is up to you to choose ;-)

**Comment by gvenka008c** [comment]
@dnsmichi Thanks a lot Mike for the wonderful write up. I updated commands.conf to have the "check_cluster" look similar to what you have provided.

In the services.conf, I made the changes as suggested by you

```

 object Host "statging-cluster" {
  check_command = "check_cluster"

  vars.check_cluster_host = true
  vars.check_cluster_label = "HOST"
  vars.check_cluster_warning = 1
  vars.check_cluster_critical = 2

  vars.check_cluster_data = {{ get_object(Host, "host1.net!ping4").state + "," + get_object(Host, "host2.net!ping4").state }}

}

```

But it shows there are no hosts up. 

```
Plugin Output
CLUSTER OK: HOST: 0 up, 0 down, 0 unreachable

```

Thoughts?

**Comment by gvenka008c** [comment]
@dnsmichi Mike, thanks for the great write up. I was able to have the service part working.

Below doesn't show any Hosts

```
object Host "staging-cluster" {
  check_command = "check_cluster"

  vars.check_cluster_host = true
  vars.check_cluster_label = "HOST"
  vars.check_cluster_warning = 1
  vars.check_cluster_critical = 2

  vars.check_cluster_data = {{
       get_object(Host, "host1.net!ping4").state + "," + get_object(Host, "host2.net!ping4").state
  }}
}
```

```
Plugin Output
CLUSTER OK: HOST: 0 up, 0 down, 0 unreachable
```

**Comment by waja** [comment]
@gvenka008c as this has nothing todo with anything of check_cluster (it works as expected) and this is an issue tracker of the monitoring-plugins project I'll close this thread.

**Comment by gvenka008c** [comment]
@dnsmichi Please see the snapshot. For some reason Host ping is not showing up as expected.

```
  vars.check_cluster_data = {{
       get_object(Host, "host1.net!ping").state + "," + get_object(Host, "host2.netpPing").state
  }}
}

```

<img width="1245" alt="screen shot 2016-12-06 at 4 46 48 pm" src="https://cloud.githubusercontent.com/assets/13439779/20945049/abbed53e-bbd3-11e6-8a81-bf5b1a6c4ea4.png">

**Comment by dnsmichi** [comment]
"host1.net!ping4" is not a host object ...
