### ISSUE TITLE
check_http - Memory allocation error

### ISSUE THREAD

**Issue by Jazb** [monitoring-plugins/monitoring-plugins#1464]
I am receiving the next error in a particular case when the vhost has the string "1000..." on the version 2.4.1 .

 *** Error in `/usr/lib64/nagios/plugins/check_http': malloc(): memory corruption (fast): 0x00002b971a2bf4e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7ada4)[0x2b971b5ffda4]
/lib64/libc.so.6(+0x7ddc7)[0x2b971b602dc7]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x2b971b604fbc]
/lib64/libc.so.6(__vasprintf_chk+0x120)[0x2b971b693a80]
/usr/lib64/nagios/plugins/check_http(+0x93b4)[0x2b971a29a3b4]
/usr/lib64/nagios/plugins/check_http(+0x9484)[0x2b971a29a484]
/usr/lib64/nagios/plugins/check_http(+0x9887)[0x2b971a29a887]
/usr/lib64/nagios/plugins/check_http(+0x534f)[0x2b971a29634f]
/usr/lib64/nagios/plugins/check_http(+0x3714)[0x2b971a294714]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b971b5a6b35]
/usr/lib64/nagios/plugins/check_http(+0x37b2)[0x2b971a2947b2]
======= Memory map: ========
2b971a291000-2b971a2a8000 r-xp 00000000 fd:00 500343                     /usr/lib64/nagios/plugins/check_http
2b971a2a8000-2b971a2aa000 rw-p 00000000 00:00 0
2b971a2b4000-2b971a3bd000 rw-p 00000000 00:00 0
2b971a4a7000-2b971a4a8000 r--p 00016000 fd:00 500343                     /usr/lib64/nagios/plugins/check_http
2b971a4a8000-2b971a4ab000 rw-p 00017000 fd:00 500343                     /usr/lib64/nagios/plugins/check_http
2b971a4ab000-2b971a4b8000 rw-p 00000000 00:00 0
2b971a4b8000-2b971a4d8000 r-xp 00000000 fd:00 134795011                  /usr/lib64/ld-2.17.so
2b971a6d7000-2b971a6d8000 r--p 0001f000 fd:00 134795011                  /usr/lib64/ld-2.17.so
2b971a6d8000-2b971a6d9000 rw-p 00020000 fd:00 134795011                  /usr/lib64/ld-2.17.so
2b971a6d9000-2b971a6da000 rw-p 00000000 00:00 0
2b971a6da000-2b971a6f0000 r-xp 00000000 fd:00 138205195                  /usr/lib64/libnsl-2.17.so
2b971a6f0000-2b971a8ef000 ---p 00016000 fd:00 138205195                  /usr/lib64/libnsl-2.17.so
2b971a8ef000-2b971a8f0000 r--p 00015000 fd:00 138205195                  /usr/lib64/libnsl-2.17.so
2b971a8f0000-2b971a8f1000 rw-p 00016000 fd:00 138205195                  /usr/lib64/libnsl-2.17.so
2b971a8f1000-2b971a8f3000 rw-p 00000000 00:00 0
2b971a8f3000-2b971a909000 r-xp 00000000 fd:00 138205202                  /usr/lib64/libresolv-2.17.so
2b971a909000-2b971ab09000 ---p 00016000 fd:00 138205202                  /usr/lib64/libresolv-2.17.so
2b971ab09000-2b971ab0a000 r--p 00016000 fd:00 138205202                  /usr/lib64/libresolv-2.17.so
2b971ab0a000-2b971ab0b000 rw-p 00017000 fd:00 138205202                  /usr/lib64/libresolv-2.17.so
2b971ab0b000-2b971ab0d000 rw-p 00000000 00:00 0
2b971ab0d000-2b971ab71000 r-xp 00000000 fd:00 135002524                  /usr/lib64/libssl.so.1.0.1e
2b971ab71000-2b971ad70000 ---p 00064000 fd:00 135002524                  /usr/lib64/libssl.so.1.0.1e
2b971ad70000-2b971ad74000 r--p 00063000 fd:00 135002524                  /usr/lib64/libssl.so.1.0.1e
2b971ad74000-2b971ad7b000 rw-p 00067000 fd:00 135002524                  /usr/lib64/libssl.so.1.0.1e
2b971ad7b000-2b971af3b000 r-xp 00000000 fd:00 134822113                  /usr/lib64/libcrypto.so.1.0.1e
2b971af3b000-2b971b13b000 ---p 001c0000 fd:00 134822113                  /usr/lib64/libcrypto.so.1.0.1e
2b971b13b000-2b971b155000 r--p 001c0000 fd:00 134822113                  /usr/lib64/libcrypto.so.1.0.1e
2b971b155000-2b971b161000 rw-p 001da000 fd:00 134822113                  /usr/lib64/libcrypto.so.1.0.1e
2b971b161000-2b971b165000 rw-p 00000000 00:00 0
2b971b165000-2b971b17c000 r-xp 00000000 fd:00 135797108                  /usr/lib64/libpthread-2.17.so
2b971b17c000-2b971b37b000 ---p 00017000 fd:00 135797108                  /usr/lib64/libpthread-2.17.so
2b971b37b000-2b971b37c000 r--p 00016000 fd:00 135797108                  /usr/lib64/libpthread-2.17.so
2b971b37c000-2b971b37d000 rw-p 00017000 fd:00 135797108                  /usr/lib64/libpthread-2.17.so
2b971b37d000-2b971b381000 rw-p 00000000 00:00 0
2b971b381000-2b971b383000 r-xp 00000000 fd:00 138205191                  /usr/lib64/libdl-2.17.so
2b971b383000-2b971b583000 ---p 00002000 fd:00 138205191                  /usr/lib64/libdl-2.17.so
2b971b583000-2b971b584000 r--p 00002000 fd:00 138205191                  /usr/lib64/libdl-2.17.so
2b971b584000-2b971b585000 rw-p 00003000 fd:00 138205191                  /usr/lib64/libdl-2.17.so
2b971b585000-2b971b73b000 r-xp 00000000 fd:00 135114791                  /usr/lib64/libc-2.17.so
2b971b73b000-2b971b93b000 ---p 001b6000 fd:00 135114791                  /usr/lib64/libc-2.17.so
2b971b93b000-2b971b93f000 r--p 001b6000 fd:00 135114791                  /usr/lib64/libc-2.17.so
2b971b93f000-2b971b941000 rw-p 001ba000 fd:00 135114791                  /usr/lib64/libc-2.17.so
2b971b941000-2b971b946000 rw-p 00000000 00:00 0
2b971b946000-2b971b991000 r-xp 00000000 fd:00 134292658                  /usr/lib64/libgssapi_krb5.so.2.2
2b971b991000-2b971bb91000 ---p 0004b000 fd:00 134292658                  /usr/lib64/libgssapi_krb5.so.2.2
2b971bb91000-2b971bb92000 r--p 0004b000 fd:00 134292658                  /usr/lib64/libgssapi_krb5.so.2.2
2b971bb92000-2b971bb94000 rw-p 0004c000 fd:00 134292658                  /usr/lib64/libgssapi_krb5.so.2.2
2b971bb94000-2b971bc6a000 r-xp 00000000 fd:00 134795070                  /usr/lib64/libkrb5.so.3.3
2b971bc6a000-2b971be6a000 ---p 000d6000 fd:00 134795070                  /usr/lib64/libkrb5.so.3.3
2b971be6a000-2b971be78000 r--p 000d6000 fd:00 134795070                  /usr/lib64/libkrb5.so.3.3
2b971be78000-2b971be7b000 rw-p 000e4000 fd:00 134795070                  /usr/lib64/libkrb5.so.3.3
2b971be7b000-2b971be7e000 r-xp 00000000 fd:00 134292656                  /usr/lib64/libcom_err.so.2.1
2b971be7e000-2b971c07d000 ---p 00003000 fd:00 134292656                  /usr/lib64/libcom_err.so.2.1
2b971c07d000-2b971c07e000 r--p 00002000 fd:00 134292656                  /usr/lib64/libcom_err.so.2.1
2b971c07e000-2b971c07f000 rw-p 00003000 fd:00 134292656                  /usr/lib64/libcom_err.so.2.1
2b971c07f000-2b971c0ae000 r-xp 00000000 fd:00 134292671                  /usr/lib64/libk5crypto.so.3.1
2b971c0ae000-2b971c2ad000 ---p 0002f000 fd:00 134292671                  /usr/lib64/libk5crypto.so.3.1
2b971c2ad000-2b971c2af000 r--p 0002e000 fd:00 134292671                  /usr/lib64/libk5crypto.so.3.1
2b971c2af000-2b971c2b0000 rw-p 00030000 fd:00 134292671                  /usr/lib64/libk5crypto.so.3.1
2b971c2b0000-2b971c2b1000 rw-p 00000000 00:00 0
2b971c2b1000-2b971c2c6000 r-xp 00000000 fd:00 138205213                  /usr/lib64/libz.so.1.2.7
2b971c2c6000-2b971c4c5000 ---p 00015000 fd:00 138205213                  /usr/lib64/libz.so.1.2.7
2b971c4c5000-2b971c4c6000 r--p 00014000 fd:00 138205213                  /usr/lib64/libz.so.1.2.7
2b971c4c6000-2b971c4c7000 rw-p 00015000 fd:00 138205213                  /usr/lib64/libz.so.1.2.7
2b971c4c7000-2b971c4d4000 r-xp 00000000 fd:00 134795264                  /usr/lib64/libkrb5support.so.0.1
2b971c4d4000-2b971c6d4000 ---p 0000d000 fd:00 134795264                  /usr/lib64/libkrb5support.so.0.1
2b971c6d4000-2b971c6d5000 r--p 0000d000 fd:00 134795264                  /usr/lib64/libkrb5support.so.0.1
2b971c6d5000-2b971c6d6000 rw-p 0000e000 fd:00 134795264                  /usr/lib64/libkrb5support.so.0.1
2b971c6d6000-2b971c6d9000 r-xp 00000000 fd:00 134323684                  /usr/lib64/libkeyutils.so.1.5
2b971c6d9000-2b971c8d8000 ---p 00003000 fd:00 134323684                  /usr/lib64/libkeyutils.so.1.5
2b971c8d8000-2b971c8d9000 r--p 00002000 fd:00 134323684                  /usr/lib64/libkeyutils.so.1.5
2b971c8d9000-2b971c8da000 rw-p 00003000 fd:00 134323684                  /usr/lib64/libkeyutils.so.1.5
2b971c8da000-2b971c8fe000 r-xp 00000000 fd:00 134292784                  /usr/lib64/libselinux.so.1
2b971c8fe000-2b971cafd000 ---p 00024000 fd:00 134292784                  /usr/lib64/libselinux.so.1
2b971cafd000-2b971cafe000 r--p 00023000 fd:00 134292784                  /usr/lib64/libselinux.so.1
2b971cafe000-2b971caff000 rw-p 00024000 fd:00 134292784                  /usr/lib64/libselinux.so.1
2b971caff000-2b971cb01000 rw-p 00000000 00:00 0
2b971cb01000-2b971cb61000 r-xp 00000000 fd:00 134324038                  /usr/lib64/libpcre.so.1.2.0
2b971cb61000-2b971cd60000 ---p 00060000 fd:00 134324038                  /usr/lib64/libpcre.so.1.2.0
2b971cd60000-2b971cd61000 r--p 0005f000 fd:00 134324038                  /usr/lib64/libpcre.so.1.2.0
2b971cd61000-2b971cd62000 rw-p 00060000 fd:00 134324038                  /usr/lib64/libpcre.so.1.2.0
2b971cd62000-2b971cd6e000 r-xp 00000000 fd:00 135797097                  /usr/lib64/libnss_files-2.17.so
2b971cd6e000-2b971cf6d000 ---p 0000c000 fd:00 135797097                  /usr/lib64/libnss_files-2.17.so
2b971cf6d000-2b971cf6e000 r--p 0000b000 fd:00 135797097                  /usr/lib64/libnss_files-2.17.so
2b971cf6e000-2b971cf6f000 rw-p 0000c000 fd:00 135797097                  /usr/lib64/libnss_files-2.17.so
2b971cf6f000-2b971cf75000 rw-p 00000000 00:00 0
2b971cf75000-2b971cf7a000 r-xp 00000000 fd:00 138205199                  /usr/lib64/libnss_dns-2.17.so
2b971cf7a000-2b971d179000 ---p 00005000 fd:00 138205199                  /usr/lib64/libnss_dns-2.17.so
2b971d179000-2b971d17a000 r--p 00004000 fd:00 138205199                  /usr/lib64/libnss_dns-2.17.so
2b971d17a000-2b971d17b000 rw-p 00005000 fd:00 138205199                  /usr/lib64/libnss_dns-2.17.so
2b971d17b000-2b971d190000 r-xp 00000000 fd:00 134822118                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2b971d190000-2b971d38f000 ---p 00015000 fd:00 134822118                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2b971d38f000-2b971d390000 r--p 00014000 fd:00 134822118                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2b971d390000-2b971d391000 rw-p 00015000 fd:00 134822118                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2b9720000000-2b9720021000 rw-p 00000000 00:00 0
2b9720021000-2b9724000000 ---p 00000000 00:00 0
7ffe8265e000-7ffe8267f000 rw-p 00000000 00:00 0                          [stack]
7ffe8273d000-7ffe8273f000 r-xp 00000000 00:00 0                          [vdso]

ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
<Terminated by signal 6 (Aborted).>

**Comment by waja** [comment]
> I am receiving the next error in a particular case when the vhost has the string "1000..." on the version 2.4.1 .

Version 2.4.1 of what software?

**Comment by Jazb** [comment]
Forgiveness, I suffered from severe confusion.. To be exact the name of package is:

nagios-plugins-http-2.1.4-2.el7.x86_64

**Comment by waja** [comment]
> nagios-plugins-http-2.1.4-2.el7.x86_64

You should ask the fork from Nagios LLC: https://github.com/nagios-plugins/nagios-plugins. This is not the same plugin (anymore) we are distributing.

**Comment by Jazb** [comment]
Oh excuse me, my mistake of not observing well ... thank you for your guidance
