### ISSUE TITLE
check_http fails to present proxy credientials when using the -S -j CONNECT flags

### ISSUE THREAD

**Issue by agentdavidson** [monitoring-plugins/monitoring-plugins#1472]
Hello -

I'm having an issue getting check_http to work via an authenticated proxy when using the -S -j CONNECT flags.

Does anymore know if this is a supported configuration?

Appended is (anonymised) output showing success when using proxy + authentication + http url but failure when using proxy + authentication + https url 

SUCCESS...
[root@myserver:/usr/local/libexec] ./check_http -I myproxy.mydomain.com -p 8080 -u http://www.google.co.nz/ -b myusername:mypassword -w 1 -c 5 -v   GET http://www.google.co.nz/ HTTP/1.0
User-Agent: check_http/v2.2 (monitoring-plugins 2.2)
Connection: close
Proxy-Authorization: Basic bWRmYzM5OlBoYXRzazhAQEA=

http://myproxy.mydomain.com:8080http://www.google.co.nz/ is 11412 characters
STATUS: HTTP/1.1 200 OK
[Head and Content follow but removed from this post]
HTTP OK: HTTP/1.1 200 OK - 11412 bytes in 0.245 second response time |time=0.245205s;1.000000;5.000000;0.000000;10.000000 size=11412B;;;0

FAILURE...
[root@myserver:/usr/local/libexec] ./check_http -I myproxy.mydomain.com -p 8080 -S -j CONNECT -H www.google.co.nz -u / -b myusername:mypassword -w 1 -c 5 -v
Entering CONNECT tunnel mode with proxy myproxy.mydomain.com:8080 to dst www.google.co.nz:443
CONNECT www.google.co.nz:443 HTTP/1.1
User-Agent: check_http/v2.2 (monitoring-plugins 2.2)
Proxy-Connection: keep-alive
Host: www.google.co.nz

Receive response from proxy
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: NTLM
Proxy-Authenticate: BASIC realm="Please enter Username and Password"
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 1274

[Proxy responds with it's "Not authenticated" HTML page but removed from this post]

CRITICAL - Cannot make SSL connection.
SSL initialized

It would seem that check_http fails to present proxy credentials when using the -S -j CONNECT flags

If I disable authentication on the proxy the -S -j CONNECT scenario works.

**Comment by agentdavidson** [comment]
Re-posted here which is probably the better forum for it.
https://support.nagios.com/forum/viewtopic.php?f=35&t=42929

**Comment by sni** [comment]
Have you tried removing the -S and use a https://... url for -u. Otherwise check_http trys to speak https with the proxy which is probably http only. In fact, check_http has an example in its help output:

```
 check_http -I 192.168.100.35 -p 80 -u https://www.verisign.com/ -S -j CONNECT -H www.verisign.com 
 all these options are needed: -I <proxy> -p <proxy-port> -u <check-url> -S(sl) -j CONNECT -H <webserver>
 a STATE_OK will be returned. When the server returns its content but exceeds
 the 5-second threshold, a STATE_WARNING will be returned. When an error occurs,
 a STATE_CRITICAL will be returned.

```

**Comment by beiermi** [comment]
I can confirm this issue.
@sni: Removing -S and use a https://... url does not work.

It's a bug, the Proxy-Authorization header is not added to request headers, if the commandline options -S and -j CONNECT are used. Patch for v2.2.git:

```
--- check_http.orig     2017-07-06 14:18:04.000000000 +0200
+++ check_http.c        2017-07-06 14:33:37.000000000 +0200
@@ -918,6 +918,10 @@
     asprintf (&buf, "%s %s:%d HTTP/1.1\r\n%s\r\n", http_method, host_name, HTTPS_PORT, user_agent);
     asprintf (&buf, "%sProxy-Connection: keep-alive\r\n", buf);
     asprintf (&buf, "%sHost: %s\r\n", buf, host_name);
+    if (strlen(proxy_auth)) {
+      base64_encode_alloc (proxy_auth, strlen (proxy_auth), &auth);
+      asprintf (&buf, "%sProxy-Authorization: Basic %s\r\n", buf, auth);
+    }
     /* we finished our request, send empty line with CRLF */
     asprintf (&buf, "%s%s", buf, CRLF);
     if (verbose) printf ("%s\n", buf);
```

Can you please check this ..

Michael

**Comment by agentdavidson** [comment]
Hi Michael -
I can confirm that the patch has resolved the issue in my environment.  Well done!  So will this fix make it's way into the mainstream release at some point?
Matt

**Comment by beiermi** [comment]
Hi Matt,

thank you for the feedback. I'm not familiar with creating pull requests, maybe I should change that ;-)

Michael

**Comment by sni** [comment]
should be fixed with https://github.com/monitoring-plugins/monitoring-plugins/pull/1514
