### ISSUE TITLE
 incomplete SSL certificate verify

### ISSUE THREAD

**Issue by ruanlinqi** [monitoring-plugins/monitoring-plugins#1479]
Hi developers:
  Nowadays we made a large scale security static analysis on several open source projects, and found some mistakes in monitoring-plugins-2.1.2. In the @plugins/sslutils.c:164:
```
 int np_net_ssl_check_cert(int days_till_exp_warn, int days_till_exp_crit){
      # ifdef USE_OPENSSL
 [...]
 certificate=SSL_get_peer_certificate(s);

 if (!certificate) {
  printf("%s\n",_("CRITICAL - Cannot retrieve server certificate."));
  return STATE_CRITICAL;
 }

 /* Extract CN from certificate subject */
 subj=X509_get_subject_name(certificate);
       [...]
 }
```

     We find that you use SSL_get_peer_certificate() to get the cert and verify some properties of it.But it still not secure enough and can lead to MITM attack. To guarantee the security,we recommand you add the judgement if(SSL_get_verify_result(ssl)==X509_V_OK) to make sure validation succeeds.

**Comment by sni** [comment]
We do not verify the certificate, all we do is extracting the expire date. Do not use check_http for security related certificate verification.

**Comment by waja** [comment]
You want to use https://github.com/matteocorti/check_ssl_cert
