### ISSUE TITLE
building with explicitly enabled perl will flood your build logs to end of diskspace

### ISSUE THREAD

**Issue by ncopa** [monitoring-plugins/monitoring-plugins#1480]
If you want explicitly enable a build with perl, want to use the autodetectected path to perl, and want it to exit with failure in case perl was not found, then you'd likely do something like:

`./configure --with-perl ...`

But if you do that, then will you trigger an endless `yes` which flood the build log til you no longer have diskspace on your build server.

The reason is in the following snippet:
````
dnl allow them to override the path of perl
AC_ARG_WITH(perl,
        ACX_HELP_STRING([--with-perl=PATH],
                        [sets path to perl executable]),
                        with_perl=$withval,with_perl=$PERL)
AC_SUBST(PERL, $with_perl)
````

autotools will set `$withval` to `yes` if you dont specify a path, which leads to `PERL=yes`. so when you later try execute `if ( $PERL -M"Net::SNMP 3.6" -e 'exit' 2>/dev/null  )`  you end up executing the command `yes` which never exits.

One workaround is to either set the path to perl: `--with-perl=/usr/bin/perl` but then you lose the autodetection of it (the `AC_PATH_PROG(PERL,perl)` could be removed in such case).

Another workaround is to simply drop the `--with-perl` option, in which case you might end up with a build without perl if it for some reason is not installed at build time.

**Comment by ncopa** [comment]
something like this fixes it:

````diff
--- ./configure.ac.orig
+++ ./configure.ac
@@ -120,6 +120,9 @@
         ACX_HELP_STRING([--with-perl=PATH],
                        [sets path to perl executable]),
                        with_perl=$withval,with_perl=$PERL)
+if test "$with_perl" = "yes"; then
+       with_perl="$PERL"
+fi
 AC_SUBST(PERL, $with_perl)

 dnl openssl/gnutls
````

**Comment by ncopa** [comment]
seems like there are more similar errors:
````
../libtool: line 7472: cd: yes/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'yes/lib'
make[2]: *** [Makefile:1993: check_dummy] Error 1
````

**Comment by RincewindsHat** [comment]
well, most of the `--with-...` options expect an argument.
