### ISSUE TITLE
check_rpc: recognize capitalized "Program" in rpcinfo output

### ISSUE THREAD

**Issue by efuss** [monitoring-plugins/monitoring-plugins#1488]
At least on NetBSD and in the „not registered“ case, rpcinfo capitalizes „program“ in the „Program xxxx is not available“ message. Currently, check_rpc doesn't recognize this output, making it report UNKNOWN state where it should be reporting CRITICAL.
The patch for this is trivial.
[patch.txt](https://github.com/monitoring-plugins/monitoring-plugins/files/995852/patch.txt)

**Comment by RincewindsHat** [comment]
Sounds harmless, @sni your the perl guy

**Comment by sni** [comment]
Looks fine for me. Manually applied the patch. Thanks and sorry for the delay...
