### ISSUE TITLE
check_ssh: add new switch for empty response

### ISSUE THREAD

**Issue by adnae** [monitoring-plugins/monitoring-plugins#1497]
Hi guys,

currently check_ssh send a critical state, when the answer from the SSH server is "empty", but the server is reachable and the ssh connect is possible.

My question is: Please can you add a switch for check_ssh, that an empty responses send only a warning and not a critical state?

thanks

**Comment by wbollock** [comment]
I'm also interested in this - https://github.com/monitoring-plugins/monitoring-plugins/pull/1738 appears to be a fix rather than having to add a warning flag

**Comment by RincewindsHat** [comment]
Probably fixed by #1738
