### ISSUE TITLE
check_by_ssh returns 'Remote command execution failed'

### ISSUE THREAD

**Issue by if-kyle** [monitoring-plugins/monitoring-plugins#1499]
Hello,

I have check_by_ssh working with most commands, but some require a RequestTTY=force, and I cannot get those to work.
```
ssh user@web -i /opt/nagios/keys/id_rsa -oRequestTTY=force 'drush-purge-queue-count shared8'
Works and returns
197
Connection to web closed
echo $?
0
```
When I try to convert this to check_by_ssh, the command runs for a few seconds (which the ssh does as well) but then simply returns an error

`./check_by_ssh -l user -H web -i /opt/nagios/keys/id_rsa -o RequestTTY=force 'drush-purge-queue-count shared8'`

returns
```
Remote command execution failed: Connection to web closed.
echo $?
3
```
When I follow the secure log on the web box, I see the command coming across correctly with check_by_ssh.  The -v option doesn't give me any more output to see whats going on.

Thanks in advance!

**Comment by RincewindsHat** [comment]
Fails for me when I use `RequestTTY=force`, does it work for you without it?

**Comment by RincewindsHat** [comment]
no feedback
