### ISSUE TITLE
check_mysql.c and check_mysql_query.c compile failure with MariaDB 10.2.8

### ISSUE THREAD

**Issue by reubenfarrelly** [monitoring-plugins/monitoring-plugins#1508]
After upgrading to MariaDB 10.2.8, these two plugins above no longer compile, both failing with the same error:

x86_64-pc-linux-gnu-gcc -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I..  -I.. -I../lib -I../gl -I../intl -I/usr/include -I/usr/include/mysql -I/usr/include/mysql/..  -DNP_VERSION='"2.2"' -I/usr/include/mysql -I/usr/include/mysql/..  -O2 -pipe -march=native -mtune=native -fno-strict-aliasing -c -o check_mysql-check_mysql.o `test -f 'check_mysql.c' || echo './'`check_mysql.c
check_mysql.c:61:24: error: ‘MYSQL_PORT’ undeclared here (not in a function); did you mean ‘MYSQL_STMT’?
 unsigned int db_port = MYSQL_PORT;
                        ^~~~~~~~~~
                        MYSQL_STMT
make: *** [Makefile:1873: check_mysql-check_mysql.o] Error 1
tornado plugins #

This is with monitoring-plugins 2.2 on a Gentoo Linux system (very up to date).
It seems that MYSQL_PORT is no longer defined in the usual mysql headers, however it is defined in: mysql/server/private/custom_conf.h

By adding this include:

--- a/plugins/check_mysql.c     2017-09-09 10:48:45.725792432 +1000
+++ b/plugins/check_mysql.c     2017-09-09 10:40:53.173809026 +1000
@@ -44,6 +44,7 @@
 #include <mysql.h>
 #include <mysqld_error.h>
 #include <errmsg.h>
+#include <server/private/custom_conf.h>

 char *db_user = NULL;
 char *db_host = NULL;
--- a/plugins/check_mysql_query.c       2017-09-09 10:50:15.969789263 +1000
+++ b/plugins/check_mysql_query.c       2017-09-09 10:41:24.869807913 +1000
@@ -40,6 +40,7 @@

 #include <mysql.h>
 #include <errmsg.h>
+#include <server/private/custom_conf.h>

 char *db_user = NULL;
 char *db_host = NULL;

----

The two plugins then compile again.

Can this - or a similar/better fix that perhaps deals with the case where this include does not exist - please be committed to the source tree? Or could we just remove the hard dependency on the definition of MYSQL_PORT so that this include is not required in the first place?

Thanks,
Reuben

**Comment by grknight** [comment]
Please do not use MYSQL_PORT.  Instead use a 0 to have the library read from the my.cnf (or similar) file as noted in https://dev.mysql.com/doc/refman/5.5/en/mysql-real-connect.html

**Comment by orlitzky** [comment]
I think that "whatever port the MySQL server on the local machine is using" is not the best default anyway, considering that `check_mysql` is often used to monitor _other_ servers (and not the local one). The suggestion made by @grknight would retain the existing behavior, but if the upstream maintainers agree, please consider simply setting it to `3306`. That's the "MySQL port" as defined in `/etc/services`, and is usually the port you want to monitor. Furthermore, having a static value for the default port reduces the variability between configurations, meaning that `check_mysql` won't do something different if you run it from your coworker's machine.

The change would be backwards-**in**compatible: anyone relying on the default port being read from `my.cnf` would need to specify a port explicitly. If the "port" argument is passed through unmolested, we could also document the fact that a port of `0` tells the plugin to read it from `my.cnf`.

**Comment by stzoran1** [comment]
I followed instructions @reubenfarrelly wrote and it is working on version 2.1.1 too. Thank you.

**Comment by CLARENNE-Q** [comment]
Do you have some news about this issue ?

I have the same error:

`/bin/sh ../libtool --tag=CC   --mode=link gcc -DNP_VERSION='"2.2.1"' -g -O2  -L. -o check_uptime check_uptime.o libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a -lrt -lpthread -ldl 
libtool: link: gcc -DNP_VERSION=\"2.2.1\" -g -O2 -o check_uptime check_uptime.o  -L. libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a -lrt -lpthread -ldl
gcc -DLOCALEDIR=\"/usr/local/nagios/share/locale\" -DHAVE_CONFIG_H -I. -I..  -I.. -I../lib -I../gl -I../intl -I/usr/include -I/usr/include/mysql -I/usr/include/mysql/mysql  -DNP_VERSION='"2.2.1"' -I/usr/include/mysql -I/usr/include/mysql/mysql -g -O2 -MT check_mysql-check_mysql.o -MD -MP -MF .deps/check_mysql-check_mysql.Tpo -c -o check_mysql-check_mysql.o `test -f 'check_mysql.c' || echo './'`check_mysql.c
check_mysql.c:61: erreur: ‘MYSQL_PORT’ undeclared here (not in a function)
make[2]: *** [check_mysql-check_mysql.o] Erreur 1
make[2]: quittant le répertoire « /root/linux-nrpe-agent/subcomponents/nagiosplugins/nagios-plugins-2.2.1/plugins »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /root/linux-nrpe-agent/subcomponents/nagiosplugins/nagios-plugins-2.2.1 »
make: *** [all] Erreur 2

real	0m14.742s
user	0m12.341s
sys	0m1.815s`

**Comment by sni** [comment]
thanks, this has been fixed with #1522
