### ISSUE TITLE
check_tcp SNI support

### ISSUE THREAD

**Issue by brandoss** [monitoring-plugins/monitoring-plugins#1510]
Many SSL servers now use SNI to deliver certs.  This can cause an issue when using check_tcp.  If not using SNI check_tcp may be comparing against the wrong certificate for expire dates.

A discussion around SNI and the differences between nagios-plugins and monitoring-plugins for this feature took place at:
https://github.com/Icinga/icinga2/issues/5577

For an example, you can see that trying to check the icinga.org certificate check_tcp actually checks the icinga.com certificate without SNI support.

```
/usr/lib/nagios/plugins/check_tcp -H icinga.org -p 443 --ssl -D 90,30
OK - Certificate '*.icinga.com' will expire on Thu 26 Dec 2019 11:59:00 PM STD.
TCP OK - 0.616 second response time on icinga.org port 443|time=0.615661s;;;0.000000;10.000000
```
The version of check_tcp I tested with:
```
/usr/lib/nagios/plugins/check_tcp -V
check_tcp v2.1.2 (monitoring-plugins 2.1.2)
```

**Comment by sni** [comment]
check_http has SNI support:

```
%> ./check_http -H icinga.org -p 443 --ssl --sni -C 90,30
OK - Certificate '*.icinga.org' will expire on Thu 26 Jul 2018 11:59:59 PM GMT +0000.
```

**Comment by wifibox** [comment]
What about if I have to check IMAP cert? Since Let's Encrypt does so good, I have many certs on my dovecot host, and I need to monitor such host and correctness of deploy renewed certs.
In this case implementation Server Name Indication (SNI) will be a natural thing to do.

**Comment by geotekberlin** [comment]
The --sni parameter is still missing in ITL, could someone please add it?

**Comment by RincewindsHat** [comment]
@geotekberlin ITL is part of https://github.com/Icinga/ and maintained there
