### ISSUE TITLE
Proxy authorization is not kept when using PROXY + CONNECT to HTTPS

### ISSUE THREAD

**Issue by Rasp8e** [monitoring-plugins/monitoring-plugins#1515]
When using the check_http through a proxy that uses basic authentication towards a HTTPS url using CONNECT, the proxy-authorization and extra HEADERS are disregarded

**Comment by Rasp8e** [comment]
The fix is already pushed and pull request was created:
https://github.com/monitoring-plugins/monitoring-plugins/pull/1514

**Comment by sni** [comment]
thanks, merged your PR.
