### ISSUE TITLE
check_radius: 

### ISSUE THREAD

**Issue by fmikker** [monitoring-plugins/monitoring-plugins#1519]
Version: check_radius v2.1.1.git (monitoring-plugins 2.1.1)
check_command: ``` $USER1$/check_radius -H $HOSTADDRESS$ -F /etc/radiusclient-ng/radiusclient.conf -u $ARG1$ -p $ARG2$ -t 10```

The default installation of the radius check is  problematic since a regular user cannot read the `servers` file (as referred to by /etc/radiusclient-ng/radiusclient.conf), in which the login name and password etc is stated.

Default setup is:
```[root@localhost radiusclient-ng] ls -alt
total 24
drwxr-xr-x. 79 root root 4096 Apr 22 16:51 ..
drwxr-xr-x.  2 root root 4096 Oct 30  2012 .
-rw-r--r--.  1 root root  135 May 10  2010 issue
-rw-r--r--.  1 root root  410 May 10  2010 port-id-map
-rw-r--r--.  1 root root 2622 May 10  2010 radiusclient.conf
-rw-------.  1 root root  169 May 10  2010 servers
```
All files directly or indirectly read by the check plugins needs to be readable by a regular user, or the check will fail with error "Auth Error".

Downstream issue: https://jira.op5.com/browse/MON-6729

**Comment by waja** [comment]
Hi @fmikker,

thanks for bringing this to our attention.

> The default installation of the radius check is  problematic since a regular user cannot read the `servers` file (as referred to by /etc/radiusclient-ng/radiusclient.conf), in which the login name and password etc is stated.
>
> Default setup is:
> ```[root@localhost radiusclient-ng] ls -alt
> total 24
> drwxr-xr-x. 79 root root 4096 Apr 22 16:51 ..
> drwxr-xr-x.  2 root root 4096 Oct 30  2012 .
> -rw-r--r--.  1 root root  135 May 10  2010 issue
> -rw-r--r--.  1 root root  410 May 10  2010 port-id-map
> -rw-r--r--.  1 root root 2622 May 10  2010 radiusclient.conf
> -rw-------.  1 root root  169 May 10  2010 servers
> ```

Keeping my Debian monitoring-plugins maintainers hat on, I would declare that as a local configuration issue.

In Debian (at least 8.x) the default permissions of the ```servers``` file is 644. I double checked that for _libfreeradius-client2_ and _libradcli4_. For whatever reason the maintainers of those packages decided this seems reasonable.

**Comment by fmikker** [comment]
@waja 
Thank you for the extensive answer!
You are completely right, this should be reported to Red Hat.

**Comment by waja** [comment]
@fmikker it might be still a good idea to keep the servers file not world readable, as there are credentials inside. Anyway ... when connecting to a server you need credentials. This is also the case when running check_radius as unprivileged user, which is indeed recommended.
