### ISSUE TITLE
[check_disk] calculation mismatch between plugin output and performace data

### ISSUE THREAD

**Issue by SimonHoenscheid** [monitoring-plugins/monitoring-plugins#1525]
It seems like check_disk calculates the values for plugin output and performance data different. 

plugin output:

```
/check_disk -w "20%" -c "10%" --partition /var/log
DISK WARNING - free space: /var/log 765 MB (16.49% inode=100%);| /var/log=3874MB;3928;4419;0;4911
```
having a look at the plugin calculation itself, the warning is reached. 
calculating with the plugin output it has not:

partition size: 4911 MB (100.00 %)
current usage: 3874MB (78.88 %)
warning treshhold would be: 3928 MB (80.00 %)
critical treshhold would be: 4419MB (90.00 %)

could it be that the divider for the performance data is 1000 while the one for the plugin logic itself is 1024 for the basic size calculation?

**Comment by mrejas** [comment]
This a very old bug. Any plans on fixing it?

```
$ ./check_disk -w 20% -c 10% /
DISK WARNING - free space: / 1946 MB (20% inode=68%);| /=7540MB;8012;9013;0;10015
$ ./check_disk --version
check_disk v2.2 (monitoring-plugins 2.2)
```
It looks strange when warning and critical is graphed and the check is warning when the line in the graph has not reached the warning level.

**Comment by RincewindsHat** [comment]
This might not be relevant anymore, but does this work with the current master?

**Comment by RincewindsHat** [comment]
Closing this, for the purpose of tidying up a little bit. Please reopen, if the problem still persists.
