### ISSUE TITLE
Any way to issue critical from 4xx with `check_http` plugin?

### ISSUE THREAD

**Issue by rafecolton** [monitoring-plugins/monitoring-plugins#1529]
I have a `check_http` check I would like to be considered critical if it returns a 4xx. By default, a 4xx is only a warning. 

I could accomplish this using `-e`, but it would be very tedious to list out every single possible success status code. For example:

```bash
# without `-e`, 401 issues a warning
ubuntu@monitor:~$ /usr/lib/nagios/plugins/check_http -H 10.0.0.5 -j GET -p 5001 -u /bogus
HTTP WARNING: HTTP/1.1 401 Unauthorized - 417 bytes in 0.002 second response time |time=0.001819s;;;0.000000 size=417B;;;0

# with `-e`, 401 issues a critical
ubuntu@monitor:~$ /usr/lib/nagios/plugins/check_http -H 10.0.0.5 -j GET -p 5001 -u /bogus -e 'HTTP/1.1 200 OK,HTTP/1.0 200 OK,HTTP/1.1 204 No Content,HTTP/1.0 204 No Content'
HTTP CRITICAL - Invalid HTTP response received from host on port 5001: HTTP/1.1 401 Unauthorized
```

Is there a more efficient way to do this?

**Comment by K0nne** [comment]
Is it possible to add a mitigation parameter to tackle this screnario?

**Comment by sni** [comment]
As soon as you specify specific return codes with `-e`, the plugin will exit critcal if it is not that return code. You can also specify more than one allowed return code like this:
```
%> ./check_http -H localhost -u /none -e 200,201,302
HTTP CRITICAL - Invalid HTTP response received from host: HTTP/1.1 404 Not Found
```
