### ISSUE TITLE
check_apt works onyl if nagios user has a default shell

### ISSUE THREAD

**Issue by sgargel** [monitoring-plugins/monitoring-plugins#1541]
On debian 9.4 the check_apt plugin work only if nagios user has a default shell

    root@my:~# getent passwd | grep nagios
    nagios:x:108:113::/var/lib/nagios:/bin/false
    root@my:~# su - nagios -c "/usr/lib/nagios/plugins/check_apt"
    root@my:~# su - nagios -s /bin/bash -c "/usr/lib/nagios/plugins/check_apt"
    APT CRITICAL: 10 packages available for upgrade (10 critical updates). |available_upgrades=10;;;0 critical_updates=10;;;0

It's a bug or is by desing?

**Comment by waja** [comment]
At first, this is no issue with check_apt itself.

As check_apt makes use of [`apt-get`](https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins/check_apt.c#L52) you need indeed need a shell to execute `apt-get`.

Cheers, Jan.
