### ISSUE TITLE
check_mailq (using check_by_ssh)

### ISSUE THREAD

**Issue by klepallec** [monitoring-plugins/monitoring-plugins#1546]
Hello, 

I want to check mail queued on a centos 7 using check_by_ssh. 
The commande failed with this error : 

```
./check_by_ssh -H zimbra -C '/usr/lib64/nagios/plugins/check_mailq -w 10 -c 20 -M' -t 120
L'exécution de la commande à distance mailq: Mail queue is empty à échoué
```

In local on the machine there is no problem : 
```
[centreon-engine@zimbra plugins]$ ./check_mailq -w 10 -c 20 -M sendmail
mailq: Mail queue is empty
OK: sendmail mailq is empty|unsent=0;10;20;0
```

I use the user nagios of centreon to monitore by ssh.

Permission on my plugin : 
```
-rwxr-xr-x. 1 centreon-engine centreon-engine  25582 21 nov.   2017 check_mailq
```

I monitore other server on debian 9.5 with this plugin by ssh and there is no problem.
I try the plugin of my debian on my centos 7 and the problem is the same.

I dont make changement on `/etc/sudoers` on debian so i think on centos it's the same. 

Here my version of plugin check_mailq :
```
./check_mailq -w 10 -c 20 -M -V
check_mailq v2.2.1.git (nagios-plugins 2.2.1)
nagios-plugins-mailq-2.2.1-9git5c7eb5b9.el7.x86_64
```

**Comment by RincewindsHat** [comment]
Is this problem still existing?

**Comment by RincewindsHat** [comment]
Just saw, that this is related to [Nagios Plugins](https://github.com/nagios-plugins/nagios-plugins).
Closing this therefore.
