### ISSUE TITLE
[check_snmp] authpassword is actually authpasswd

### ISSUE THREAD

**Issue by chuhn** [monitoring-plugins/monitoring-plugins#1551]
`check_snmp` only understands `--authpasswd=[…]` the output of `check_snmp --help` is wrong:

https://github.com/monitoring-plugins/monitoring-plugins/blob/22f13aa2f19e1eb97f1a7feea248b3d25b038d92/plugins/check_snmp.c#L1163

**Comment by RincewindsHat** [comment]
Is this still a problem? If so, could you elaborate a bit? Do you need to place square brackets around the password?

**Comment by chuhn** [comment]
Looking at the code it is still ther:

https://github.com/monitoring-plugins/monitoring-plugins/blob/f0ac7fcc7c40fab04c00fbbc8c091e89e77b0f74/plugins/check_snmp.c#L1164
mentions "authpassw**or**d" while
https://github.com/monitoring-plugins/monitoring-plugins/blob/f0ac7fcc7c40fab04c00fbbc8c091e89e77b0f74/plugins/check_snmp.c#L676
and 
https://github.com/monitoring-plugins/monitoring-plugins/blob/f0ac7fcc7c40fab04c00fbbc8c091e89e77b0f74/plugins/check_snmp.c#L1260
speak about "authpasswd".

Fix: `sed -ie 's/authpassword/authpasswd/' check_snmp.c`

Cheers

Christopher

**Comment by RincewindsHat** [comment]
Ahh, now I see. I misread your initial message. Thanks

**Comment by RincewindsHat** [comment]
#1676

**Comment by RincewindsHat** [comment]
Fixed, thanks for the notice
