### ISSUE TITLE
check_http doesn't report perfdata with -C

### ISSUE THREAD

**Issue by stblassitude** [monitoring-plugins/monitoring-plugins#1553]
```
$ '/usr/local/libexec/nagios/check_http' '--sni' '-H' 'www.example.com' '-I' 'www.example.com' '-S' '-c' '1' '-w' '0.500000'
HTTP OK: HTTP/1.1 200 OK - 176 bytes in 0.231 second response time |time=0.230736s;0.500000;1.000000;0.000000;10.000000 size=176B;;;0
$ '/usr/local/libexec/nagios/check_http' '--sni' '-C' '10,2' '-H' 'www.example.com' '-I' 'www.example.com' '-S' '-c' '1' '-w' '0.500000'
OK - Certificate  'www.example.com' will expire on Thu Jan  3 03:28:38 2019 +0000.
```

This is i monitoring-plugins 2.2.

I would expect the perfdata to be reported also when checking the cert expiration.

**Comment by odenbach** [comment]
If you use the -C switch, check_http does not make a http request at all. It just checks the certificate. So what perfdata would you like to have? The number of days the certificate will be still valid?

**Comment by stblassitude** [comment]
That behavior is well hidden in the documentation :-) May I suggest that the man page is amended by a second usage line, just like the example at the bottom, to make it clear that check_http can perform two independent tests?

On the other hand, being able to combine both the regular test and the certificate lifetime in a single test would be OK as well. But I understand that that would break POLA.
