### ISSUE TITLE
Drop mirror.switch.ch from the list of mirror sites

### ISSUE THREAD

**Issue by thlengge** [monitoring-plugins/monitoring-plugins#1555]
I already sent this message twice as mail on 20. September and 27. September to admin@monitoring-plugins.org, but no action nor answer yet. So I try it on this channel.

------------
The SWITCHmirror service hosted on mirror.switch.ch will be decommissioned soon.

Could you please remove the entry for mirror.switch.ch, labeled 'Switzerland' from your list of mirror sites at https://www.monitoring-plugins.org/download.html and notify us once accomplished?

Thereafter, we will stop the mirroring of this package and drop it from our repository.

Many thanks and kind regards
switchmirror@switch.ch

PS: See http://mirror.switch.ch for details on the decommissioning.

**Comment by weiss** [comment]
Sorry about the missing email response.

> Could you please remove the entry for mirror.switch.ch, labeled 'Switzerland' from your list of mirror sites at https://www.monitoring-plugins.org/download.html and notify us once accomplished?

Done.

Many thanks for your service in the past.
