### ISSUE TITLE
check_http: Optionally return content

### ISSUE THREAD

**Issue by towolf** [monitoring-plugins/monitoring-plugins#1559]
When using check_http on an API with a healthz endpoint, this is basically useless:

![image](https://user-images.githubusercontent.com/345210/48279873-2db3a800-e452-11e8-9557-13209a745e3f.png)

I'd like to see the content that the HTTP request response is returning. It's actually stating that an API on the internet that it is using is down. So I can't do anything and can ignore this problem.

**Comment by towolf** [comment]
I know that I probably don't want to return long HTML page content, but a flag to also include the body text would be sweet and I can't really believe that this is not supported?

**Comment by towolf** [comment]
Here's another example:
```
./plugins/check_http -H lobby-api.example.com -u /health -S
HTTP OK: HTTP/1.1 200 OK - 746 bytes in 0,119 second response time |time=0,119410s;;;0,000000;10,000000 size=746B;;;0
{"status":"UP","database":{"status":"UP"},"migration":{"status":"UP"},"rabbitMQ":{"status":"UP"},"redis":{"status":"UP"}}
```

I will try to make a PR with an optional flag to return the content.

**Comment by towolf** [comment]
Thanks for merging.

Here's an example where this is useful, Gitlab:

Before
```
# /usr/lib/nagios/plugins/check_http -I 127.0.0.1 -S -u /-/liveness
HTTP OK: HTTP/1.1 200 OK - 654 bytes in 0,039 second response time |time=0,039068s;;;0,000000 size=654B;;;0
```
After
```
# ./check_http -I 127.0.0.1 -S -u /-/liveness -B
HTTP OK: HTTP/1.1 200 OK - 654 bytes in 0,039 second response time |time=0,039184s;;;0,000000;10,000000 size=654B;;;0
{"db_check":{"status":"ok"},"redis_check":{"status":"ok"},"cache_check":{"status":"ok"},"queues_check":{"status":"ok"},"shared_state_check":{"status":"ok"},"gitaly_check":{"status":"ok"}}
```

**Comment by towolf** [comment]
Now we just need a release ...

**Comment by rossnick** [comment]
Indeed ! This seem to never have been released
