### ISSUE TITLE
check_ntp_time high CPU usage when using time.google.com

### ISSUE THREAD

**Issue by nohn** [monitoring-plugins/monitoring-plugins#1568]
When using time.google.com as host, check_ntp_time uses an usual amount of sys time:

```$ time ./check_ntp_time -H time.google.com
NTP OK: Offset -0.003119975328 secs|offset=-0.003120s;60.000000;120.000000;

real    0m5.212s
user    0m0.580s
sys     0m4.305s
```

when using other hosts like for example ptbtime1.ptb.de, everything works as expected:

```$ time ./check_ntp_time -H ptbtime1.ptb.de
NTP OK: Offset -0.00247785449 secs|offset=-0.002478s;60.000000;120.000000;

real    0m0.093s
user    0m0.003s
sys     0m0.000s
```

strace output for both runs is attached: [check_ntp_time.logs.zip](https://github.com/monitoring-plugins/monitoring-plugins/files/2720186/check_ntp_time.logs.zip)

**Comment by sni** [comment]
The reason is simply, that ptbtime1.ptb.de resolves to a single ip address while time.google.com resolves to multiple ip addresses and check_ntp_time checks all of them.
