### ISSUE TITLE
check_http takes very long (2.2.1)

### ISSUE THREAD

**Issue by jalbstmeijer** [monitoring-plugins/monitoring-plugins#1590]
Hi,

Since the beginning of march a check to instagram started timing out, just taking a bit longer than the default timeout. Any idea why?

Both curl and wget don't seem to have an issue;

check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 32645 bytes in 10.538 second response time |time=10.538104s;;;0.000000 size=32645B;;;0

check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 32811 bytes in 10.551 second response time |time=10.551390s;;;0.000000 size=32811B;;;0

check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 32693 bytes in 10.542 second response time |time=10.541755s;;;0.000000 size=32693B;;;0

time wget -q  -4 https://www.instagram.com -O /dev/null
real	0m0.257s

wget -q  -4 https://www.instagram.com -O /dev/null
real	0m0.244s

time wget -q  -4 https://www.instagram.com -O /dev/null
real	0m0.238s

time curl -4 https://www.instagram.com > /dev/null
reaal	0m0.390s

time curl -4 https://www.instagram.com > /dev/null
real	0m0.834s

time curl -4 https://www.instagram.com > /dev/null
real	0m0.335s

Gr, J

**Comment by waja** [comment]
Please post the output of `check_http -V`

**Comment by jalbstmeijer** [comment]
As stated in the subject. version 2.2.1

> check_http -V                      
check_http v2.2.1 (nagios-plugins 2.2.1)

**Comment by jalbstmeijer** [comment]
maybe related to? https://github.com/monitoring-plugins/monitoring-plugins/issues/1549

**Comment by waja** [comment]
> check_http v2.2.1 (nagios-plugins 2.2.1)

This is not our plugin and we can't say anything about forked code basis, but you created nagios-plugins/nagios-plugins/issues/444, which should address your problem.

**Comment by waja** [comment]
Anyway ... we seems also affected:

```
$ /usr/lib/nagios/plugins/check_http -t 30 -4 -H www.instagram.com -u / -S -v
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.2 (monitoring-plugins 2.2)
Connection: close
Host: www.instagram.com


https://www.instagram.com:443/ is 32720 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Content-Type: text/html; charset=utf-8
Vary: Accept-Language, Cookie, Accept-Encoding
Content-Language: en
Date: Wed, 03 Apr 2019 14:07:58 GMT
Strict-Transport-Security: max-age=31536000
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 1
Connection: close
Content-Length: 30920
**** CONTENT ****
<!DOCTYPE html>
[...]
</html>

HTTP OK: HTTP/1.1 200 OK - 32720 bytes in 10,338 second response time |time=10,338428s;;;0,000000;30,000000 size=32720B;;;0
```

**Comment by reubenfarrelly** [comment]
I'm seeing this issue also with [check_http v2.2 (monitoring-plugins 2.2)] although sometimes needs far more than 10s.  I have however pinpointed it down to the fact that it all started when I upgraded from Linux Kernel 4.20 to 5.0 on the system that is running check_http.  All 4.20.x builds are OK, and all 5.0.x are currently affected.  I've tested backwards and forwards between kernels a number of times.
It also only happens once out of every 5 or 6 times the plugin runs, however if I run it in quick succession I can always observe the problem after a few attempts.
I would be most interested to know if this matches the experience of others.  It only appears to be a problem with this specific application and this specific plugin on these newest kernels.

**Comment by waja** [comment]
I can reproduce that on kernel 4.9.144-3.1.

**Comment by jalbstmeijer** [comment]
I cannot confirm it is kernel version related. Myself running latest RedHat 6 kernel.
I'm monitoring dozens of urls with check_http, only the check to instagram is failing this way.

My guess is that instagram has set a 10 seconds timeout for clients that don't close the connection themselves,  https://github.com/monitoring-plugins/monitoring-plugins/issues/1549

**Comment by RincewindsHat** [comment]
Can not reproduce on current master and debian 12. Maybe Insta changed something with the site. Can anyone still experience this problem?

**Comment by andreasbaumann** [comment]
Looks fine to me:

```
./check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 71237 bytes in 0.484 second response time |time=0.483732s;;;0.000000;30.000000 size=71237B;;;0;
./check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 71237 bytes in 0.302 second response time |time=0.301588s;;;0.000000;30.000000 size=71237B;;;0;
./check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 71237 bytes in 0.278 second response time |time=0.277780s;;;0.000000;30.000000 size=71237B;;;0;
```

**Comment by RincewindsHat** [comment]
Closing this, for the purpose of tidying up a little bit. Please reopen, if the problem still persists.
