### ISSUE TITLE
SELinux error after update on RHEL6

### ISSUE THREAD

**Issue by ubellavance** [monitoring-plugins/monitoring-plugins#1594]
Hi,

We had nagios-plugins-ntp-2.2.1-4git.el6 packages on our RHEL6 server and after we updated to the latest version available in EPEL (nagios-plugins-ntp-2.2.1-15.20180725git3429dad.el6), we started having these SELinux denials:

``avc:  denied  { execute } for  pid=24170 comm="check_ntp" name="ntpdate" dev=dm-0 ino=391810 scontext=system_u:system_r:nagios_services_plugin_t:s0 tcontext=system_u:object_r:ntpdate_exec_t:s0 tclass=file``

Here's the SELinux contexts for the files:

Before the update:
```
[ubellavance@server ~]$ ll -Z /usr/sbin/ntpdate
-rwxr-xr-x. root root system_u:object_r:ntpdate_exec_t:s0 /usr/sbin/ntpdate

[ubellavance@server ~]$ ll -Z /usr/lib64/nagios/plugins/check_ntp
-rwxr-xr-x. root root system_u:object_r:nagios_services_plugin_exec_t:s0 /usr/lib64/nagios/plugins/check_ntp
```

After the update:
```
[ubellavance@server ~]# ll -Z /usr/sbin/ntpdate
-rwxr-xr-x. root root system_u:object_r:ntpdate_exec_t:s0 /usr/sbin/ntpdate

[ubellavance@server ~]# ll -Z /usr/lib64/nagios/plugins/check_ntp
-rwxr-xr-x. root root system_u:object_r:nagios_services_plugin_exec_t:s0 /usr/lib64/nagios/plugins/check_ntp
```

I don't know exactly what to do from here. I tried downgrading the nagios-plugins-ntp package but it's not supported.

**Comment by ubellavance** [comment]
Oh and the selinux-policy has not been updated.

**Comment by waja** [comment]
Anyway ... we are not building this package and are also not https://github.com/nagios-plugins/nagios-plugins

**Comment by ubellavance** [comment]
Sorry, still confused between monitoring-plugins and nagios-plugins.  Will open a ticket on Red Hat bugzilla (packagers) and on nagios-plugins github repo.

Thanks for your quick answer.

**Comment by ubellavance** [comment]
I have made more analysis and it looks like a packaging bug: https://bugzilla.redhat.com/show_bug.cgi?id=1710544

(It looks like someone used the contents of check_ntp.pl for check_ntp)
