### ISSUE TITLE
check_disk: ignores inode thresholds after -A

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1596]
In Debian we got the following [bug](http://bugs.debian.org/928752) reported:

when speciying inode threshold after -A (--all) they are ignored.

Testing with a near out of inodes disk:

	df -i /
	Filesystem Inodes   IUsed IFree IUse% Mounted on
	....root  2510032 2503586  6446  100% /

Passing -A before inode settings, but after block settings leads to OK:

	/usr/lib/nagios/plugins/check_disk -w 10% -c 5% -A -W 10% -K 5%
	DISK OK - free space: ... / 25612 MB (70% inode=0%);

Moving -A to the end leads to the expected CRITICAL:

	/usr/lib/nagios/plugins/check_disk -w 10% -c 5% -W 10% -K 5% -A
	DISK CRITICAL - free space: ... / 25612 MB (70% inode=0%);

FWIW there seems to be some checking wrt -A position:

	/usr/lib/nagios/plugins/check_disk -A -w 10% -c 5% -W 10% -K 5%
	DISK UNKNOWN: Must set a threshold value before using -r/-R

**Comment by RincewindsHat** [comment]
That is indeed still the case.

**Comment by RincewindsHat** [comment]
I fear this is kinda intentional. Part of that weird grouping/selecting stuff in `check_disk`.
I would love to remove that, but it could break some setups on the way.

**Comment by RincewindsHat** [comment]
@waja any opinion on that?

**Comment by waja** [comment]
I would say, when we can not change the behaviour, we should clearly document, what the users needs to do to use it correctly.
