### ISSUE TITLE
check_file_age: OK result though file is 0 bytes 

### ISSUE THREAD

**Issue by wopfel** [monitoring-plugins/monitoring-plugins#1604]
Hi,
I've experienced that an empty file doesn't trigger a critical state. According to the help text an empty file should by default result to crit, shouldn't it?

`<size>  File must be at least this many bytes long (default: crit 0 bytes)`

I'm unsure how this can be fixed, since the description states "must be at least this many bytes". Since the default is 0, it is true - the file is at least 0 bytes long, which returns an OK state.

If the check would be changed to _greater than_, then the description (_at least_) doesn't fit any longer.

I'm running the latest version 2.2 in Arch Linux. I've double-check using latest Ubuntu docker container image (hopefully they have the latest release of monitoring-plugins in their repositories):

```
root@58617f44a0df:/# apt update
(...)
root@58617f44a0df:/# apt install monitoring-plugins
(...)
root@58617f44a0df:/# /usr/lib/nagios/plugins/check_file_age --version
check_file_age v2.2 (monitoring-plugins 2.2)
The Monitoring Plugins come with ABSOLUTELY NO WARRANTY. You may redistribute
copies of the plugins under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
root@58617f44a0df:/# pwd
/
root@58617f44a0df:/# touch empty-file
root@58617f44a0df:/# /usr/lib/nagios/plugins/check_file_age -f /empty-file
FILE_AGE OK: /empty-file is 11 seconds old and 0 bytes | age=11s;240;600 size=0B;0;0;0
root@58617f44a0df:/# ls -l /empty-file
-rw-r--r-- 1 root root 0 Aug 31 15:51 /empty-file
```

(I'm not using a range specification here)

Kind regards,
Bernd

**Comment by sni** [comment]
I guess you need to use ranges then, supported since 98a365d76c9b7e270d7b00953905d80c80c1467d.  Not sure if that is possible with the 2.2 already.

**Comment by RincewindsHat** [comment]
I would interpret this as "working as intented", since I would expect to plugin to ignore the size if I don't specify one.

**Comment by wopfel** [comment]
Thanks for the feedback. Should we change the help text, then? So it says a 0-byte file is okay, rather that critical?

**Comment by odenbach** [comment]
Size is not important if not explicitly requested. So please do not change the current behaviour. The documentation could be made more clear about this, right.

0-byte files are perfectly normal if you look at e.g. time stamp files for synching an archive.

**Comment by RincewindsHat** [comment]
#1730
