### ISSUE TITLE
check_disk : resume show 0Mb, perfomance data is right with GlusterFS Mount

### ISSUE THREAD

**Issue by guldil** [monitoring-plugins/monitoring-plugins#1612]
Hy,

With icinga2 monitoring, check_disk show wrong information on web server with GlusterFS mount :

```
root@xxx-xx-webfarm02:/usr/lib/nagios/plugins# ./check_disk  -w 80 -c 90

DISK CRITICAL - free space: /dev 978 MB (100% inode=99%); /run 194 MB (97% inode=99%); / 8992 MB (65% inode=72%); /dev/shm 999 MB (100% inode=99%); /run/lock 5 MB (100% inode=99%); /sys/fs/cgroup 999 MB (100% inode=99%); /boot 379 MB (84% inode=99%); /mnt/glusterfs-mount1 0 MB (0% inode=99%); /mnt/glusterfs-mount2 0 MB (0% inode=99%); /run/user/0 200 MB (100% inode=99%);| /dev=0MB;898;888;0;978 /run=5MB;120;110;0;200 /=4754MB;14426;14416;0;14506 /dev/shm=0MB;919;909;0;999 /run/lock=0MB;-75;-85;0;5 /sys/fs/cgroup=0MB;919;909;0;999 /boot=67MB;391;381;0;471 /mnt/glusterfs-mount1=294343MB;409506;409496;0;409586 /mnt/glusterfs-mount2=294343MB;409506;409496;0;409586 /run/user/0=0MB;120;110;0;200
```

df command on same server show right information : 

`root@xxx-xx-webfarm02:~# df -h`
`Sys. de fichiers                   Taille Utilisé Dispo Uti% Monté sur`
`udev                                 979M       0  979M   0% /dev`
`tmpfs                                200M    5,8M  195M   3% /run`
`/dev/mapper/ubuntu19--vg-root         15G    4,7G  8,8G  35% /`
`tmpfs                               1000M       0 1000M   0% /dev/shm`
`tmpfs                                5,0M       0  5,0M   0% /run/lock`
`tmpfs                               1000M       0 1000M   0% /sys/fs/cgroup`
`/dev/sda1                            472M     68M  380M  16% /boot`
`xxx-xx-gluster01:/mount1          400G    288G  117G  72% /mnt/glusterfs-mount1`
`xxx-xx-gluster02:/mount2            400G    288G  117G  72% /mnt/glusterfs-mount2`
`tmpfs                                200M       0  200M   0% /run/user/0`

look like problem is here : 

`/mnt/glusterfs-mount1 0 MB (0% inode=99%); /mnt/glusterfs-mount2 0 MB (0% inode=99%)`

what is really strange, the performance data are  ok  :

`471 /mnt/glusterfs-mount1=294343MB;409506;409496;0;409586 /mnt/glusterfs-mount2=294343MB`

![pb-check_disk-gluster](https://user-images.githubusercontent.com/5718040/69916658-f4cfe200-145d-11ea-8322-cd50fccaa816.png)

but : 

![pb-check_disk-gluster-2](https://user-images.githubusercontent.com/5718040/69916696-817aa000-145e-11ea-9a82-1aee7da1b819.png)

Server is Ubuntu 16.04 with GlusterFS 3.13

What can i do ?

Guldil

**Comment by RincewindsHat** [comment]
Hi @guldil,
Sorry to answer this late. Could you test that with the current master and verify that this problem still exists?

**Comment by RincewindsHat** [comment]
ok, just build a small test setup and I can not reproduce the problem. Looks alright to me.
I am going to close this issue, please reopen it, if you think the problem still persists.
