### ISSUE TITLE
check_disk: Permission denied

### ISSUE THREAD

**Issue by protist** [monitoring-plugins/monitoring-plugins#1622]
I initially asked at the [Nagios forums](https://support.nagios.com/forum/viewtopic.php?f=7&t=57301), but they refused to support monitoring-plugins.

I'm running an Arch Linux server with the latest [Nagios](https://aur.archlinux.org/packages/nagios/) and [monitoring-plugins](https://www.archlinux.org/packages/community/x86_64/monitoring-plugins/). I've added a command to check the disk space for my hard drives. I edited `/etc/nagios/objects/localhost.cfg` and added the following:

    define command{
        command_name check_hard_disks
        command_line /usr/lib/monitoring-plugins/check_disk -w '$ARG1$' -c '$ARG2$' -e -r '^/media/.*' --exclude-type=tracefs --exclude-type=cgroup
    }

    define service{
            use                             generic-service         ; Name of service template to use
            host_name                       localhost
            service_description             Disk Space for Hard disks
            check_command                   check_hard_disks!204800!102400
    }

However, I'm getting the following error in the GUI

    DISK CRITICAL - /media/Morlock is not accessible: Permission denied

Nagios is in the correct group with the correct permissions, and the command seems to work when I run it manually

    $ ls -ld /media/Morlock
    drwxr-x--- 5 pi media 4096 Jul 27  2019 /media/Morlock
    $ sudo runuser -u nagios -- groups
    nagios media
    $ sudo runuser -u nagios -- /usr/lib/monitoring-plugins/check_disk -w '204800' -c '102400' -e -r '^/media/.*' --exclude-type=tracefs --exclude-type=cgroup
    DISK OK| /media/Morlock=1480562MB;2610828;2713228;0;2815628 /media/PiBuHDD=3496481MB;3549720;3652120;0;3754520 /media/PiHDD=1832964MB;2561328;2663728;0;2766128 /media/PiHDD2=2818985MB;5472216;5574616;0;5677016

In the original post, it was suggested to make `nagios` a login user, i.e. in `/etc/passwd`, I changed

    nagios:x:30:30::/dev/null:/bin/false

to

    nagios:x:30:30::/home/nagios:/bin/bash

and created `/home/nagios`, but this didn't work, i.e. nagios still fails with permission errors, and the `nagios` user can still run the command fine manually.
```
$ sudo su nagios
[nagios@alarmpi ~]$ /usr/lib/monitoring-plugins/check_disk -w '204800' -c '102400' -e -r '^/media/.*' --exclude-type=tracefs --exclude-type=cgroup
DISK OK| /media/Morlock=1478022MB;2610828;2713228;0;2815628 /media/PiBuHDD=3518556MB;3549720;3652120;0;3754520 /media/PiHDD=1846916MB;2561328;2663728;0;2766128 /media/PiHDD2=2831097MB;5472216;5574616;0;5677016
[nagios@alarmpi pi]$ cd
[nagios@alarmpi ~]$ pwd
/home/nagios
[nagios@alarmpi ~]$ ls -Al
total 0
```

**Comment by ghciv6** [comment]
is your arch linux server running with active selinux policies? You can check this with "getenforce".

**Comment by protist** [comment]
Thanks @ghciv6. I don't have selinux (nor apparmor) installed. I'm running Arch ARM, and neither is enabled by default.

To confirm, I tried running `sestatus`, `getenforce`, `aa-enabled`, and `apparmor_status`, but none of those commands were found.

**Comment by ghciv6** [comment]
The stat() system call returns that error. Some kind of mechanism is blocking the call or the environment differs from your environment in the shell.
 
You can start your own plugin through the nagios process to check if the environment matches your assertions:
```
#!/bin/sh
/usr/bin/id
/usr/bin/stat /media/Morlock
exit 0
```

**Comment by protist** [comment]
Interesting! When running the command manually, it works as expected.
```
$ sudo runuser -u nagios -- /usr/local/bin/test_nagios
uid=30(nagios) gid=30(nagios) groups=30(nagios),1050(media)
  File: /media/Morlock
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 811h/2065d	Inode: 2           Links: 5
Access: (0700/drwx------)  Uid: ( 1000/      pi)   Gid: ( 1050/   media)
Access: 2019-07-30 20:03:21.242711181 +1000
Modify: 2019-07-27 17:16:41.732449096 +1000
Change: 2020-03-19 10:00:01.505745326 +1100
 Birth: 2019-07-26 19:57:00.000000000 +1000
```
However, when I run the job through Nagios, I only get the following single line as "Status Information" in the web GUI.
```
uid=30(nagios) gid=30(nagios) groups=30(nagios)
```
So here it looks like the `nagios` user isn't in the `media` group for some reason, and  `stat` fails.

**Comment by ghciv6** [comment]
Looks like the calling program is stripping out supplemenentary groups for security or performance reasons. And you are restricting filesystem access...

You have two options:
1. allow read-only access to the mountpoint for "other/world":
`chmod o+r /media/Morlock`

2. If the filesystem /media/Morlock supports extended attributes, you can allow the nagios group to access it too:
`setfacl -m g:tcpdump:r-- /media/Morlock `

**Comment by protist** [comment]
Thanks again @ghciv6. I tested both options, restarted nagios, but neither worked! In both cases the `stat` test was still empty, and the `check_disk` command failed as per the first post.
```
$ ls -ld /media/Morlock
drwxr--r--+ 5 pi media 4096 Jul 27  2019 /media/Morlock
$ getfacl /media/Morlock
getfacl: Removing leading '/' from absolute path names
# file: media/Morlock
# owner: pi
# group: media
user::rwx
group::---
group:nagios:r--
mask::r--
other::r--
```
I also tried restarting just in case, but they still failed.

What's weird is that I also tried messing around with the primary gid of the nagios user, just for the sake of troubleshooting. I thought that this should surely work. Originally, it was
```
$ sudo runuser -u nagios -- id
uid=30(nagios) gid=30(nagios) groups=30(nagios),1050(media)
```
So I modified the gid to
```
sudo runuser -u nagios -- id
uid=30(nagios) gid=1050(media) groups=1050(media),30(nagios)
```
Then restarted. However, even now nagios is still failing as above. In the test you suggested, the reported `gid` is still `30(nagios)`??? It looks like somehow this information is stored somewhere else, and presumably never updated.

**Comment by ghciv6** [comment]
i've done some tests here. you need r-x permissions on the **parent directory** and no permissions for the stat() directory.
 
try:
`setfacl -m g:nagios:r-x /media`

**Comment by protist** [comment]
Brilliant. That works. Thank you again. I wasn't exactly sure what you meant by "no permissions", but I also had to give `r--` to the subdirectory too.

In terms of buggy behaviour, would you consider the fact that nagios ignores secondary gid an upstream bug? i.e. should I file a bug there? I'm not sure it this issue is constrained by the system though, so I don't know if it's fixable in the nagios code.

**Comment by ghciv6** [comment]
you can ask in the nagios forum if they know this behaviour. might be they have an option to initialize supplementary group id's too.

i don't think this is a plugin issue. so i suggest to close this isse.

**Comment by protist** [comment]
Yes, I agree. Thank you for all your help @ghciv6!
