### ISSUE TITLE
Docs on monitoring-plugins.org seem to reflect git master, not latest release

### ISSUE THREAD

**Issue by mbra** [monitoring-plugins/monitoring-plugins#1625]
Hey,

I have noticed that the documentation/--help output on monitoring-plugins.org seems to reflect the state of the git master branch instead of the latest release.

For example I was very interested in the "--show-body" Version of check_http, which I can find quite easily via a simple search for "check_http show body".

I only googled this because I did not see anything useful in the `--help` output myself and immediately thought I must have overlooked that option; turns out I did not and I just can't have that option because it is not really released yet. :-/

Yes, it says "check_http v2.2.git" right in the first line of the help output, but I think it is a little too subtle. I think it is not unreasonable to assume that most people to not really start from the top *including* the copyright header and all. At least it did not prevent the "Yay, I overlooked something and there is a solution after all" happiness and the sadness that followed when I found out it was not quite as simple after all. :-(

I would really appreciate if it could be made more clear that I am not viewing the docs of the latest release or if the latest released version could be used to generate the documentation.

Also, are there any plans for a 2.3 release any time soon? I would very much like to avoid packaging a private pseudo version of the package but if there are no plans I would probably have to at least consider it.

**Comment by RincewindsHat** [comment]
Hi,
did the 2.3 release fix your problem?

**Comment by RincewindsHat** [comment]
Closing this for now, pls reopen if the problem persists :-)
