### ISSUE TITLE
check_cluster with nagios macro

### ISSUE THREAD

**Issue by BasteFw** [monitoring-plugins/monitoring-plugins#1626]
Hello
I have a problem with check_cluster.
With version 2.2:
/ check_cluster -d $ SERVICESTATEID: host1: Check_MK $
CLUSTER OK: Cluster service: 1 ok, 0 warning, 0 unknown, 0 critical

with the latest snapshot version:
check_cluster -d $ SERVICESTATEID: host1: Check_MK $
Could not parse arguments

check_cluster no longer take nagios macros?

Thank you

**Comment by RincewindsHat** [comment]
Hi @BasteFw , sorry for the late response. Don't know much about nagios, but did this ever work? I would guess, nagios filled in those values, not the plugin.

**Comment by RincewindsHat** [comment]
Closing this, for the purpose of tidying up a little bit. Please reopen, if the problem still persists.
