### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by plivnik** [monitoring-plugins/monitoring-plugins#1635]
Trying to compile monitoring-plugin2.2 on openSUSE Leap 15.1.
During make I have got
check_mysql.c:61:24: error: ‘MYSQL_PORT’ undeclared here (not in a function); did you mean ‘MYSQL_STMT’?
 unsigned int db_port = MYSQL_PORT;
                        ^~~~~~~~~~
                        MYSQL_STMT
make[2]: *** [Makefile:1869: check_mysql-check_mysql.o] Error 1

How to correct this problem, please?
Thanks
Mike

**Comment by ghciv6** [comment]
a MYSQL_PORT issue is fixed since Nov 2017:
https://github.com/monitoring-plugins/monitoring-plugins/commit/399cc141526ee77e1befce469f1fab40645f299d
