### ISSUE TITLE
check_tcp: Add possibity to check the whole SSL certificate chain for expiry

### ISSUE THREAD

**Issue by martinseener** [monitoring-plugins/monitoring-plugins#1636]
Currently it is not possible to check the whole certificate chain of a TLS-enabled service for expiration but only the site certificate.
It would be nice to have a parameter to enable full-chain checks if a certificate in there is about to expire. See recent issue: https://www.ssl.com/blogs/addtrust-external-ca-root-expired-may-30-2020/

I haven't found this feature neither for check_tcp nor check_http but I would suggest to add this feature to check_tcp because a service may not speak http but smtp where this feature would also be helpful.

**Comment by lazyfrosch** [comment]
Have a look a https://github.com/matteocorti/check_ssl_cert

Most plugins here do not check trust, but merely the expiration of the direct certificate.

**Comment by martinseener** [comment]
It's not about checking trust but rather checking the certificate chain, the server sents to the client if any certificate in the chain is expiring by itself.
Let's say a server sends back
1. its site certificate
2. the intermediate that signed 1.

the client has the CA and can check trust. But what i want to check is that 1. AND 2. certificates are checked for their expire date.

**Comment by lazyfrosch** [comment]
I know what you want to test, check_ssl_cert does not validate this now with the latest changes.

My point is that plugins are here are meant to check the protocol itself, and there are better plugins for validating certificates.

**Comment by ckujau** [comment]
There's [check-cert-expire](https://salsa.debian.org/nagios-team/pkg-nagios-plugins-contrib/-/blob/master/dsa/checks/dsa-check-cert-expire) and [check-cert-expire-dir](https://salsa.debian.org/nagios-team/pkg-nagios-plugins-contrib/-/blob/master/dsa/checks/dsa-check-cert-expire-dir) that can be used to check the expiration date of (local) trust stores. Combined with `check_ssl_cert` these could be used to check the entire chain.

Also, during the recent AddTrust debacle I learned that [gnutls-cli](https://gnutls.org/manual/html_node/gnutls_002dcli-Invocation.html) *did* check the entire chain and would fail where `openssl` (and tools linked to it) would succeed.

**Comment by martinseener** [comment]
Okay understood. I only thought that, if check_tcp provides the possibility to check the certificate with `-D`, why not adding possibility to extend the check to the whole chain sent back from the server. But if it's out of scope for you for this plugin, you can close this issue.
Thanks for the other checks links 👍  Will build another solution then!
