### ISSUE TITLE
check_http: expect success result code

### ISSUE THREAD

**Issue by mpounsett** [monitoring-plugins/monitoring-plugins#1639]
check_http doesn't seem to have a way to return WARNING or CRITICAL results if it gets a non-success HTTP result code.  It would be very useful if there was a way to set it to be OK only if there is a 2xx result.

**Comment by sni** [comment]
the -e option can be used to make check_http expect a specific (or multiple) status codes. If set, it will return either OK or CRITICAL.

**Comment by mpounsett** [comment]
Thanks .. for some reason that wasn't clear to me when I read the help page.  I did some more digging and managed to find an example of making that work.
