### ISSUE TITLE
check_pgsql: check of database name is too strict

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1660]
In Debian we got the following [bug](http://bugs.debian.org/982847) reported:

Hi *,
to reproduce create a Database called freshports.git and try to
use it with `check_pgsql`:

```
flo@p5:/tmp/monitoring-plugins-2.3$ /usr/lib/nagios/plugins/check_pgsql -d freshports.devgit -l flo
check_pgsql: Database name is not valid - freshports.devgit
Usage:
check_pgsql [-H <host>] [-P <port>] [-c <critical time>] [-w <warning time>]
 [-t <timeout>] [-d <database>] [-l <logname>] [-p <password>]
[-q <query>] [-C <critical query range>] [-W <warning query range>]
```
```
flo@p5:/tmp/monitoring-plugins-2.3$ psql freshports.devgit
psql (13.1 (Debian 13.1-1+b1))
Type "help" for help.

freshports.devgit=# \d
Did not find any relations.
freshports.devgit=# 
```

The problem is that `check_pgsql` validates the Database name and has different assumptions
that postgres itself.

I fail to see a reason to validate the database name here. Postgres'es API should
do this - So i would suggest a fix like this by removing `is_pg_dbname` alltogether.

**Comment by waja** [comment]
closed by dae075e

**Comment by louislepage** [comment]
Hi,

if I am not mistaken, it seems like the actual fix never made it into the master and the current release.
Only the commit about `sprintf` made it.
The PR #1662 was closed without merging the fixes.

Is there any reason for this? 
The proposed solutions seems solid to to me.

Cheers,
Louis

**Comment by waja** [comment]
okay ... I created #1803 for this ...
