### ISSUE TITLE
Fix release notes for 2.3.1

### ISSUE THREAD

**Issue by glensc** [monitoring-plugins/monitoring-plugins#1673]
The URL in the release note is not clickable:
- https://github.com/monitoring-plugins/monitoring-plugins/releases/tag/v2.3.1

cc @waja

**Comment by waja** [comment]
Hi @glensc 

> The URL in the release note is not clickable:

Seems like Markdown is not possible there ... Did I miss something?

**Comment by glensc** [comment]
Yes, remove the left space padding. 4 spaces starts a code block.

**Comment by waja** [comment]
@glensc many thanks!
