### ISSUE TITLE
Is it possible to install a particular plugin when we install from source ?

### ISSUE THREAD

**Issue by jason354007** [monitoring-plugins/monitoring-plugins#1675]
For example, I want to install  just check_http.
How to just install check_http and not all the other plugins ?

**Comment by jason354007** [comment]
Thanks @odenbach for the tip. The "compile everything and then copy check_http" works fine.
How to just compile check_http ?

**Comment by sni** [comment]
it won't save you much time, but you can change into the source/plugins folder and run `make check_http`

**Comment by jason354007** [comment]
Thanks. You're right. It doesn't save much time.
