### ISSUE TITLE
check_curl: `-f follow` not working

### ISSUE THREAD

**Issue by jacobbaungard** [monitoring-plugins/monitoring-plugins#1685]
It appears that the `-f follow` flag is not working correctly in check_curl. `-f curl` seems to work OK.

```
./check_curl -H www.mozilla.com -u /firefox -f follow
Output:  HTTP WARNING - maximum redirection depth 15 exceeded 
```

`check_http` also returns OK on the above.

**Comment by andreasbaumann** [comment]
I would actually rather make it two tests, one for '-f follow' and one for '-f curl'.

And the '-f follow' case is interesting to fix maybe, I see:

```
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/firefox
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
< HTTP/1.1 308 Permanent Redirect
< Location: https://www.mozilla.com/
< HTTP/2 301 
< location: https://www.mozilla.org/firefox
```

**Comment by jacobbaungard** [comment]
I agree, once `-f follow` is working well, we should add another test. For now I just removed it from the github actions branch because it seems not to work in most cases.

I tried a few more examples, one worked one failed:

`./check_curl -H op5.com -f follow` works OK
`./check_curl -H www.github.com -f follow` fails

**Comment by waja** [comment]
@andreasbaumann how do we want to deal with this issue?

**Comment by andreasbaumann** [comment]
Ok, the problem is in picohttpparser, phr_parse_response cannot handle the HTTP/2 response:

```
HTTP/2 301 
content-length: 0
location: https://github.com/
```
effectively returning illegal values for redirection:

```
* Seen redirect location (null)
** scheme: (null)
** host: (null)
** port: (null)
```

**Comment by andreasbaumann** [comment]
I can't believe it, but just parsing the major HTTP version seems to have done the trick. :-)
