### ISSUE TITLE
check_ntp_time - optionally return UNKNOWN on uncontactable NTP server

### ISSUE THREAD

**Issue by willfurnell** [monitoring-plugins/monitoring-plugins#1701]
Hello,

If the NTP server goes down, we do not want all our hosts to raise a CRITICAL alert when using check_ntp_time about the server being uncontactable/there being no response from the NTP server. We would just want one CRITICAL alert from the NTP server itself in a seperate check.

Would it be possible to change this to UNKNOWN, or make it configurable to UNKNOWN please?
I've found the line that sets this here: https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins/check_ntp_time.c#L420

Thanks,
Will.

**Comment by RincewindsHat** [comment]
Hi @willfurnell , sorry for the delay. Could you turn this into a Pull Request?

**Comment by weiss** [comment]
> If the NTP server goes down, we do not want all our hosts to raise a CRITICAL alert when using check_ntp_time about the server being uncontactable/there being no response from the NTP server.

Should this be handled by defining appropriate service dependencies in the monitoring application?

**Comment by waja** [comment]
> Shouldn't this be handled by defining appropriate service dependencies in the monitoring application?

second that
