### ISSUE TITLE
check_curl - get xml content behind proxy

### ISSUE THREAD

**Issue by winter1967** [monitoring-plugins/monitoring-plugins#1720]
Hello,
i tried to use check_curl to get an xml content behind proxy:
`'/usr/lib64/nagios/plugins_contrib/check_curl' '-H' 'geodaten.metropoleruhr.de' '-I' 'proxyip' '-S' '-l' '-p' 'proxyport' '-u' 'https://geodaten.metropoleruhr.de/spw2?SERVICE=WMS&REQUEST=GetCapabilities' '-v' 'true'
`
I get an "OK", but no content.

When i use curl with '-k' option i can get my file behind the proxy:
`curl -x proxip:proxyport -k 'https://geodaten.metropoleruhr.de/spw2?SERVICE=WMS&REQUEST=GetCapabilities' -v`

I get the content i want to get ;-)

It would be a nice feature to implement the  ignore certificate option (-k) from curl?

Or it's a wrong usage by me?

**Comment by andreasbaumann** [comment]
- `-v` is just -v, no `-v true`
- `-B` shows the body, `./check_curl -v -H geodaten.metropoleruhr.de -I geodaten.metropoleruhr.de -S -u '/spw2?SERVICE=WMS&REQUEST=GetCapabilities' -B` works fine for me
- ignoring certificate options is possible, but the `-k` option is taken by `-k, --header=STRING`. In principle nothing speaks against adding a `--ignore-certificate-checks` option
- I fail to see why I have to use a proxy to access the data, It works for me just fine without the proxy (maybe you are required to use a proxy at your place?)

**Comment by winter1967** [comment]
Hi, 
thank you very much, -B works for me fine, i haven't try it ;-)
We've very strong security admins, so for us, we've sometimes, when we monitor components 'outside' we have to use proxies; i know, direct connection have no problem (there.. check_http works, too)

**Comment by RincewindsHat** [comment]
I guess a `--ignore-certificate-checks` would be good to have (as it is always where TLS is in place). In the mean time you could use the root certificate to verify the connection via `--ca-cert`
