### ISSUE TITLE
check_icmp: fails with 'Socket operation on non-socket' when source IP is specified

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1734]
Hi,

in Debian we got the following [bugreport](https://bugs.debian.org/997849):

After upgrade to Debian 11 (bullseye) check_icmp option to specify IP source address stopped working.

```
# /usr/lib/nagios/plugins/check_icmp -H 8.8.8.8
OK - 8.8.8.8: rta 0,643ms, lost 0%|rta=0,643ms;200,000;500,000;0; pl=0%;40;80;; rtmax=0,773ms;;;; rtmin=0,395ms;;;;

/usr/lib/nagios/plugins/check_icmp -H 8.8.8.8 -s [correct_source_ip_address_here]
check_icmp: Cannot bind to IP address 91.202.124.36: Socket operation on non-socket
```

check_icmp capabilities are correctly set:

```
# getcap /usr/lib/nagios/plugins/check_icmp
/usr/lib/nagios/plugins/check_icmp cap_net_raw=ep
```

Before upgrade to Debian 11 everything was working perfectly correct.

The problem indeed exists also on Debian 10 and monitoring-plugins 2.3.1 and even on Debian 9 with monitoring-plugins 2.3. Debian 10 ships with monitoring-plugin 2.2. So the issue seems to be introduced later than monitoring-plugin 2.2 but exist since 2.3 reproducible.

**Comment by RincewindsHat** [comment]
hm, if I understand the code correctly, this can possibly work. Using `-s` will trigger a call to `bind` in the function `set_source_ip` (line 545 in the option parser).
The `bind` uses `icmp_sock`, a global variable wich will be filled in line 596.

**Comment by waja** [comment]
As guessed, (on Debian 10) with version 2.2 it works like intended here.

**Comment by ghciv6** [comment]
set_source_ip() uses the uninitialized variable icmp_sock. it's initialized later when address_family was detected based on target addresses. this was the change from 2.2 to 2.3.

are you working on this or should i try to write a fix?
