### ISSUE TITLE
Update check_http

### ISSUE THREAD

**Issue by helmi1987** [monitoring-plugins/monitoring-plugins#1761]
is it possible to update the code from check_http with the function from nagios-plugins?

https://nagios-plugins.org/doc/man/check_http.html (--continue-after-certificate)

thanks

**Comment by andreasbaumann** [comment]
` ./check_http --continue-after-certificate -C 100,200 -I openssl.org -u /` of nagios-plugins returns:

```
SSL CRITICAL - Certificate 'mta.openssl.org' expires in 59 day(s) (2022-06-08 19:48 +0200/CEST).
HTTP CRITICAL: HTTP/1.1 200 OK - 434 bytes in 0.237 second response time |time=0.236846s;;;0.000000 size=434B;;;0 
```

Is this good? And the option should also be added to `check_curl`..

**Comment by helmi1987** [comment]
Helo @andreasbaumann 

it looks good. I will make a check this afternon

**Comment by helmi1987** [comment]
I habe test it on icinga2 docker

`apt update
apt upgrade
apt install git automake autoconf gettext gcc

#make new directory
git clone https://github.com/monitoring-plugins/monitoring-plugins.git
cd monitoring-plugins
./tools/setup
./configure -prefix=/user/local --with-cgiurl=/usr/lib/nagios/custom-plugins/test/plugins --with-openssl=/usr/bin/openssl 
make
make install
make install-root`

after this steps was it all work.

when will this new release is in the apt package monitoring-plugins?

**Comment by helmi1987** [comment]
Any Update here?

thanks helmi1987

**Comment by RincewindsHat** [comment]
@helmi1987 I guess we have to make a release here and then the Debian maintainers have to decide, if they want to include that.
I hope we manage to get a working release soon.
