### ISSUE TITLE
check snmp / filter the output

### ISSUE THREAD

**Issue by haytxy** [monitoring-plugins/monitoring-plugins#1765]
hello Team,

Is any option to filter a pattern from the plugin output?

Im having this ugly output ...
![image](https://user-images.githubusercontent.com/79607995/165322623-f46b26ec-81ff-4336-943e-34f5f335a1d4.png)

Marcin

**Comment by RincewindsHat** [comment]
Hi @haytxy,
I am not sure, if that can be solved generally in `check_snmp`, I would recommend a custom script, even if it is just a wrapper.
