### ISSUE TITLE
check_disk support new units like MiB

### ISSUE THREAD

**Issue by mdicss** [monitoring-plugins/monitoring-plugins#1786]
New unit names Mib, KiB, GiB, TiB should be added to be able to solve problems with systems like icinga and grafana which redefined the old names (MB, GB ...) but understand the new names. See: https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_disk.c

**Comment by RincewindsHat** [comment]
The current `check_disk` output displays values in bytes anyways, so that is already solved.

**Comment by RincewindsHat** [comment]
Or did I misunderstand the question?

**Comment by mdicss** [comment]
The problem is, that e.g. grafana now interprets MB as megabytes 'decimal' and MiB as megabytes 'binary'. So the old unit MB there has a new interpretation causing wrong computed values. When you can use the new unitnames MiB, then they are correctly interpreted as 'binary' megabytes and you have the chance to get correct values.

**Comment by RincewindsHat** [comment]
Yep, that indeed sucks and I blame a generation of careless computer people for using units wrongly.
Anyhow, if you try the current master, `check_disk` (and some other plugins) wil output the full value as 'Byte' now and this should fix it.
Also avoids the rounding errors.

**Comment by mdicss** [comment]
I just test the check_disk in the master branche.  When using -u MB and -u MiB the values returned are the same, which is as expected, but also with -u MB the output gives back 'MiB'. This sould remain MB for backward compatibility.
check_disk -u MB -> xxxMB
check_disk -u MiB -> xxx MiB

**Comment by RincewindsHat** [comment]
Indeed this is a bug. Although this is not relevant for the perfdata part.

**Comment by mdicss** [comment]
Thank you for your fast response and for your work!
In my case, check_disk works as I want to use it with -u MiB with Icinga2 and InfluxDB/Grafana. Using this, the values should be correct now, when I swith the units in Grafana too.
