### ISSUE TITLE
Use `grep -E` instead of `egrep`

### ISSUE THREAD

**Issue by mariaa144** [monitoring-plugins/monitoring-plugins#1790]
I'm getting a warning from sensors script because egrep is now "obsolescent". `egrep` commands should be changed to `grep -E`.

Nagios reports the following when running on Arch Linux:
`Remote command execution failed: egrep: warning: egrep is obsolescent: using grep -E`

**Comment by waja** [comment]
Hi @mariaa144,

can you tell us your distribution and the version of `grep` please?

Thanks Jan

**Comment by andreasbaumann** [comment]
https://www.gnu.org/software/grep/manual/grep.html, 17.
grep 3.8 did away with the old egrep and fgrep (after deprecating them for at least 15 years).
IIIRC fgrep and egrep have been symlinks or shell script calling 'grep -F' resp. 'grep -E' for a long time.
egrep is still running, it just prints this warning on stderr. This should really not bother anybody.. unless
they rely on stderr. :-)

**Comment by mariaa144** [comment]
Yes, I think the warning is new because Nagios just started an "Unknown" status today for me when I updated Arch Linux.

**Comment by andreasbaumann** [comment]
A small grep on 'egrep' reveils tons of egreps in:
- configure.ac
- Solaris packaging
So, probing for egrep, grep -E might be needed (if Solaris is still a thing).

**Comment by andreasbaumann** [comment]
AC_PROG_EGREP is an option to probe for it, but what about code inside configure.ac itself (sort of a hen and egg here)?

**Comment by RincewindsHat** [comment]
hm, @waja does it break anything if we just patch every `egrep` with `grep -E` ?

**Comment by weiss** [comment]
> does it break anything if we just patch every `egrep` with `grep -E`?

That shouldn't break anything.

(That GNU move does sound like an April Fools' Day joke to me, though.)

**Comment by RincewindsHat** [comment]
@mariaa144  Thanks for the issue. Should be resolved now.
