### ISSUE TITLE
check_http - send POST request through proxy

### ISSUE THREAD

**Issue by pdcemulator** [monitoring-plugins/monitoring-plugins#1804]
I want to check a Webservice over an http proxy with a POST request. This webservice requires a certain http header set in the request.

It seems that not all values (Content-Type, Authorization) are sent to proxy. Please compare with working curl request and tcpdump output between monitoring host and proxy below.
The team that is operating the target system told me they have GET requests instead of POST in their access logs from my system. But I have to use the -j CONNECT parameter to get through the proxy...

My request:
`./check_http -H www.example.org -I proxy.internal.tld -u 	https://www.example.org/service/example -p 80 -j CONNECT -b "proxyuser:pass" -k "additionalheader: asdf" -E -P "key=value" -T "x-www-form-urlencoded" --ssl -a "appuser:pass"`

This sample curl request is working fine. Proxy set using http_proxy/https_proxy env variable.
`curl -X POST -k -H 'additionalheader: asdf' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization: Basic xxxx' -i 'https://www.example.org/service/example' --data 'key=value'`

tcpdump output:
```
s!(/....CONNECT www.example.org:443 HTTP/1.1
User-Agent: check_http/v2.3 (monitoring-plugins 2.3)
Proxy-Authorization: Basic xxxx
additionalheader: asdf
Proxy-Connection: keep-alive
Host: www.example.org


w.......CONNECT www.example.org:443 HTTP/1.1
Host: www.example.org:443
Proxy-Authorization: Basic xxxx
User-Agent: curl/7.29.0
Proxy-Connection: Keep-Alive
additionalheader: asdf
Content-Type: application/x-www-form-urlencoded
Authorization: Basic xxxx
```

(description updated as it turned out issue is not related to parameter -k)

**Comment by RincewindsHat** [comment]
Does it work with `check_curl`?

**Comment by pdcemulator** [comment]
No, I ran check_curl with same parameters as check_http and it had the same issue.

(We use check_mk 2.1, which comes with monitoring-plugins 2.3 but without check_curl. So I built it by myself).

**Comment by pdcemulator** [comment]
Working with -j CONNECT:POST as described in #1475

**Comment by sni** [comment]
Btw, `check_curl` works well with setting a proxy from the environment, ex.:

```
https_proxy=http://192.168.100.35:3128 .../check_curl -H www.....com -S
```
