### ISSUE TITLE
check_http: realloc(): invalid next size when using chunked encoding

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1829]
In Debian we got reported this issue: https://bugs.debian.org/1029934:
 
```
$ /usr/lib/nagios/plugins/check_http -H www.bootc.net --ssl --sni 
realloc(): invalid next size
Aborted
```
 
> When run in verbose mode it's clear that the site uses HTTP chunked
encoding, and this is potentially the cause of the problem.
>
> Please go ahead and use the URI/hostname in my example above to help to
reproduce this bug.

**Comment by RincewindsHat** [comment]
should be fixed by #1830
