### ISSUE TITLE
check_icmp still fails on FreeBSD 13.1 | Failed to send ping to 127.0.0.1 = Invalid argument

### ISSUE THREAD

**Issue by sonduko** [monitoring-plugins/monitoring-plugins#1841]
All calls to check_icmp return 100% packetloss and an error saying 'invalid argument'.

Run command: 
/usr/local/libexec/nagios/check_icmp -vvvvvvH 127.0.0.1

/usr/local/libexec/nagios/./check_icmp -vvvvvvH 127.0.0.1
address_family: 2 (IPv4 = 2; IPv6 = 10)
setsockopt failed
Setting alarm timeout to 10 seconds
packets: 5, targets: 1
target_interval: 0.000, pkt_interval 80.000
crit.rta: 500.000
max_completion_time: 3400.000
crit = {500000, 80%}, warn = {200000, 40%}
pkt_interval: 80000  target_interval: 0  retry_interval: 0
icmp_pkt_size: 76  timeout: 10
Sending ICMPv4 echo-request of len 24, id 30259, seq 0, cksum 0x83BD to host 127.0.0.1
Failed to send ping to 127.0.0.1 = Invalid argument
Sending ICMPv4 echo-request of len 24, id 30259, seq 1, cksum 0x80E0 to host 127.0.0.1
Failed to send ping to 127.0.0.1 = Invalid argument
Sending ICMPv4 echo-request of len 24, id 30259, seq 2, cksum 0x7EF2 to host 127.0.0.1
Failed to send ping to 127.0.0.1 = Invalid argument
Sending ICMPv4 echo-request of len 24, id 30259, seq 3, cksum 0x7D12 to host 127.0.0.1
Failed to send ping to 127.0.0.1 = Invalid argument
Sending ICMPv4 echo-request of len 24, id 30259, seq 4, cksum 0x7B38 to host 127.0.0.1
Failed to send ping to 127.0.0.1 = Invalid argument
finish(0) called
icmp_sent: 0  icmp_recv: 0  icmp_lost: 0
targets: 1  targets_alive: 1
CRITICAL -
127.0.0.1: rta nan, lost 100%|
rta=0.000ms;200.000;500.000;0; pl=100%;40;80;0;100 rtmax=0.000ms;;;; rtmin=0.000ms;;;;
targets: 1, targets_alive: 0, hosts_ok: 0, hosts_warn: 0, min_hosts_alive: -1

This should problem should be fixed.
Please see this for more information:
https://github.com/monitoring-plugins/monitoring-plugins/issues/1769
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264342

This is my actual bug report for FreeBSD:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269403

**Comment by sonduko** [comment]
Sry, I'm on the wrong project page. I have the problems with nagios-plugins. I close this case.

**Comment by waja** [comment]
> Sry, I'm on the wrong project page. I have the problems with nagios-plugins. I close this case.

great!
