### ISSUE TITLE
check_disk: interpret -X' arg as pattern, not literal

### ISSUE THREAD

**Issue by Al2Klimov** [monitoring-plugins/monitoring-plugins#1857]
In the Icinga 2 ITL we already exclude three FS types starting with "fuse" by default and Icinga/icinga2#9033 seems to demand one or two additional ones. As a user I'd like to be able to do `-X fuse*`. Do you agree with me?

**Comment by RincewindsHat** [comment]
Hm, sounds like a good idea, give all the `fuse*` things flying around.
@sni @waja opinions?

**Comment by sni** [comment]
i don't think we have "wildcards" anywhere yet, so i would prefer regex matching. But it sounds like a good idea, yes.
