### ISSUE TITLE
Wrong Plugin Returns

### ISSUE THREAD

**Issue by MisterMountain** [monitoring-plugins/monitoring-plugins#1860]
Hi,

i suddenly discovered that some monitoring-plugins have wrong return codes on the version output. Wrong as in "doesnt correspond with the guidelines in https://www.monitoring-plugins.org/doc/guidelines.html#AEN78"

This happens at least in check_sensors, check_oracle and check_log.

**Comment by waja** [comment]
@MisterMountain could you please so
kind and be a bit more specific?

**Comment by MisterMountain** [comment]
@waja Yes, sure. According to the linked Monitoring Guidelines, it would be expected behaviour to get an return code 3, if you are running e.g. check_oracle --version. In the current main-branch, check_oracle would instead exit with status 0.
