### ISSUE TITLE
Deprecate IRIX

### ISSUE THREAD

**Issue by RincewindsHat** [monitoring-plugins/monitoring-plugins#1877]
[IRIX](https://en.wikipedia.org/wiki/IRIX) has been end-of-life since quite some time.

```
# git grep -i irix | wc -l
141
```
I think some of that can be safely removed.

**Comment by waja** [comment]
Let's go ahead with the next release and remove it with the next major release.

**Comment by RincewindsHat** [comment]
Had another look through that and it seems like most IRIX stuff is in `gl`. So this issue is mostly pointless.
