### ISSUE TITLE
check_procs: `Unable to read output` on AlmaLinux 9

### ISSUE THREAD

**Issue by SMillerDev** [monitoring-plugins/monitoring-plugins#1897]
After compiling my own RPM of monitoring plugins for RHEL 9 everything seems to work well except `check_procs` which always reports "Unable to read output" is there any way to get more debugging information?

**Comment by RincewindsHat** [comment]
Hi @SMillerDev,
could you try with `-v`? Did you build the package (spec file) youself?

**Comment by SMillerDev** [comment]
I build the spec/package myself based on the nagios plugins package in EPEL. It worked fine for CentOS 7, but on Alma Linux 9.

```console
sean@heath:~$ /usr/lib64/nagios/plugins/check_procs  -c 1: -C sshd
Unable to read output
sean@heath:~$ /usr/lib64/nagios/plugins/check_procs  -c 1: -C sshd -v
Unable to read output
```

**Comment by RincewindsHat** [comment]
hm, could you try if the `ps` command is there? :-)

**Comment by SMillerDev** [comment]
```console
sean@heath:~$ which ps
/bin/ps
```

And the ps command that is specified in `./configure` also works fine when I run it from the commandline, giving seemingly identical output to the one on CentOS 7.

**Comment by RincewindsHat** [comment]
hm, weird

```
/usr/lib64/nagios/plugins/check_procs  -c 1: -C sshd -vv
```
?

**Comment by SMillerDev** [comment]
Ah, now we're getting somewhere, maybe `ps` isn't available on the machine that build the package:
```console
root@findlay:~# /usr/lib64/nagios/plugins/check_procs  -c 1: -C sshd -vv
CMD:  -eo 's uid pid ppid vsz rss pcpu etime comm args'
Unable to read output
```

Since the `nagios_plugins` from EPEL has:
```
--with-ps-command="`which ps` -eo 's uid pid ppid vsz rss pcpu etime comm args'" \
```

I'll let you know if it is

**Comment by RincewindsHat** [comment]
hm, would be nice to let the build (of `check_procs` at least) fail at that point

**Comment by SMillerDev** [comment]
It definitely would be nice, but I'll leave that up to you.

**Comment by SMillerDev** [comment]
Yeah, hardcoding the `ps` command fixed it, thanks for pointing out the increased verbosity option!

**Comment by RincewindsHat** [comment]
hm, but `ps` was installed on the build machine? but not detected?

**Comment by SMillerDev** [comment]
I decided to change my `Buildrequires` to `%{_bindir}/ps` and just use that in the configure command instead, I didn't bother checking if it was installed since my previous `Buildrequires` was supposed to check that already so it might be something about the `which` command in the specfile.

**Comment by waja** [comment]
> Yeah, hardcoding the `ps` command fixed it, thanks for pointing out the increased verbosity option!

That's what we also do when building the Debian packages. So I'd say this is a good idea.
