### ISSUE TITLE
Documentation: How to update translations

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1900]
Since we've introduced #1895, we should have a documentation in place how update them (easily). Ths can be included into https://www.monitoring-plugins.org/doc/faq/git.html or somewhere in https://github.com/monitoring-plugins/monitoring-plugins/tree/master/doc

**Comment by waja** [comment]
it's something like:
```
tools/setup && \
./configure && \
cd po && make update-po
```

**Comment by RincewindsHat** [comment]
since we are going to remove translations #1947 this can be closed
