### ISSUE TITLE
check_load - Error opening /usr/bin/uptime 

### ISSUE THREAD

**Issue by jframeau** [monitoring-plugins/monitoring-plugins#1902]
Env: RKL 9 / OMD Labs 5.20

Using cli, check_load works as usual.

But under gearman worker, check_load fails when opening uptime.

SELinux is on but when set to 0, same error. 

```
$ check_load --version
check_load v2.3.3 (monitoring-plugins 2.3.3)
```

jfr

**Comment by RincewindsHat** [comment]
Hi @jframeau,
I don't know much about OMD etc., but could you add the full error message to this thread?

Also, did you try to use `check_load` (via cli) as the user which is executing the checks?

**Comment by RincewindsHat** [comment]
Note: Edited the first post slightly for better readability

**Comment by jframeau** [comment]
No issue when starting the command via cli and the user dedicated to monitoring.

Btw, we have two other workers running on CentOS 7 and RKL 8 with no such erro (same check_load version).

Unfortunately, this is the only message we get. 

I just recompiled check_load with some additional output in spopen function. Let's see what(s goiing on.

**Comment by sni** [comment]
what error message do you get?
