### ISSUE TITLE
check_disk is very slow

### ISSUE THREAD

**Issue by nono-gdv** [monitoring-plugins/monitoring-plugins#1919]
Hi,

Since upgrading from Debian 11 (monitoring-plugins 2.3.1) to Debian 12 (monitoring-plugins 2.3.3), check_disk has gotten very slow on one of our servers.

Here is the old version 2.3.1:
```
# time ./check_disk -W 1% -K 1% -w 1% -c 1% -l --exclude-type=fuse.lxcfs --exclude-type=tmpfs --exclude-type=devtmpfs --exclude-type=overlay --exclude-type=nsfs --exclude-type=tracefs --exclude-type=squashfs --exclude-type=zfs -e -A -i ^/var/lib/lxc/.+ -i ^/etc/octopuce/
DISK OK| /=11765MB;19786;19786;0;19986

real    0m14,709s
user    0m10,701s
sys     0m0,307s
```

I tried the exact same command line with version 2.3.3 but gave up and stopped the command after more than one hour.

The machine has about 16000 mounted filesystems, most of them ZFS snapshots (which check_disk should ignore with this command line).
```
# mount | wc -l                                          
16486
# mount | grep -v zfs | wc -l                                          
24
```

Running the plugin under strace shows it calling statfs again and again.

I suspect this behaviour was introduced in commit dd249c5d4bbce1c1250322dab8c8d0d69b0dca34 but I have not formally verified it.

**Comment by RincewindsHat** [comment]
Hi @nono-gdv,
firstly thanks for reporting this. This looks quite interesting.
When I find the time I will try to replicate the problem and try to find out what the original cause is.

If possible, could you grab a debugger and see where `check_disk` spends its time?

PS: I also would be quite interested to learn what this setup does.

**Comment by sni** [comment]
i assume this is due to #1879 which has been fixed in #1880. But afaik did not make it into a release yet.

**Comment by RincewindsHat** [comment]
@waja Sounds like you might want to cherry-pick that patch then.

**Comment by waja** [comment]
@nono-gdv  It would be very welcomed to report that issue in den Debian BTS. This might raise the chance to get that fixed in Debian 12, cause patches for minor (or no) bug fixes have a small chance to get accepted by stable release managers.

**Comment by nono-gdv** [comment]
Done, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1051768

**Comment by waja** [comment]
This was fixed with 22_check_disk_avoid_mount (https://sources.debian.org/src/monitoring-plugins/2.3.3-6/debian/patches/22_check_disk_avoid_mount/) in Version 2.3.3-6. Let's see if I get the chance to backport it.

**Comment by waja** [comment]
This issue will be solved with the next stable point release: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052218#24

**Comment by waja** [comment]
> This issue will be solved with the next stable point release: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052218#24

Which happened right now. :)
