### ISSUE TITLE
lib/maxfd.h missing from https://www.monitoring-plugins.org/download/monitoring-plugins-2.3.4.tar.gz

### ISSUE THREAD

**Issue by hydrapolic** [monitoring-plugins/monitoring-plugins#1943]
Hello, trying to build v2.3.4 from official website, however maxfd.h is missing from the package. It's included in the github source code thought.

**Comment by RincewindsHat** [comment]
Hi @hydrapolic, thanks for reporting, we're on it

**Comment by hydrapolic** [comment]
Thanks!
