### ISSUE TITLE
ftbfs on centos 7 due to old openssl

### ISSUE THREAD

**Issue by sni** [monitoring-plugins/monitoring-plugins#1950]
EVP_MD_CTX_new and SSL_CTX_set_min_proto_version from `lib/utils_base.c` is not available on centos 7. Seems like this has
been introduced with openssl 1.1.1.

centos 7 has this one:
```
Installed Packages
Name        : openssl-devel
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
```

The regression has been introduced with:
- https://github.com/monitoring-plugins/monitoring-plugins/commit/7c98e2b345b91d8ef3fb1f7a1bcf74194d54c966
- https://github.com/monitoring-plugins/monitoring-plugins/commit/8700f497160cfc2cce8918c8cd8922b7320c510a

**Comment by RincewindsHat** [comment]
Correct me if I am wrong, but we discussed this in the chat and due to the EOL of CentOS/RHEL 7 being quite close, nobody really voluntered to restore backwards compatibility.
Therefore, if nobody else REALLY wants this (and has more to offer than some nice words), this won't be fixed.

**Comment by sni** [comment]
ok for me, i reverted those commits in our builds for the time being...
