### ISSUE TITLE
plugins exporting their local symbols

### ISSUE THREAD

**Issue by andreasbaumann** [monitoring-plugins/monitoring-plugins#1954]
`nm check_curl | grep print`:

```
0000000000005580 T print_help
000000000000b470 T print_revision
000000000000d500 T print_thresholds
0000000000005430 T print_usage
```

Is there a particular reason why we use this style:

```
void print_help (void);
...
void
print_help (void)
{
...
```

instead of:

```
static print_help (void);
...
void
print_help (void)
{
...
```

IMHO it just exports a whole bunch of local symbols into the binary.

**Comment by RincewindsHat** [comment]
Can't say that there is any other reason other than nobody care until just now :-)

**Comment by RincewindsHat** [comment]
After thinking about that for a minute, another reason might be, that we have some unit tests in c which probably need to link against some of those symbols, but I might be wrong

**Comment by RincewindsHat** [comment]
reference #2020 #2021

**Comment by RincewindsHat** [comment]
Apart from uselessly exposing the symbols, _not_ declaring those symbols as static prevents a compiler from detecting unused ones.
IMHO, this is actually a problem, although one with small consequences ("only" wasting dev time)

**Comment by RincewindsHat** [comment]
should mostly be fixed by now.

**Comment by RincewindsHat** [comment]
should be done
