### ISSUE TITLE
following change check_users plugin always reports 1 user too many when called via check_by_ssh

### ISSUE THREAD

**Issue by mosh5382** [monitoring-plugins/monitoring-plugins#1957]
Following the recent change to preferring systemd-logind over utmp it seems that check_users includes the user that initiates the check_by_ssh in the total user count.  This has the unintended consequence of 1 too many users being reported by check_users.  I run check_users as follows:

`check_users -w 0 -c 1`

I want to be notified for any user login. Following the change, check_users always thinks 1 user is logged in even if no users are currently logged in.

This appears to be because of the quick response by systemd-logind. I run the following commands to monitor logged in users:

`watch -n 0.1 loginctl`

`watch -n 0.1 utmpdump /var/run/utmp`

When a check_by_ssh occurs the ssh session is short enough that no user login is registered in utmp. However, as systemd-logind reacts instantly to the check_by_ssh login the user that initiates the check_by_ssh login is counted by check_users.

Perhaps some logic can be included to subtract 1 user from the logged in users count when check_users is initiated by check_by_ssh?  For now I've rolled back to an older release of monitoring-plugins where check_users still uses the utmp method.

**Comment by RincewindsHat** [comment]
Hi @mosh5382,
Sorry to have cause you trouble. Nevertheless IMHO `check_users` is correct here (and was wrongish in the past), since one users is actually logged.
Wouldn't the fix be to modify your thresholds to accomodate this?

**Comment by mosh5382** [comment]
Thanks for the follow up.  You are right that check_users is working correctly.  I don't see any downside to changing my threshold.  I don't believe Nagios would do two checks at the same time with check_by_ssh which would cause a false positive.  I'm going to close this issue.
