### ISSUE TITLE
check_load: uses #ifdef HAVE_PROC_LOADAVG which was removed from the configure script

### ISSUE THREAD

**Issue by adaugherity** [monitoring-plugins/monitoring-plugins#1965]
There are several `#ifdef HAVE_PROC_LOADAVG` blocks, e.g. https://github.com/monitoring-plugins/monitoring-plugins/blob/f054ab04e788405932b9bb081747bc7c8328a0d8/plugins/check_load.c#L130-L151

These blocks will never be compiled, since that symbol is not defined.  It used to be a configure check, but that was removed a _long_ time ago, in fe856aa (configure.in line 609).

It seems that using `getloadavg()` is preferred where available, so the `/proc/loadavg` fallback may not be that common.  Regardless, it should either be removed or wired back into configure.ac; I have no idea which would be preferred.

I don't think there's a need to bring back the --with-proc-loadavg=_path_ parameter (what else would it ever be?), but perhaps we should check for the existence of `/proc/loadavg`?

(Noticed via https://bugzilla.suse.com/show_bug.cgi?id=1216148#c9, which turned out to be an unrelated problem.)

**Comment by RincewindsHat** [comment]
Hi @adaugherity 
Thanks for reporting that, I am trying to address this in #1966

**Comment by RincewindsHat** [comment]
Closed by #1998. Thanks @adaugherity
