### ISSUE TITLE
check_curl: --post parameter takes URL decoded data, not encoded as help suggests

### ISSUE THREAD

**Issue by C0rn3j** [monitoring-plugins/monitoring-plugins#1978]
Based on what the help suggests, `id=1` should not work but `id%3D1` should.

The opposite is the true, either the help documentation or the behavior needs fixing.

```shell
[0] % '/usr/lib/monitoring-plugins/check_curl' --help  | grep -e 'check_curl v'
check_curl v2.3.5 (monitoring-plugins 2.3.5)
```

```ini
 -P, --post=STRING
    URL encoded http POST data
```

```shell
[0] % '/usr/lib/monitoring-plugins/check_curl' '--hostname=www.bloody.com' '--post' 'id%3D1' '--sni' '--ssl=1.2+' '--string=V2023.1206_MUI' '--timeout=30' '--url=/en/Detailed.php' '--use-ipv4'
HTTP CRITICAL: HTTP/1.1 200 OK - string 'V2023.1206_MUI' not found on 'https://www.bloody.com:443/en/Detailed.php' - 149297 bytes in 1.646 second response time |time=1.646261s;;;0.000000;30.000000 size=149297B;;;0;

[2] % '/usr/lib/monitoring-plugins/check_curl' '--hostname=www.bloody.com' '--post' 'id=1' '--sni' '--ssl=1.2+' '--string=V2023.1206_MUI' '--timeout=30' '--url=/en/Detailed.php' '--use-ipv4'
HTTP OK: HTTP/1.1 200 OK - 158714 bytes in 1.653 second response time |time=1.652690s;;;0.000000;30.000000 size=158714B;;;0;
```

**Comment by RincewindsHat** [comment]
Totally agree, the description is not descriptive enough and misleading

**Comment by andreasbaumann** [comment]
ok, understood. I can reproduce it now. `check_curl` and `check_http` behave exactly the same, so I would opt do adapt the documentation in both plugins and not to change the behaviour.

**Comment by andreasbaumann** [comment]
Fixed in 4c4031100a4520fe1e9a835e56b00e32b841f63e

**Comment by RincewindsHat** [comment]
So, this is closed I guess? If not, don't hesitate to reopen the issue

**Comment by C0rn3j** [comment]
@RincewindsHat it's not in `master` yet, if it's eventually going there, fine by me to close.

**Comment by RincewindsHat** [comment]
oh, yes, sorry. Misread that. I will leave this open until the issue is resolved to make sure it's not forgotten :-)

**Comment by C0rn3j** [comment]
#2006 fixed this
