### ISSUE TITLE
./check_snmp doesn't work - wrong parameters passed to s

### ISSUE THREAD

**Issue by alexoalexo** [monitoring-plugins/monitoring-plugins#1983]
On my Debian 12.4 system, it looks like check_snmp is broken/not working ...
```
# ./check_snmp -V
check_snmp v2.3.3 (monitoring-plugins 2.3.3)
```

Running this:   ./check_snmp -v -H localhost  -C public -o ifOperStatus.1
Returns:
`
/usr/bin/snmpget -Le -t 10 -r 5 -m ALL -v 1 [context] [authpriv] localhost:161 ifOperStatus.1
`

It doesn't push the correct options to snmpget

Thanks

**Comment by RincewindsHat** [comment]
Hi @alexoalexo, what would be the correct options?

**Comment by alexoalexo** [comment]
For example it doesn't send the community string.
If I do 
`/check_snmp -v -H localhost -C myCommunity -o ifOperStatus.1`

 I still get:
`/usr/bin/snmpget -Le -t 10 -r 5 -m ALL -v 1 [context] [authpriv] localhost:161 ifOperStatus.1`

**Comment by RincewindsHat** [comment]
Does it work if you add `-P 2c`?

**Comment by alexoalexo** [comment]
No,
here another example:

```
# ./check_snmp -v -H 192.168.x.x-C monitoringcommunity  -P 2c  -o ifOperStatus.1
/usr/bin/snmpget -Le -t 10 -r 5 -m ALL -v 2c [context] [authpriv] 192.168.x.x:161 ifOperStatus.1
```
and eventually times out

If I run snmpget manually with the correct community, it is ok:
```
# /usr/bin/snmpget -Le -t 10 -r 5 -m ALL -v 2c -c monitoringcommunity  192.168.x.x   1.3.6.1.2.1.1.3.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (13774600) 1 day, 14:15:46.00
```

As I said, check_snmp is not pushing down the correct parameters to snmpget

**Comment by sni** [comment]
[context] and [authpriv] are placeholders so the credentials do not end up in the output by accident. You could use `strace` to reveil the true parameters.

**Comment by RincewindsHat** [comment]
also your newest example doesn't work for me since there is a space missing before `-C`

**Comment by alexoalexo** [comment]
> also your newest example doesn't work for me since there is a space missing before `-C`

This is as I've tried to change IP. 
I just realized that I'm not using the correct OID format :)
`

ifOperStatus.1: Unknown Object Identifier (Sub-id not found: (top) -> ifOperStatus)
`

Thanks for your help
