### ISSUE TITLE
./plugins/check_load.c uses HAVE_PROC_LOADAVG but this is not checked or set in configure script

### ISSUE THREAD

**Issue by bugfinder** [monitoring-plugins/monitoring-plugins#1999]
Hi, stumbled over this when checking why check_load always needs to call uptime as external binary. turned out the HAVE_PROC_LOADAVG macro is never being defined, should probably be similar to the proc/meminfo check

**Comment by RincewindsHat** [comment]
Hi @bugfinder, this was reported to us in #1965 (and the dead code removed).
