### ISSUE TITLE
check_curl documentation and status

### ISSUE THREAD

**Issue by Tontonitch** [monitoring-plugins/monitoring-plugins#2003]
Hello,
Any reason to not have a check_curl page in the documentation?
Is this plugin considered as stable and ready for production now?
BR,
Yannick

**Comment by RincewindsHat** [comment]
As far as I remember, the lack of documentation is due to some technical problem ( @weiss ), which we could not circumvent.

It is mostly stable I would say, I am using it in production and I didn't find any obvious problems yet.

**Comment by waja** [comment]
Actually, the build process of the man pages is broken on the system hosting the website. So they are not updated since Feb 2023.

**Comment by waja** [comment]
The source of the issue is https://github.com/monitoring-plugins/monitoring-plugins/commit/e8bd88d1fcded01ccd066572eeaae1b507989cb3 which requires automake 1.14

**Comment by waja** [comment]
I did some work to update the man page sites by hand and this seems to be better than the versions from 2023, but the build chain needs to be fixed at some point.

**Comment by weiss** [comment]
> the build process of the man pages is broken on the system hosting the website.

This is finally [fixed][1].

[1]: https://monitoring-plugins.org/doc/man/check_curl.html
