### ISSUE TITLE
check_icmp perfdata rtmin is always 0.0ms

### ISSUE THREAD

**Issue by dheule** [monitoring-plugins/monitoring-plugins#2047]
If you call check_icmp:
`./check_icmp -H some_hostname.domain.org`
the output of the performance data rtmin is always 0.0ms, this is not possible.
Example output:
`OK - some_hostname.domain.org rta 196.981ms lost 0%|rta=196.981ms;200.000;500.000;0; rtmax=197.168ms;;;; rtmin=0.000ms;;;; pl=0%;40;80;0;100`
As you see, rtmin is always 0

**Comment by RincewindsHat** [comment]
Jup, looks like it may never be set properly. Thanks for reporting that.
