### ISSUE TITLE
check_ping: Adjusting packet size [sf#781002]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#229]
Submitted by thedoc31 on 2003-07-31 19:51:35

check_ping doesn't currently support the -s
(packetsize) feature of the ping command.

I have an instance where normal ICMP packets sometimes
don't show packet loss across our WAN but larger
packets will show the packet loss.  It would be handy
to be able to specify the packet size on the
commandline of check_ping so I can make a small packet
check and a large packet check for WAN latency in Nagios.

**Comment by go8ose** [comment]
I'd really like this as well. We had a router replaced last week which was misconfigured, and dropping packets larger than 1468 bytes. We didn't even know we had a problem until users were complaining the next morning. Now I want to setup some monitoring to catch this earlier, which would need this option.

**Comment by riskersen** [comment]
Here's a suggested patch #1356 but the test is failing..maybe someone could have a look on it

**Comment by RincewindsHat** [comment]
check_icmp implements this
