### ISSUE TITLE
check_swap on hpux shows negative value [sf#1082791]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#401]
Submitted by mroeh on 2004-12-10 11:10:21

Hi,

I'm using nagios-plugins-HEAD-200412080547 on hpux
11.00. Compiling works fine, but when I try to use the
check_swap I get the following error:
./check_swap -vvv -w90% -c80%
Command: /usr/sbin/swapinfo -dfM,
Format: %_s %d %_d %d
SWAP CRITICAL: -2147483547% free (0 MB out of 0 MB)
|swap=0MB;0;0;0;0

Output of /usr/sbin/swapinfo -dfM is
 Kb      Kb      Kb   PCT  START/      Kb
TYPE      AVAIL    USED    FREE  USED   LIMIT RESERVE 
PRI  NAME
dev     2097152       0 2097152    0%       0       - 
  1  /dev/vg00/lvol2
dev     17776640       0 17776640    0%       0       -
   1  /dev/vgswap/lvol1
memory  3217700 2425360  792340   75%

The same happened if the swap is used.

**Comment by riskersen** [comment]
According to the SF tracker:
The error is (in version 1.4.5) at line 1442 of configure.in
ac_cv_swap_command="$PATH_TO_SWAPINFO -dfM", 
The error is the ',' at the end of the line

The "," has been removed as well, so it should be fixed.
	ac_cv_swap_command="$PATH_TO_SWAPINFO -dfM"
