### ISSUE TITLE
Uninitialized value warning in check_ifoperstatus [sf#1202797]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#432]
Submitted by reuben on 2005-05-16 14:03:44

I've been seeing this error for the last few weeks with
this plugin.  This is the message returned by the
plugin when invoked via Nagios:
```
**ePN /usr/lib/nagios/plugins/check_ifoperstatus: "Use
of uninitialized value in numeric gt (>) at (eval 3257)
line 359". 
```
Nagios displays an 'orange' status for this check.

line 359 looks like this:
```
unless ($snmpkey > 0 || defined $ifdescr){
```
When the command is executed manually, it looks like this:
```
[root@tornado plugins]#
/usr/lib/nagios/plugins/check_ifoperstatus -H
192.168.0.1 -C snmpaccess -d ATM0
OK: Interface ATM0 (index 1) is up.[root@tornado plugins]# 
```
(I wonder if a missing CR at the end is a bad thing..)

**Comment by RincewindsHat** [comment]
Closing this, since plugins must be specifically designed to be used with ePn and `check_ifoperstatus` is not.
