### ISSUE TITLE
Enhancements in check_snmp [sf#1104536]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#453]
Submitted by friedl-faba on 2005-01-18 16:27:59

I've made some enhancements in the check_snmp plugin. These are:
Use of factors, so that the output will be divided/multiplied by this factor.
Algebraic operations, allowing addition, multiplication ... of results and 
constants
Generation of performance output for Nagios

There are few additional files, which I needed for the algebric 
operations:
queue.h / queue.c for stacks and queues
calculator.h / calculator.c for the evaluation
Therefore some changes in the Makefile are necessary.

Regards,
Friedrich
## 

Friedrich Priewasser
Software Engineer
Fabalabs Software GmbH
Honauerstraße 4
A-4020 Linz
e-mail: mailto:friedrich.priewasser@fabalabs.org
http://www.fabalabs.org

**Comment by sesse** [comment]
Hi,

16 years later, is there some work to get this patch merged? :-) I need the factors; SNMP temperature values are in decidegrees, and it would be nice to be able to multiply them by 0.1 before display.

**Comment by sni** [comment]
could anyone put this change in a proper pull request, then i am happy to review it.

**Comment by odenbach** [comment]
I would like to help but unfortunately the link from above does not work anymore so I do not have the patch. @sesse can you privide me with the file?

**Comment by sni** [comment]
the attachments are now at http://monitoring-plugins.org/attachments/116237-check_snmp.tar.gz

**Comment by odenbach** [comment]
Thanks. Unfortunately the patch does not apply at all to the current code, many changes have occured in the past years. Without complete understanding what the patch does I cannot modify the source to implement its changes.
@sesse What exactly do you need from the patch? Just the factors? As I understand the patch also implements some other features.

**Comment by sesse** [comment]
Yes, I only need the factors.

Currently, what I have on warning is

WARNING: SNMP WARNING - *281* decidegrees

and I would like to be able to specify a factor 0.1 to get

WARNING: SNMP WARNING - *28.1* degrees

Having it on display-only is fine (I can keep having limits in raw values), having it with %g only is fine. I believe some of this should already be in place for rate calculations.

**Comment by RincewindsHat** [comment]
Modifier is implemented since [2.3.3](https://github.com/monitoring-plugins/monitoring-plugins/releases/tag/v2.3.3)

**Comment by RincewindsHat** [comment]
Frankly I think this add too much complexity to `check_snmp` and I would like to reject this. @sni other opinions?

**Comment by sni** [comment]
i guess this can be close because the modifier/factor is already in place.
