### ISSUE TITLE
check_swap performance info incorrect [sf#1225470]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#466]
Submitted by backseat on 2005-06-22 13:55:14

If check_swap is invoked with percentage aguments the
performance data is incorrect:

---

$ ./check_swap -V
check_swap (nagios-plugins 1.4) 1.47

$ ./check_swap -w 30% -c 20%  
SWAP OK: 94% free (894 MB out of 954 MB)
## |swap=893MB;286;190;0;953

In the performance data section is:
value=893
warn=286
crit=190
min=0
max=953

The value is above both the warn and crit values, which
in this case is correct (ie, not an error). It would be
better if the performance data were presented in
percentage terms if the input is in percentage terms.

One solution would be to express the warning and
critical values as an @range (alarm if within range)
with a lower value of zero.

**Comment by RincewindsHat** [comment]
I think this can be closed. Don't see a concrete problem here.
