### ISSUE TITLE
signal handler in popen.c is totally broken [sf#1469468]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#549]
Submitted by nsturm on 2006-04-12 21:35:12

popen_timeout_alarm_handler() in popen.c is a signal
handler which does all kinds of stuff you better NOT
do in a signal handler. Plugins using this signal
handler should be rewritten to deal with a much simpler
signal handler, doing the bare minimum like setting a
flag.

For a better explanation of all the problems, please
look at
http://www.openbsd.org/papers/opencon04/index.html

**Comment by riskersen** [comment]
According to the SF tracker, popen_timeout_alarm_handler has been fixed in 2007
