### ISSUE TITLE
check_ping timeout on Mandrake 10.1 [sf#1373801]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#601]
Submitted by alex_b on 2005-12-05 21:01:38

With Mandrake 10.1 and nagios-plugins-1.4 I had a
problem where devices that were down would return a
result of 'plugin timed out'.  The attached patch fixes
the problem by adding 2 seconds to the alarm() call.

The problem was that Nagios passed a timeout value of
10 seconds to the plugin.  The plugin would then call
ping with a timeout of 10 seconds (PING_HAS_TIMEOUT is
defined).  This would cause the plugin to abort before
it got the result from the ping command.  Adding 2
seconds to alarm will cause it to abort the plugin
after 12 seconds which will give ping enough time to
respond.

It may be better to reduce the timeout value passed to
ping.  For example, instead of:
```
# ifdef PING_HAS_TIMEOUT

asprintf (&cmd, rawcmd, timeout_interval, max_packets,
addresses[i]);
# else
```
use:
```
# ifdef PING_HAS_TIMEOUT

if (timeout_interval > 2)
asprintf (&cmd, rawcmd, timeout_interval-2,
max_packets, addresses[i]);
else
asprintf (&cmd, rawcmd, timeout_interval, max_packets,
addresses[i]);
# else
```

**Comment by RincewindsHat** [comment]
Patch missing, don't see any current mention of this problem. Close?

**Comment by RincewindsHat** [comment]
https://www.monitoring-plugins.org/attachments/158749-patch-check_ping-timeout

**Comment by waja** [comment]
I would opt for close. This distro is not existing anymore since years.

**Comment by RincewindsHat** [comment]
D'accord
