### ISSUE TITLE
check_procs segfaults with zombies [sf#1455619]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#627]
Submitted by lausser on 2006-03-21 21:03:42

Hi,
under solaris, ps produces output like this for 
zombie processes:
Z 55618 28898 15263    0    0  0.0 

The statement 
cols = sscanf (input_line, PS_FORMAT, PS_VARLIST);
which is actually this one:
...sscanf (input_line, "%s %d %d %d %d %d %f %s%n", 
procstat,&procuid,&procpid,&procpid,&procvsz,&procrss,
&procpcpu,procprog,&pos);

does not fill the pos variable with a value because 
there is no match for the last %s. pos keeps the 
value it got when the last time a non-zombie process 
was found.

pos points to the arguments following procprog which 
is senseless in this case anyway. but later it is 
used to initialize the procargs array.
asprintf (&procargs, "%s", input_line + pos);
In the case of a zombie pos has a value related to 
the last input_line but not the current one, so an 
illegal byte beyond the strings end may be accessed.

I made a patch which takes this into account.

Greetings from Munich,
Gerhard

**Comment by RincewindsHat** [comment]
OpenIndiana
```
./plugins/check_procs
Unable to read output
````

**Comment by RincewindsHat** [comment]
Closing this until someone comes around and tells us how reproduce the issue (and how to compile on Solaris).
