### ISSUE TITLE
check_dhcp: patch for "Rogue DHCP server detection" [sf#1854415]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#752]
Submitted by pcervicek on 2007-12-19 22:03:04

This patch helps check_dhcp to detect rogue dhcp servers.
Use it with the "-x" flag

example output:

[root <at> pc4 plugins-root]# ./check_dhcp -s 192.168.1.1 -x
CRITICAL: Rogue DHCP Server detected! Server 192.168.1.205 offered 192.168.1.239

**Comment by riskersen** [comment]
Correct link: http://sourceforge.net/p/nagiosplug/patches/272/
