### ISSUE TITLE
Configure nagios-plugins inside vserver hangs [sf#1776916]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#756]
Submitted by norbertklein on 2007-08-18 18:12:05

nagios-plugins-1.4.9
./configure
Gentoo
Tested on x86 AMD64
gcc

Configure nagios-plugins hangs inside vserver environment (or any other environment without IP `127.0.0.1`) as soon as the configure script tries to
check the ICMP syntax.  

Reproducible: Always

Gentoo output:

```
checking for ps... /bin/ps
checking for ps syntax... /bin/ps axwo 'stat uid pid ppid vsz rss pcpu comm 
args'
checking for ping... /bin/ping
checking for ping6... /bin/ping6
checking for ICMP ping syntax...

ctrl-c
/usr/portage/net-analyzer/nagios-plugins/nagios-plugins-1.4.9.ebuild:
src_compile aborted; exiting.
```

The reason is that `127.0.0.1` is hardcoded as localhost IP inside the configure script. This is done for checking ICMP syntax and  nslookup syntax. But
vservers don't have this IP.

The following files contain 127.0.0.1 hardcoded:
configure.in
check_dig.c
check_pgsql.c
check_smtp.c
check_tcp.c
check_ups.c

I tested these five checks inside a vserver environment and check_dig was the only one which didn't work. As far as I understand the code the reason is that check_dig calls the program dig which fails in case of 127.0.0.1. The others use system calls for their operations.

To fix it I modified configure.in and used the hostname in check_dig.c. I attached a patch for the two mentioned files. For Gentoo you find a modified ebuild below which contains the patchs as well. I tested it on two different Gentoo machines and it worked for me.

http://www.acodedb.com/download/linux/nagios-plugins.tgz

**Comment by riskersen** [comment]
It is still hard-coded, so we might consider the merge, current behavior should lead to AC_MSG_WARN([unable to find usable ping syntax])

URL of the diff is: https://www.monitoring-plugins.org/attachments/241808-configure.in_check_dig.c.diff

**Comment by riskersen** [comment]
Duplicate with #1071

**Comment by RincewindsHat** [comment]
@monitoring-plugins/developers is this still a thing? Having machines without loopback/127.0.0.1 ? Should we address that?

**Comment by waja** [comment]
Looking into https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/monitoring-plugins/monitoring-plugins-2.3.5.ebuild#n74 I think, there are several reasons why this is also impossible and ppl can configure ping(6) usage in this case.

**Comment by RincewindsHat** [comment]
so, close this?

**Comment by waja** [comment]
would say 'yes'.
