### ISSUE TITLE
broken awk script subst.in [sf#1250967]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#794]
Submitted by nsturm on 2005-08-03 13:53:18

The script plugins-scripts/subst.in does things in the wrong order
resulting in broken pathnames. As an example look at check_rpc.pl.

First "use lib utils.pm;" is substituted by the full path name to utils.pm,
but then the first name component is stripped off again (at least on
OpenBSD where /usr/local/libexec/nagios/utils.pm becomes just
nagios/utils.pm)

This is on OpenBSD-current with plugins 1.4 and 1.4.1. Diff attached.

**Comment by RincewindsHat** [comment]
`subst.in` was removed a while ago, this is probably not a problem anymore
