### ISSUE TITLE
check_tcp: Expiring SSL certs produce confusing messages. [sf#1939529]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#799]
Submitted by gdrago23 on 2008-04-10 18:10:54

I am running nagios-plugins 1.4.11, the version from Ubuntu Hardy, backported to Feisty.

$ /usr/lib/nagios/plugins/check_tcp -S -H www.google.com -p 443 -D 10; echo $?
OK - Certificate will expire on 05/14/2008 23:18.
TCP OK - 0.084 second response time on port 443|time=0.083917s;;;0.000000;10.000000
0
$ /usr/lib/nagios/plugins/check_tcp -S -H www.google.com -p 443 -D 295; echo $?
WARNING - Certificate expires in 34 day(s) (05/14/2008 23:18).
CRITICAL - Cannot retrieve server certificate.
1

The plugin only returns WARNING, as it should, but the second result line is wrong--the server certificate is indeed being retrieved, and the plugin isn't returning CRITICAL.

Looking through the check_tcp.c source, it appears that np_net_ssl_check_cert is returning CRITICAL when the certificate can't be retrieved or parsed, or when it's expired, and WARNING when it's going to expire within the interval specified by the "-D" option. check_tcp interprets any answer other than STATE_OK as a failure to retrieve the cert.

The root problem seems to be a conflation of Nagios return codes with function return codes; a plugin may interpret a failure to retrieve the certificate at all quite differently from the retrieval of an expired or soon-to-expire certificate.

Perhaps it would be a better idea to have np_net_ssl_check_cert return STATE_UNKNOWN when it can't retrieve the SSL cert information, and STATE_WARNING/STATE_CRITICAL when there's a problem with it, so that the calling program can differentiate between the two types of event. Failing that, check_tcp should check for (result != STATE_OK && result != STATE_WARNING) rather than just (result != STATE_OK).

**Comment by RincewindsHat** [comment]
```
./plugins/check_tcp -S -H www.google.com -p 443 -D 29500; echo $?                                                                                                                   git - (monitoring-plugins|check_ping_adjust_packet_size)
WARNING - Certificate 'invalid2.invalid' expires in 2965 day(s) (Di 01 Jan 2030 00:00:00 GMT +0000).
1
```
can't reproduce
