### ISSUE TITLE
check_swap not build on UNIX [sf#1984255]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#802]
Submitted by df7be on 2008-06-04 10:37:09

Hello,
on Solaris 10, HP-UX 11.11, 11.23 the Plugins was not build. The latest Version of this Plugin avaulable on HP-UX was:
./check_swap --version
check_swap (nagios-plugins 1.4.6) 1.58

On Solaris 10:
 ./check_swap --version
check_swap v1859 (nagios-plugins 1.4.11)

I attached the config-Log of our HP-UX 11.23 Machine (PA-RISC 2.0 64bit) with gcc 4.1.1

73 de DF7BE

**Comment by RincewindsHat** [comment]
Is this sufficiently dead/irrelevant to close the issue?

**Comment by RincewindsHat** [comment]
Compiled for me on OpenIndiana
