### ISSUE TITLE
check_ldap should work with all LDAP protocol [sf#2023584]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#813]
Submitted by migrec on 2008-07-21 15:43:55

I've submitted a Debian Bug Report in order to avoid problems with the LDAP protocol.

You can see it at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=491233

So the maintainer tells me that if the default protocol is changed in the check_ldap script, existing installations will be break.

My idea is to made the check_ldap able to work both v2 and v3 protocol of LDAP. We should have the version protocol used (v2, v3 or v2/v3) printed in result of check_ldap.

I don't know how to do it. Is it possible for the team to implement this ? I think there is a lot of advantages to made the script as I explain here (see Debian bug report please).

Thanks,

**Comment by RincewindsHat** [comment]
```
 -2 [--ver2]
    use ldap protocol version 2
 -3 [--ver3]
    use ldap protocol version 3
    (default protocol version: 2)
```
This seems to be implemented if I do understand the problem correctly

**Comment by waja** [comment]
In http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=491233 there is a long discussion, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=491233#40 is a good point so start ...
anyhow this issue is so old and nobody complained since 15 years ... I think this can stay closed.
