### ISSUE TITLE
check_ircd: added ipv6 support and removed unneccessary bind [sf#2114022]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#822]
Submitted by rj667 on 2008-09-16 13:52:33

Patch against Plugin Version: 1.3
Plugin Name: check_ircd
Example Plugin Commandline: check_ircd -H 2001:888:0:2::6667
Tested on operating system: Linux
Tested on architecture: x86_64
Tested with compiler: none (perl-script)
- added IPv6 support
- removed unneccessary bind() call

**Comment by RincewindsHat** [comment]
Closed by #1995
