### ISSUE TITLE
check_ircd: use IO::Socket and Sys::Hostname [sf#2139972]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#824]
Submitted by aitsu on 2008-10-01 11:13:40

Many FreeBSD users of nagios-plugins have reported that the check_ircd plugin simply does not work for them under perl 5.8.8, returning the error:

IRCD UNKNOWN: Could not bind socket (Can't assign requested address)

I decided to help them with this problem, and re-wrote a small bit of code to make use of IO::Socket and Sys::Hostname, both of which are now part of perl.

**Comment by RincewindsHat** [comment]
should be close by #1995
