### ISSUE TITLE
Make check_http post binary data [sf#1712985]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#830]
Submitted by t_pascal on 2007-05-04 20:11:52

This is a horrible hack to post binary data (passed as -P "URL-encoded bin data").

It works, but really needs to be fixed up to check the input and use proper libararies.

I also need to hack it to allow a binary data search for the -s option (which I haven't done yet).

T. Pascal

**Comment by RincewindsHat** [comment]
This one seems really dead. Closing this, for the purpose of tidying up a little bit.
