### ISSUE TITLE
check_disk ignore non-matched regexp [sf#2506958]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#842]
Submitted by paulhaldane on 2009-01-14 13:14:26

Patch against Plugin Version (-V output):
 check_disk v2025 (nagios-plugins 1.4.13)
Plugin Name: check_disk
Example Plugin Commandline:
check_disk -w 10% -c 5% -e -L -A
  -C -w 6% -c 3% -r '._sapdata._'
  -X tmpfs 
Tested on operating system: Solaris 10
Tested on architecture:
Tested with compiler: gcc 3.3.2

Patch adds a new option (-n) which tells check_disk not to exit with error if we use -R/-r and the supplied regular expression doesn't match any filesystems.
We find this useful as we have some filesystems that we run with less free space than others (because the usage will only increase with explicit administrator action) and so want to set tighter thresholds in nrpe.conf.
However if we use the same check_disk options on all hosts, machines which don't have any matching filesystems will flag up an error.
The -n option needs to appear before -R/-r if it's used.

**Comment by marcelfischer** [comment]
Is there still plan to implement that? Would be quite nice to have such an option to ignore this kind of error

**Comment by RincewindsHat** [comment]
Should have the functionality implemented with #1801
