### ISSUE TITLE
check_tcp Segmentation fault on HP-UX 11.23 [sf#1984240]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#844]
Submitted by df7be on 2008-06-04 10:19:43

Hello,
compiled Plugins Version 1.4.12 with gcc (GCC) 4.1.1 the
check_tcp cored at call (with no or any options)
here comes the GDB Backtrace, i hope ths helps.

73 de DF7BE

/usr/local/nagios/libexec> gdb check_tcp core
HP gdb 3.1 for PA-RISC 1.1 or 2.0 (narrow), HP-UX 11.00.
Copyright 1986 - 2001 Free Software Foundation, Inc.
Hewlett-Packard Wildebeest 3.1 (based on GDB) is covered by the
GNU General Public License. Type "show copying" to see the conditions to
change it and/or distribute copies. Type "show warranty" for warranty/support.
..
Core was generated by `check_tcp'.
Program terminated with signal 11, Segmentation fault.

warning: The shared libraries were not privately mapped; setting a
breakpoint in a shared library will not work until you rerun the program.

Process ID is greater than 65535.
#0  0xc06ba404 in pthread_mutex_lock+0x64 () from /usr/lib/libcma.2

(gdb) bt
#0  0xc06ba404 in pthread_mutex_lock+0x64 () from /usr/lib/libcma.2

Cannot access memory at address 0xc06ba390
(gdb)

**Comment by RincewindsHat** [comment]
Closed until someone can verify this again
