### ISSUE TITLE
check_disk - option "--ignore-inaccessible" would be neat [sf#2616403]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#847]
Submitted by cyco_dd on 2009-02-19 15:14:04

The following Bugreport we got against our debian package:

[...]

| weasel@malo:~$ /usr/lib/nagios/plugins/check_disk 90 95
| DISK CRITICAL - /home/buildd/chroots/etch/proc is not accessible: Permission denied

I think this commit is to blame:

| 2007-07-10 20:18  psychotrahe
| 
|         \* [r1754] NEWS, plugins/check_disk.c, plugins/t/check_disk.t:
|           Check_disk now calls stat() for all filesystems to check.
|           Check_disk prints an strerror() message if the call of stat()
|           fails.

[...]

weasel@simona:~$ sudo chmod o-rx /mnt/test
weasel@simona:~$ stat /mnt/test/mountpoint
stat: cannot stat `/mnt/test/mountpoint': Permission denied

[...]

so as discussed on IRC, adding an option "--ignore-inaccessible" would be neat.

You can track the bugreport via
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=516097

I would say, an option, which skips mount points with missing permissions would be a good idea.

With kind regards, Jan.

**Comment by macropin** [comment]
I think this issue is also responsible for various other spurious results such as

`DISK CRITICAL - /sys/fs/cgroup/systemd (deleted) is not accessible: No such file or directory`
or
`DISK CRITICAL - /host/sys/kernel/config is not accessible: Permission denied`

these occur when running `check_disk` in a container environment eg Docker.

**Comment by waja** [comment]
> these occur when running ```check_disk``` in a container environment eg Docker.

You're running ```check_disk``` __IN__ a container?

**Comment by macropin** [comment]
Oh I've done worse. One time I even ran [mailman](https://github.com/macropin/docker-mailman) in a container...

**Comment by RincewindsHat** [comment]
Should be implemented with #1801
