### ISSUE TITLE
Report expect_string in plugin output if test fails [sf#2798295]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#879]
Submitted by patricia_jung on 2009-05-29 10:52:44

Patch against Plugin Version (-V output): check_http v2053 (nagios-plugins 1.4.13)
Plugin Name: check_http 
Example Plugin Commandline: check_http -H www.trish.de -p 80 -L --onredirect=CRITICAL --string "bla"
Tested on operating system: (SuSE) Linux
Tested on architecture: x86
Tested with compiler: gcc (SUSE Linux) 4.3.1 20080507 (prerelease) [gcc-4_3-branch revision 135036]

With more than one website to monitor one does not want to check the nagios configuration in order to find out the expect string configured. This patch reports it and this way relieves stress in case of failure.

**Comment by RincewindsHat** [comment]
Closing this, for the purpose of tidying up a little bit. It is not clear, if this patch would have been accepted in the current state anyway
