### ISSUE TITLE
Range support for check_nt [sf#2804825]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#888]
Submitted by rakhun on 2009-06-11 14:43:20

Plugin name and version: check_nt v1.4.13.138.g9eab.dirty (nagios-plugins 1.4.13)
Example commandline: plugins/check_nt -H IP -v USEDDISKSPACE -l C -w 50 -c 5:95
Tested on: Fedora 10, i686 with compiler gcc (GCC) 4.3.2 20081105 (Red Hat 4.3.2-7)
The patch makes it possible to determine the status based on ranges, like in the example where the status is critical if disk usage is below 5 or above 95 (not the best example, but something might be seriously wrong if the usage gets too low)

**Comment by RincewindsHat** [comment]
Link is dead, closing this

**Comment by sni** [comment]
Btw, those links have been added long time ago, meanwhile they are available under https://www.monitoring-plugins.org/attachments/330612-rangesupport.patch

**Comment by RincewindsHat** [comment]
oh, didn't know that. That make this kinda awkward.

**Comment by RincewindsHat** [comment]
Created an PR, therefore closing the issue
