### ISSUE TITLE
check_jabber: Always returns WARNING with Openfire server. [sf#1939578]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#891]
Submitted by gdrago23 on 2008-04-10 19:20:46

check_jabber always returns WARNING when run against an Openfire Jabber server. It may do so against other servers, but I have no way of checking that.

Running check_jabber -v with no -e, -A or -a arguments shows that it expects the string "<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'". However, Openfire rearranges the namespace definitions; it returns a string beginning with "<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client"". This is exactly as valid, but the hardcoded string doesn't match it, so it always returns "JABBER WARNING - Unexpected response from host/socket on port 5222".

A fix is to look for the three components separately in any order. The attached patch changes check_tcp so that running check_jabber is now equivalent to running:

check_jabber -A -e "<?xml version='1.0' encoding='UTF-8'?><stream:stream" -e "xmlns=\"jabber:client\"" -e "xmlns:stream=\"http://etherx.jabber.org/streams\""

Because the match has been made more general, this shouldn't cause any regressions with regards to other servers being detected.

**Comment by RincewindsHat** [comment]
Might be fixed. Reopen if still present.
