### ISSUE TITLE
check_dns: add AAAA,MX,TXT,SRV,CNAME [sf#2741269]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#894]
Submitted by dhorn2000 on 2009-04-07 19:21:10

Added optional support for the major DNS record types (AAAA, MX, TXT, SRV, CNAME, A, ANY).  Specifically, allow for a new optional --querytype parameter, and a new optional --accept-cname parameter.  Help text has been updated to reflect the changes as well. Patch is against SVN trunk of check_dns.c from April 7,2009.

This change should be completely backwards compatible with existing check_dns usage and syntax.  New features are off by default.

**Comment by ekohl** [comment]
Given check_dig can do this, would it be better to recommend users to use that instead? check_dns is broken anyway because it uses nslookup which is [flawed and shouldn't be used](https://jdebp.eu/FGA/nslookup-flaws.html).

**Comment by sni** [comment]
closing this one, please use check_dig instead.
