### ISSUE TITLE
check_ping ignores -4 option [sf#2832817]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#898]
Submitted by phalenor on 2009-08-05 22:15:37

check_ping v1991 (nagios-plugins 1.4.13)
Solaris 10u5 sparc

check_ping ignores -4 option when the host passed with -H is a hostname which has both A and AAAA records associated with it. Expected behavior is that -4 forces check_ping to use an IPv4 address returned from an A record lookup of the host if a hostname is provided. This is the behavior seen with other plugins such as check_ssh, which correctly query over only IPv4 or IPv6 with -4 or -6 are passed, respectively.

**Comment by riskersen** [comment]
From my perspective, this one is also open, because by now, we're doing following

`		if (address_family != AF_INET && is_inet6_addr(addresses[i]))
			rawcmd = strdup(PING6_COMMAND);
		else
			rawcmd = strdup(PING_COMMAND);`

So the usage of the -4 option should be added to the if clause, i would say.

**Comment by sbraz** [comment]
@riskersen Hi, any chance to see this fixed?

**Comment by RincewindsHat** [comment]
This seems to be fixed, at least it worked for me just now.
