### ISSUE TITLE
check_ntp_xxx ntpd failure handling [sf#2836780]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#899]
Submitted by duncan_ferguson on 2009-08-13 10:39:37

check_ntp and check_ntp_time have both been returning errors recently - compiled up new binaries from nagios-plugins-trunk-200908120000.tar.gz and they show the same behaviour, returning occasional "Offset unknown" messages.

This has been traced back to ntpd occasionally unselecting all ntp servers so the plugin doesn't know which server to refer against, returning the error.

The plugin should return a more meaningful error about no selected ntp server

This was seen on Ubuntu Hardy 8.04 on both 32 and 64 bit servers compiled with gcc

**Comment by RincewindsHat** [comment]
Unclear whether this is still a thing. Closing this for cleanup.
