### ISSUE TITLE
freebsd: fails on make [sf#2865114]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#908]
Submitted by charlo212 on 2009-09-23 18:31:03

Hi,

Trying to compile the plugins on a freebsd 6.3 box. The configure stage looks okay but it fails on make with the following....
- SNIP -
  if gcc -DLOCALEDIR=\"/usr/local/nagios/share/locale\" -DHAVE_CONFIG_H -I. -I. -I.. -I.. -I../lib -I../gl -I../intl   -I/usr/include    -DNP_VERSION='"1.4.14"' -g -O2 -MT check_http.o -MD -MP -MF ".deps/check_http.Tpo" -c -o check_http.o check_http.c;  then mv -f ".deps/check_http.Tpo" ".deps/check_http.Po"; else rm -f ".deps/check_http.Tpo"; exit 1; fi
  check_http.c:63: error: syntax error before '_' token
  check_http.c:63: warning: data definition has no type or storage class
  *_\* Error code 1

Stop in /home/nagios/nagios-plugins-trunk-200909231200/plugins.
**\* Error code 1

Stop in /home/nagios/nagios-plugins-trunk-200909231200.
**\* Error code 1

Stop in /home/nagios/nagios-plugins-trunk-200909231200.
- SNIP -

Host Details:
uname -m = i386
uname -r = 6.3-RELEASE
uname -s = FreeBSD
uname -v = FreeBSD 6.3-RELEASE #3: Fri Jan 23 16:43:41 MST 2009     root@fc:/usr/src/sys/i386/compile/VKERN 

I've tried to upload my config.log but it's 504k and the restriction is down to 2XXk

Let me know what else you'd need or if anything needs to be taken from the config.log that would help.

Charlie

**Comment by RincewindsHat** [comment]
impossible to reproduce by now
