### ISSUE TITLE
check_disk shows â€œ/ not foundâ€ on Solaris [sf#2874581]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#913]
Submitted by testtest5 on 2009-10-08 10:56:49

This issue occurs when the 0-byte regular file /etc/.mnttab.lock is present on the Solaris host being monitored. 
The workaround is to delete /etc/.mnttab.lock
Is this fixable?

(I think this is the same issue as #1490762 but I can't re-open that bug)

**Comment by RincewindsHat** [comment]
Closing this until someone can verify
