### ISSUE TITLE
New parameter for check_nwstat [sf#2898995]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#918]
Submitted by jottschi on 2009-11-17 11:19:14

This adds the new VPU parameter to the check_nwstat plugin. This parameter returns the percentage used space on a Netware volume.
Now you can monitor your Netware volumes easy. We use it with a warning 85% and critical 90%.
eg: check_nwstat -H your.netware.host -v VPUvol1 -c 85 -w 90 returns
324653 MB (95%) used on volume vol1 - total 340212 MB|Used space in percent on vol1=95;90;80;0;100.

**Comment by RincewindsHat** [comment]
closed by #1183
