### ISSUE TITLE
Unspecified performance data format for threshold ranges [sf#2952850]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#929]
Submitted by patricia_jung on 2010-02-16 16:41:55

Hello there,

for thresholds given as ranges it still seems that performance data can't be implemented properly as the developer guidelines do not specify an appropriate format. I am aware of that this is a known issue (see e.g. http://nagiosplugins.org/rfc/new_threshold_syntax), but I would like to know whether there has been some progress recently.

If so please change the developer guidelines accordingly, if not please provide a specification.

Thanks

  Patricia

**Comment by RincewindsHat** [comment]
https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
