### ISSUE TITLE
check_ldap doesnot compile on OpenSolaris [sf#2972610]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#932]
Submitted by wernerfrerichs on 2010-03-18 15:19:35

root@nagmon:~/nagios-plugins-1.4.14# uname -a
SunOS nagmon 5.11 snv_111b i86pc i386 i86pc Solaris
root@nagmon:~/nagios-plugins-1.4.14#  ./configure --prefix=/usr/nagios --enable-perl-modules
root@nagmon:~/nagios-plugins-1.4.14# make
...
root@nagmon:~/nagios-plugins-1.4.14# cd plugins
root@nagmon:~/nagios-plugins-1.4.14/plugins# make check_ldap
gcc -DLOCALEDIR=\"/usr/nagios/share/locale\" -DHAVE_CONFIG_H -I. -I.. -I.. -I../lib -I../gl -I../intl   -I/usr/include   -DNP_VERSION='"1.4.14"' -g -O2 -MT check_ldap.o -MD -MP -MF .deps/check_ldap.Tpo -c -o check_ldap.o check_ldap.c
mv -f .deps/check_ldap.Tpo .deps/check_ldap.Po
/bin/sh ../libtool --tag=CC   --mode=link gcc -DNP_VERSION='"1.4.14"' -g -O2  -L. -o check_ldap check_ldap.o netutils.o utils.o ../lib/libnagiosplug.a ../gl/libgnu.a  -lnsl -lsocket -lresolv  -lpthread -ldl 
gcc "-DNP_VERSION=\"1.4.14\"" -g -O2 -o check_ldap check_ldap.o netutils.o utils.o  -L/root/nagios-plugins-1.4.14/plugins ../lib/libnagiosplug.a ../gl/libgnu.a -lnsl -lsocket -lresolv -lpthread -ldl
Undefined                       first referenced
 symbol                             in file
ldap_bind_s                         check_ldap.o
ldap_perror                         check_ldap.o
ldap_unbind                         check_ldap.o
ldap_open                           check_ldap.o
ldap_search_s                       check_ldap.o
ld: fatal: symbol referencing errors. No output written to check_ldap
collect2: ld returned 1 exit status

**Comment by RincewindsHat** [comment]
Open Solaris is dead
