### ISSUE TITLE
check_time.t and check_udp.t fail  [sf#2973604]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#933]
Submitted by bekar on 2010-03-20 02:55:20

Using a Centos 5 system, both of these test packages don't work properly as their contents describe.

check_time.t uses variable names including 'udp', yet the '-u' flag isn't passed to the check.  As it does both tcp/udp the test should probably seperate them out and do both.

check_udp.t fails on the behaviour of 'nc' on the system.  I've had to add in:

```
   skip "No compatable netcat available", 6 unless (system("nc -l -w 1 -p 3333 -u > /dev/null 2>&1") == 0);
```

to skip these listener check for the moment.

**Comment by RincewindsHat** [comment]
not sure if this still happens, hopefully not.
In any case CentOS 5 is long dead.
