### ISSUE TITLE
check_http HTTP CONNECT through proxy patch [sf#2975393]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#934]
Submitted by mfrostp83 on 2010-03-23 19:43:51

check_http cannot (as of 1.4.14) speak the HTTP CONNECT protocol through a proxy.  This is primarily used for checking SSL through a proxy.  The attached patch allows this functionality by using the -K or --http-connect flag telling check_http to connect with HTTP CONNECT.

Note that this option depends on SSL being enabled and will only connect to a remote host using port 443 which is not adjustable from the command-line.

**Comment by RincewindsHat** [comment]
Seems to be obsolete with https://github.com/monitoring-plugins/monitoring-plugins/commit/342dd1b97fd3423cb6368fedbb6c729f3c3b6243
