### ISSUE TITLE
check_procs on HP-UX fails to get arguments [sf#2998162]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#958]
Submitted by semaphoric on 2010-05-07 15:23:30

In reference to Track ID: 948667

ps -el does not show all arguments on HP-UX

ps -elx does ( at least for 11.11 and greater ). We tested this on the following systems:

---

HP-UX XXXXXXXX B.11.11 U 9000/800 1114444681 unlimited-user license

/usr/bin/ps -elx | head -2

F S        UID   PID  PPID  C PRI NI             ADDR   SZ            WCHAN TTY       TIME COMD
1003 S          0     0     0  0 128 20           c0fd80    0                - ?         0:25 swapper

/usr/bin/ps -elx | grep ssh
  1 S          0 16804 16555  1 154 20         4ab17940   23         48c3fbee pts/0     0:00 grep ssh
  1 S          0 16552 20702  0 154 20         4aac3540  341           b0f1a0 ?         0:00 sshd: root@pts/0
##   1 S          0 20702     1  0 154 20         4b1cc800  305           b0f1a0 ?         6:46 /opt/dcx/openssh/sbin/sshd -f /opt/dcx/openssh/etc/sshd_config

HP-UX XXXXXXXX B.11.23 U 9000/800 929037533 unlimited-user license

/usr/bin/ps -elx | head -2
  F S        UID   PID  PPID  C PRI NI             ADDR   SZ            WCHAN TTY       TIME COMD
1003 S          0     0     0  0 127 20          112bd80    0           faf064 ?         7:16 swapper

/usr/bin/ps -elx | grep snmp
  1 R          0  8291  8190  0 154 20         56fee280   23                - pts/0     0:00 grep snmp
##   1 S          0 24003     1  0 154 20         58f44b80  118         415c1040 ?         8:54 /sysmgmt/opt/net-snmp/sbin/snmpd -p /sysmgmt/opt/net-snmp/var/net-snmp/snmpd.pid 0.0.0.0:8161

HP-UX XXXXXXXX B.11.31 U ia64 3285774567 unlimited-user license

/usr/bin/ps -elx | head -2
  F S        UID   PID  PPID  C PRI NI             ADDR   SZ            WCHAN TTY       TIME COMD
1003 S          0     0     0  0 127 20 e0000001005e3010    0 e000000100000004 ?        79:17 swapper

/usr/bin/ps -elx | grep agentx
401 R          0  1288     1  1 152 20 e0000007e0c5ac00  859                - ?        84:47 /sysmgmt/perl/bin/perl /sysmgmt/sat/monitoring/bin/sat_agentx -a -p /sysmgmt/sat/monitoring/var/log/sat_agentx.pid
401 S          0 11517 11456  0 128 20 e0000007e816b780    2 e0000008a8567880 pts/0     0:00 grep agentx

HTH

**Comment by RincewindsHat** [comment]
Please open this if you have a HP UX at hand
