### ISSUE TITLE
URL for check_game not available anymore [sf#3004910]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#960]
Submitted by madolphs on 2010-05-20 22:45:24

While ./configure it's been said that one should get qstat from http://www.activesw.com/people/steve/qstat.html. The site seems to be no longer available. http://www.qstat.org/ seems to be more appropriate.

configure, lines 19373,19374

Regards,
Mike Adolphs

**Comment by RincewindsHat** [comment]
Fixed in #1725
