### ISSUE TITLE
check_mailq.pl ignores separate submission queue [sf#3112695]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#972]
Submitted by jwm on 2010-11-19 16:23:52

check_mailq.pl ignores the separate submission queue used in (modern?) sendmail implementations.

For the queue output below with one message in the submission queue and no messages in the transport queue, check_mailq.pl reports zero messages in the queue because the request count from the last queue always overwrites previous queues. If the sendmail MTA isn't running or has become wedged, messages will sit in the submission queue forever.

The attached patch fixes this in a backwards compatible way (i.e., it shouldn't break any of the currently supported formats).
```
## MSP Queue status...
## /var/spool/mqueue-client (1 request)
## -----Q-ID----- --Size-- -----Q-Time----- ------------Sender/Recipient------
## oAJEfhdW014123        5 Fri Nov 19 14:41 jwm
## (Deferred: Connection refused by [127.0.0.1])
## root
## Total requests: 1
## MTA Queue status...
## /var/spool/mqueue is empty
## Total requests: 0
```

**Comment by moschlar** [comment]
Could the corresponding PR please be merged?

I successfully tested it in our infrastructure.

**Comment by RincewindsHat** [comment]
#1192 would be that PR

**Comment by waja** [comment]
> I successfully tested it in our infrastructure.

How could multiple queues setup? We run just postfix as MTA here.

**Comment by moschlar** [comment]
I'm not the Sendmail expert here, but AFAIK it is just the current default in a default Debian Sendmail installation, that there are two queues, one to which the `sendmail` program run locally delivers into and the other (main) one, which has all outgoing mail.

For testing it, I did the following:

- block outgoing traffic to port 25
- stop sendmail service
- run a proper local sendmail command to send me a test email
- mailq shows the mail in the first queue
- start sendmail service
- mailq shows the mail in the second queue
- allow outgoing traffic to port 25
- mailq shows two empty queue
