### ISSUE TITLE
check_dns returns incorrect state when specifying server [sf#2946553]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#982]
Submitted by dicko82 on 2010-02-05 14:59:49

Plugin Version (-V output): check_dns v1992 (nagios-plugins 1.4.13)
Plugin Name: check_dns
Plugin Commandline showing issues: /usr/lib/nagios/plugins/check_dns -H www.test.com -s 1.1.1.1
Operating System: Red Hat Enterprise Linux Server release 5.4 (Tikanga)

An incorrect state is returned when checking that the dns server ( 1.1.1.1 ) can resolve the host www.test.com when the dns server is down. The following command is used

 /usr/lib/nagios/plugins/check_dns -H www.test.com -s 1.1.1.1

If the DNS server is unavailable the check still returns OK. This worked correctly on RHEL 5.3 but not in Rhel 5.4

It appears that the behaviour of nslookup has changed between 

bind-utils-9.3.4-10.P1.el5

and 

bind-utils-9.3.6-4.P1.el5

On RHEL 5.3  bind-utils-9.3.4-10.P1.el5, nslookup timed out when querying against a server that was not working. 

[root@nagios nagios]# nslookup www.rm.com 194.238.49.43
;; connection timed out; no servers could be reached

On RHEL 5.4 bind-utils-9.3.6-4.P1.el5, the same query against a non existent dns server returns an ip address.

[root@nagios ~]# nslookup www.rm.com 1.1.1.1
Server:         10.34.1.11
Address:        10.34.1.11#53

Non-authoritative answer:
Name:   www.rm.com
Address: 2.2.2.2

It appears that nslookup now makes best efforts to resolve the query even if it cant resolve it against the server specified. This results in an incorrect state being returned when using check dns to ensure that a specific mail server is working correctly.

**Comment by ghstwhl** [comment]
Hello from the year 2020.  We have Tiger Kings, Murder Hornets, Mask Riots, and a check_dns that still returns OK if you specify the server and it isn't available.  (We also don't have flying cards, but that's a issue to be logged in a different repo...)

bind service running:
```
# /usr/lib/nagios/plugins/check_dns -H www.ghostwheel.com -s ns2.ghostwheel.com
DNS OK: 0.011 seconds response time. www.ghostwheel.com returns 38.99.95.53|time=0.010614s;;;0.000000
```

bind service stopped:
```
root@p7:~# /usr/lib/nagios/plugins/check_dns -H www.ghostwheel.com -s ns2.ghostwheel.com
DNS OK: 0.010 seconds response time. www.ghostwheel.com returns |time=0.009621s;;;0.000000
```

Note that in the second example there is nothing after returns, so it failed to get a response at all, and yet the status is OK.
