### ISSUE TITLE
check_http: gzip deflate chunked problem [sf#3294169]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#994]
Submitted by pzlatcpp on 2011-04-28 04:24:57

check_http can't deal with compressed data by gzip or deflate and also can't surpport chunked data. This patch add some functions to deal with the above situations. We add two parameters to commandline -d/--decompress and -X/--chunked; when users want to surpport gzip and deflate data format the can use -d; when they want to deal with chunked data they can use  -X.

Plugin Version: check_http v1.4.15.23.g1bc7.dirty (nagios-plugins 1.4.15)
Exmaple Commandline: ./check_http -H www.aipai.com -p 80 -t 60 --header='Accept-Encoding: gzip,deflate' -u /hredu.html -v -d -X
Tested on Operating system: debian 6
Tested with complier: gcc 4.4.5

**Comment by alaslums** [comment]
6 years later... tumbleweeds drift by...

```
.................................................
.                                   |           .
._-""--__                    '.  \  |  /  .'    .
.  |j  _-'"-__-"=         ~    '. \ | / .'      .
. L| -'   _-'    '=        _____-- .-. -______  .
.  | L|_,    . * ."=_-_________---' ~ '---______.
.     |      _\|/_             ,'~~~~~~~'  | ~-_.
.                      ~~~   <')  ~~~     L|,   .
.                  ~~~~~     (_\\          |    .
.                             ||\\              .
.           .-.               ((__))            .
.          (  o)-.            ( O O)            .
.           ) )\|\)            "\_\\.-~         .
.        _./ (,_    Yes,         "'             .
.       ( '**"  )  the Dead Cow restaurant used .
.       \\\   ///    to be here, but its been   .
.        \\\ ///    closed for quite some time. .
.         //|\\                                 .
.        ///|\\\                                .
..............................................MJP
```

**Comment by sni** [comment]
please give the check_curl from the feature_check_curl branch a try.

**Comment by RincewindsHat** [comment]
Chunked encoding is now implemented, deflate will probably not implemented at all. closing this therefore.
